### ISSUE TITLE
Gender differences over time in Japanese and Korean speech

### ISSUE THREAD

**Issue by brucknerp** [obdurodon/dh_course#12]
English differentiates between gender in pronouns and possessives, but unlike some other languages it does not have gendered language in syntax, words, and morphology. Japanese (and to some extent, Korean) is one of these languages--certain speech patterns are considered “manly” and others “womanly”, determined by the patterns’ relative roughness or softness. I.e. women’s language is usually associated with things like using more polite forms or speaking with a higher vocal register. While Korean does not explicitly mark gender grammatically like Japanese, different genders utilize different levels of politeness at varying rates, and there are phonetic differences (like vowel quality) within language use by men and women as well. For example, men use the deferential form more often because it has military connotations, and there is a mandatory military service for men in the country. 
             As women’s rights/feminist movements are becoming more mainstream today, I want to look at whether the language use differences between genders has changed from past years, and in what ways in Korean and Japanese. As more women enter the workforce in Japan, is their speech changing? Are they using patterns that are “womenly” or “manly”? When did the differences in sentence endings change in Korea between genders?
	To answer this question, we need texts with lots of dialogue or speech, or a transcription, as regular literature is gender neutral. For the time span, it will depend on constraints, but one approach is to start from around the 1970’s, the time of the women’s liberation movement, to the present, but the specific text is still undecided. We would pick several characteristics in both languages, whether a specific word, honorific level, or speech pattern ending, among other things, and track their frequency throughout each text and over time between genders, to see if any linguistic devices have become more or less popular, or persisted in society.
	I am a linguistics major, so I am interested in these types of sociolinguistic changes. Anyone interested in Japanese, Korean, Linguistics, or gendered language, or who just thought this was interesting should join!

**Comment by amk231** [comment]
The project I worked on last year gave some attention, though sadly not enough for my liking, to the differences between male and female poets in the oldest existing collection of Japanese poetry, the Manyoshu. Originally, we wished to look at whether or not there were substantial differences in topics, imagery, word choice, and to whom the poems were addressed to, however, since I was working in translation a lot of the original content was lost or at least altered. 

I noticed one of your previous assignments was in Japanese, and if you are able to read the texts directly you will greatly benefit from that. This type of research easily lends itself to the sorts of document analysis we do in this class and I think this would be a super interesting project! I am wondering if you were planning on comparing the differences in your findings between Korean and Japanese or if these would be primarily separate topics? You would also have to give some thought (as you have already begun) to the sorts of texts you would be using, as language greatly changes depending on the formality of the discussion, as well as the topic of the discussion. 

I look forward to hearing more about this project!

**Comment by gmd29** [comment]
This sounds really interesting! Sadly, I don't know Japanese or Korean, though. Let me know if you'd like to work together considering another language and gender project in English (It would be interesting to track use of singular they) or if you think this project would be possible without knowledge of Japanese and Korean.

**Comment by brucknerp** [comment]
Gina and I are working on this together, we will be using pop songs over several decades as our text to look for potential changes in language use by gender over time--specifically looking at morphology and syntax.

Here is the repo:
https://github.com/brucknerp/jpn_gen_pop
