### ISSUE TITLE
Alice in Translation

### ISSUE THREAD

**Issue by enb34** [obdurodon/dh_course#21]
Our project will focus on the translation of rhymes, songs, and nonsense words into Japanese in Lewis Carroll's _Alice's Adventures in Wonderland_.

The repo can be found here: [https://github.com/enb34/alice-in-translation](https://github.com/enb34/alice-in-translation)

**Comment by ebeshero** [comment]
Uh oh! This link isn't working. Notice why: In your markdown, you have: 
``
 [https://github.com/enb34/alice-in-translation](url)
``
You need to replace the word "url" with another copy of the web address, thus:
``
 [https://github.com/enb34/alice-in-translation](https://github.com/enb34/alice-in-translation)
``
You can correct this by using the pencil icon on the Issue here and editing your post! :-)

**Comment by djbpitt** [comment]
I see that the link has been fixed, but I wanted to mention that there are two ways in markdown to expose a link and make it clickable:

```markdown
[http://example.com](http://example.com)
```

and

```markdown
<http://example.com>
```

In the second of these, the user sees the literal URL. In the first, the user sees the thing in square brackets, but clicking goes to the thing in parentheses. This means that you can do something like:

```markdown
Here is my [terrific project site](http://terrific-project-site.com)!
```

and the clickable link will read just "terrific project site", without displaying the URL.
