### ISSUE TITLE
Line-breaks as milestones vs. wrapped elements

### ISSUE THREAD

**Issue by pickettj** [obdurodon/dh_course#233]
I am trying to decide between linebreak milestones `<lb/>` vs line elements `<l>text</l>`. Line breaks would seem to be the best option, since they allow for the tagging of thematic sections that span one line to the next without breaking element nesting rules (e.g. `<l> text <ts> text </l> text </ts>` is ill-formed (is that a term?), whereas `<ts> text <ls/> text </ts>` is well formed. This is probably why `<lb/>`is the standard for the [Epidoc TEI variant](https://sourceforge.net/p/epidoc/wiki/Home/).

However, there is one minor, but distracting, problem specific to using Oxygen with Arabic script. In order to keep the text all going in the right direction, I set rules to put in a line break every time there is a new element, in order to keep things readable. The reason I liked having the full `<l></l>` wrapped element is that it kept the lines indented and visually separate from one another. As a milestone `(<lb/>)`, all the lines are indented to the same level such that it is difficult to tell them apart.

I.e. in this screenshot the lines are indented the same as all the other elements within the line, which is confusing:

![image](https://user-images.githubusercontent.com/25989796/51803450-5a8e8480-2223-11e9-9d86-a6010544a8be.png)

But here (i.e. with wrapped elements) it is much easier to read:

![image](https://user-images.githubusercontent.com/25989796/51803474-9c1f2f80-2223-11e9-80d5-4e26b0497934.png)

Is there a way to have the best of both worlds? Or other recommendations?

**Comment by zme1** [comment]
A quick note on your post: Instead of including screenshots of your code, consider using the block-level code delimiters to include it directly in your post. Similar to the inline code delimiters, you'll surround the code with Tilde characters, except instead of using just one, you'll use three before and after your block of code. It will look like this when you publish your post:

```
<code>
   <snippet>Code here.</snippet>
</code>
```

Re: your question, using either wrapper `l` elements or empty `lb` elements will not necessarily impact your ability to ultimately render the texts (i.e. you will have the same ability to manipulate them when it comes time to publish reading views), but the disadvantage with the `lb` elements in your case is, rather than distinguish one line from another when pretty-printed, it will be formatted as an inline element, which means it will be formatted just like running text. My advice for you, then, is to give preference to legible formatting in your &lt;oXygen/&gt; viewing window by wrapping your lines in `l` elements. To avoid overlapping hierarchies, you can use discontinuous virtual elements to connect wrapper elements like `ts`, which would *also* be written as "empty" elements, but the "start" and "end" tags would be unified in a shared attribute value, which you could later use for processing. You'll find this strategy briefly discussed in Issue #194 , along with two other common alternatives. Below is an example of discontinuous virtual elements in action:

```
<l>Normal text here. <ts group="1"/>Thematic text</l>
<l>here.<ts group="1"/></l>
```

**Comment by pickettj** [comment]
@djbpitt Right, an Oxygen rule to double-indent certain elements would effectively get the best of both worlds... but I can't quite figure out how to do that. I only see rules for adding a linebreak after specific elements.

@zme1 The "discontinuous virtual elements" workaround is a good idea, but one that I try to avoid to the extent possible. Just because it is an added manual step that ends up costing time, which adds up. I think I'd rather live with the formatting drawbacks of the milestone `<lb/>`, since `<lb></lb>` doesn't actually add any information. As you say, once we learn how to quickly produce effective reading views, this will be less of an issue...

**Comment by djbpitt** [comment]
@pickettj I think the only way &lt;oXygen/&gt; lets you specify something like double-indentation is with CSS in Author view, and I don't know whether that plays well with right-to-left scripts. Setting up your own CSS for Author view is also a bit of a slog, although given the size of your project, it might be worth the effort. See <https://www.oxygenxml.com/doc/versions/20.1/ug-editor/topics/dg-css-support-in-author.html>.
