### ISSUE TITLE
Question about ampersands and quotation marks

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#234]
For my first XML assignment I put angle brackets around &quot because I thought I had to, the tutorial is a little vague as to why I would want straight quotation marks v regular ones, but I thought it was because you can't use the regular ones in XML. The explanation I was given was not helpful and I still don't understand what I did wrong. When you use an ampersand for example, do you put it in angle brackets or not? This is unclear and I cannot proceed without a yes or no answer.
I assume that Shakespeare uses the ampersand and I just want to be sure I a replacing it with the right thing. So, does &amp go inside of angle brackets or not? Thank you!

**Comment by zme1** [comment]
It sounds like you're searching for XML reserved characters (`<`, `>`, and `&`) in your Regex assignment to replace them with their XML entity strings, but I'm not entirely sure so correct me if I'm wrong in that assumption.

Our course's tutorial, [An even gentler introduction to XML](http://dh.obdurodon.org/what-is-xml.xhtml), has a section called "Entities and numerical character references" (which you'll find about 45% of the way down the page) that is dedicated to the explanation of what these reserved characters are, and what their corresponding XML entities, i.e. the bits of code that represent those literal characters, look like in an XML document. In short, we write these XML entities when we want the *literal* character to appear in the text, rather than something the XML processor would interpret as code.

In order to find and replace any reserved characters, all that's required for you to do is to, from your Find and Replace window, search in turn for each of those *literal* characters that you'd want to replace. If the search returns no matches, then you don't need to worry any more about them! If they *do* return any reserved characters, write the corresponding XML entity (which you'll find in the discussed section of the reading above) in the Replace window, and that should swap out all your literal reserved characters for their corresponding character entities.

**Comment by zme1** [comment]
As a side note, you'll want to do this before you write any code! Otherwise, you'll end up swapping any angle brackets, i.e. characters that you actually *want* the validator to interpret the characters as code, with their XML entities.

**Comment by djbpitt** [comment]
@spkellyo 

> When you use an ampersand for example, do you put it in angle brackets or not? This is unclear and I cannot proceed without a yes or no answer.

The answer is no. You do not put ampersands inside angle brackets. You put element names inside angle brackets (along with attributes, if there are any). Example:

```xml
<name type="retain">A &amp; P</greeting>
```

When this is rendered eventually as plain text, the textual content will show up as “A &amp; P”, that is, XML processing will recognize that when the developer types `&amp;` as part of the textual content (not markup), that should be understood as representing an ampersand character.

**Comment by spkellyo** [comment]
Thanks djbpitt, that was what I wondering about. zme1 I was following the tutorial for last night's assignment step by step and adding them in first was not mentioned so I didn't do it, but that's good to know for the future. But I was literally asking whether or not they go in brackets because that is unclear in the tutorial probably because it is a pain to add in all the tags saying you want to show the angle brackets or other reserved characters, but as a novice I feel like it needs to be stated one way or the other for clarity (but I am a communication person not a tech person, so I look at it differently.) Thank you both.

**Comment by djbpitt** [comment]
@spkellyo If you have specific rewordings in mind that you think would improve the clarity of the tutorials, please feel free to contribute!
