### ISSUE TITLE
Project Repo

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#239]
# Yugoslav Folklore

This project repo is a description of our project concerning the role gender plays in Yugoslav folksongs and poetry. 

# _Link_: [https://github.com/emmamamula/Yugoslav-Folklore](url)

**Comment by djbpitt** [comment]
@emmamamula The link you’ve posted is broken because it includes the `/invitations` bit at the end. That gets appended when GitHub sends a collaboration invitation, but the address for visitors (that is, the address your classmates will use) is just <https://github.com/emmamamula/Yugoslav-Folklore>.
