### ISSUE TITLE
Single-Issue discussion: GitHub and the command line

### ISSUE THREAD

**Issue by zme1** [obdurodon/dh_course#247]
Since your first encounter with the command line and GitHub, how has your understanding of these technologies changed? What obstacles still affect your understanding of its use? On GitHub specifically, which features stand out as useful tools for your project team? How would you plan to implement them? Which features do you want to learn more about?

**Comment by sjw82** [comment]
I initially struggled to create a local connection with Git. Now I can say that I understand its purpose and terminology, but can’t claim to be capable with its application. Yesterday I had to push some code to Github and I had the same issues as my first time using the command line, having difficulty with restarting from the beginning rather than from the previous step when things would become fatal. I would like to get more practice with command line; inexperience is the main problem as the primary obstacle is the interface.
Github was easier to pick up; the interface is more intuitive. I like Github a lot, particularly the issues and projects. The project tab is useful because it allows the user to visualize procedures and progress. Also being able to have different project boards allows for more concentration; for example in our project we might end up with a project board dedicated solely to the different verses, each card corresponding to an issue with a checklist of steps of analysis to be done for the verse. Being able to tailor the columns also allows more specificity; for example I have a board that says: to-do, in progress, requires mentor attention, done. I didn’t like having things in-progress that I could no longer work on, but the project board accommodates that. And since each card can be an issue, it is easy for the mentor to then go on and respond thoroughly, not being limited to a little project card.
Issues similarly allow for complexity as they’re essentially blog posts but for this reason also contribute transparency to the project. The viewer as well as the participants in the project can see the logic behind each step as it is explained in prose and not limited to a task on a to-do list. Particularly the assignee option on issues is valuable because it allows clarity in who is responsible for what and notifies the person that it has become their task, improving team efficacy.

**Comment by Ethandaniel47** [comment]
I have, in fairness, often felt more confused than I have triumphant when it comes to dealing with much of this new technology. Formerly, I had basically only used my computer to access Word documents and the internet, so I was unaware that I was even able to access these things, such as the command line, from my desktop. I still feel like I often struggle understanding the language of these technologies, but I am getting more comfortable as the semester wears on. 
GitHub has been, despite my initial issues with Pitt's quarantine filter, much easier to access. I think that the interface is accessible and intuitive for new users. I am able to navigate my own repo as well as the course repo without much trouble and I understand the hierarchy of issues and comments and the like. I think that having a place like GitHub will come in handy when it comes to working on our project because in dealing with Poe's poetry, it will be many small pieces that involve close reading. I imagine tackling a single poem at a time, so it will be nice for the three of us to be able to compile and edit all of our work by accessing Git and GitHub.

**Comment by Guifindor** [comment]
Ever since I have been introduced to the Git bash, I have grown comfortable with the Git Bash. Most of the commands feel intuitive to use, and it runs smoothly for the most part. The only command that continues to confuse me is checkout. It works most of the time, but then there's the very rare occasion where it just flat out breaks and the head refuses to re-attach itself to the current checkout version. It's solvable, but it takes a little bit to fix it every time it does happen. Otherwise, I mostly understand the technology of Git.
I feel that one useful feature would be the Kan Ban board. Even if it doesn't get used a 100% to it's original purpose, being able to visually set goals and tasks would be really helpful to tracking our progress. I imagine that we would try to use it to it's original purpose as much as possible, using it to create goals, designate tasks to members and track their progress. Plus, it would give a sense of satisfaction if we finish all that we set out to accomplish.  One feature I would like to learn about would be the branching feature of Git/GitHub. It is one feature I have not played around with yet because there really hasn't been a need for it yet. Yet, I imagine it has some hidden potential that could be very useful for maybe not necessarily this semester's project, but for another project further down the road.

**Comment by MLuckman** [comment]
GitHub is comparatively easy, because you can see what is going on and when you aren't using the command line, it's pretty simple. Git proper, the command line, is much more difficult because it gives limited feedback and you can't really see where you're going wrong. 

GitHub's projects tab seems useful for tracking progress. One thing I'm interested in is file organization. Right now, it seems like the only way to deal with files is to dump them into a repo in a single giant mess. I want to be able to organize things more: a folder for poems, divided into subfolders for B/C/S and English-language, stuff like that.

**Comment by emmamamula** [comment]
Upon initial use, the command line and GitHub were both things that I saw as only being essential to the course. Now, after I have had the opportunity to practice a bit more I see that both of these resources are tools that will be essential not only relative to this course, but also to future projects and group collaborations. The command line especially seemed daunting and though it would be impossible to use, but even after just using it to change my password I already feel more comfortable with it.
I think the biggest obstacle I am facing is that everything is still relatively new and I do not yet have all of the information to feel entirely comfortable. But I am sure this will soon pass once we begin more rigorous work on our site and after I have more time to work with Github and the command line. Another thing I am still shaky on is pulling things from my computer and putting them onto GitHub, but again I think it will soon become second nature with more practice. Even just through the beginning steps of our project I am recognizing that the organizational aspects of GitHub will be extremely useful not only for project creation, but also for communication among group members. The todo notes are great for staying on track and also just for serving as a reminder of the group's timeline and goals. Overall, the ability to easily record and keep track of current and completed tasks is what I believe will be most useful in this process. I want to know more about the Wiki feature of GitHub, it seems like something that could potentially be useful.

**Comment by rmf96** [comment]
Before my first encounter with the command line and GitHub, I had zero knowledge or understanding of such technology. After reading through the tutorials and information pages, I now have a relatively simple understanding of the technologies and how to use them. I think that the only obstacles that would still affect my ability to use the technologies is just lack of practice, which can be fixed with some more intensive reading and practicing. As for GitHub, I think it is very useful to have a common place where everyone in the project team can easily access all related information. This will be specifically useful in the beginning stages of our project while we are collecting and forming our corpus that we will be analyzing. I would however like to learn a little more about how and where to upload different categories of things (for example, we are going to have three separate categories within our corpus) within GitHub.

**Comment by k-busko** [comment]
Initially I had a very narrow view about the capabilities of GitHub. It wasn't until I was actually on the computer during my downtime on Reddit that I noticed that a lot of the moderators on that site use GitHub to organize their information and data and even respond to issues users of the site have directly. I am still struggling with how to navigate the cite because I am still new to programming terminology so I am a bit slow when it comes to understanding features of the site. In regards to my group project, the ability to post and address issues in real time as they are posted makes addressing problems and formulating new ideas easier as a group that is not always in the same physical location. One feature that I would really like to learn how to use is the task tagging feature where you can task out group members with specific jobs or roles so they know exactly what is expected of them.

**Comment by pickettj** [comment]
I'd like to develop a better technical understanding of what git is doing behind the scenes. I think I get the conceptual model behind the workflow (e.g. add vs. commit vs. push). But I don't quite understand what ties a directory on one's computer to the master. For instance, when you git init, is that creating an invisible file within the directory that saves the information that the remote directory is connected to the master? In other words, where on the local system is git keeping one's settings?

**Comment by djbpitt** [comment]
@pickettj First the trigger warning: nobody has to know anything I’m going to write about here. This is a response to James’s inquiry about what goes on inside Git, and the first part of the answer is that we don’t have to know that any more than we have to know what goes on inside our cell phones. But if you’re curious:

1. A Git repo on your local machine stores a bunch of information in a hidden directory called *.git*. You can look inside it if you want (at the command line inside the top-level directory of your repo, type `ls .git` (note the dot!). You are exactly correct about what `git init` does; it creates this hidden directory and sets up and initializes the housekeeping files and subdirectories. It configures a master branch by default, and you can create others yourself as you need them. 
1. You can read about how Git stores and manages information about the repo at <http://www.mit.edu/~mtikekar/posts/2013-09-02-git.html> and <https://wildcardcorp.com/blogs/what-the-heck-is-git-doing>. The second of those pages contains links to additional information.

**Comment by djbpitt** [comment]
@MLuckman Command-line Git is challenging at first because we’re staring at a blank command line, where we could type absolutely anything. You can remind yourself of common (and even some not-so-common) Git commands by typing `git help` inside your repo. There are plenty of Git features that we use so rarely that we have to look them up when we need them, but you’ll become comfortable with the common stuff pretty quickly.

As for the giant mess you mention, your repo is hierarchical because it’s part of your file system, and you should organize the contents into subdirectories. Your project mentor will discuss that with you during a project meeting because projects sometimes have individual requirements, but this is a good time for you (and everyone) to take a first look at our [Project directory and file structure](http://dh.obdurodon.org/project-structure.xhtml) guide.

**Comment by pickettj** [comment]
@djbpitt thanks! That makes sense. This is why, I suppose, it doesn't actually matter what the name of your local repo is, because there is a hidden .git configuration files that sit there in the background and tell git which of your local folders correspond to which online repo. This is also why when you navigate to a different directory and commit something, git already knows that it is supposed to target a (potentially) different online master repo. And this is also why there are all of those mysterious git commands out there that can allow you to tinker with those settings stored in the hidden files via the command line.

**Comment by djbpitt** [comment]
@Guifindor The elevator pitch about branches is that the master branch (which every repo includes automatically) should normally be stable, and sometimes when we're developing new features we introduce instability, so we like to do that outside master. The point of branches is that we should do development in branches other than master, and once a development or feature branch reaches stability, we merge it into master and then delete it as a separate branch. As a result, master is never unstable. Well, at least that’s the goal …

In this course most projects do all of their work in master. Because our code base tends to be relatively small and simple (by professional software development standards), the risk of instability is fairly small, and the cost of recovering from instability fairly light. Additionally, Git is sufficiently alienating for new users that as long as you don’t have to learn about explicit branching right away, it might be easiest not too.

The long view (nobody in our course has to know this!) is that branches are part of what is sometimes called *the Git workflow*, which is a systematic approach to using branches for development. You can read about one version of it at <https://nvie.com/posts/a-successful-git-branching-model/>. 

For what it’s worth, in my simplest one-person repos I usually do all of my work in master, and that’s what most project teams in our course do, as well. In larger projects or when I’m collaborating with others, I usually do development outside the master branch.

**Comment by engeljonathan98** [comment]
1) My first encounter with Git was actually years ago, in the context of Computer Science. It was, and is, very confusing! This class has been very helpful in grasping what each of its granular actions do. Though I've always understood Git in theory, I've been confused in the past about its commands. What differentiates a "push" from a "commit"? How do you create a local repo? What is the order of commands? Providing frequent practical usage of Git has helped clear up the order of actions and therefore what each action does. I feel like I can competently use it for the first time: which, ask around my friends and teachers, is a big change.

2) Branching!! I know you said we won't use it much in this class, but I still don't really understand the purpose of this feature. Why would we create a new branch? Is it functional or for different users? What makes a branch different from a local repo? How do we handle committing to different branches? Again, while maybe not relevant to us, it's a big barrier for me personally in understanding the technology and how to use it in my own work. (I notice you wrote up a bit about them above this and I'll read it later, but again, this has been my struggle for years now.)

3) GitHub's Kanban board is great! James and I are already using the "to-do" feature to assign work. In my experience, the great difficulty with organizing large projects is (1) making sure people know what to do and (2) providing them motivation to do it in a timely manner. The Kanban is a great way to organize thoughts into achievable goals that we can understand and work towards. Especially since James and I are mainly going to be working on two different ends of the project -- James on the text and me on the GIS -- this is also a really useful tool for us to keep track of what is going on with the _other_ and communicate to each other our needs and problems. To that end, I'd like to explore what other tabs we could add to board: how much more granular could we make our process? What oversights could we introduce to keep track of each other? How can we use this feature to make our process speedier and more communicative?

**Comment by brenda275** [comment]
My first reaction to GitHub and command line was a state of total confusion. I was faced with terminology I never heard of before to try to understand a seemingly complex software. As I read about its purpose I agreed that it seemed to be helpful for collaborative work but at that point I did not actually have a chance to try it out. As I am slowly starting to engage more and more with GitHub and command line I am realizing its purpose. One thing I am still not too sure about is the process of uploading files from my local computer onto GitHub. Once that happens I hope to be able to manage my files into categories so I can easily find specific files, such as the main grouping of the corpus of my project.

**Comment by khuber116** [comment]
In all honesty, I still am not at all confident with using the command line or Git. I feel as though I haven't used it quite enough at this point in time to fully grasp it. However, I think that in time I will have no issues and I know that if I am ever confused about something there are multiple resources I can go to in order to fix my issues. 

When it comes to GitHub I feel much differently. Other than the major issues I had with getting my account set up the website has been easy to use. The ways in which repos and issues work could be a little more obvious from the beginning but they are definitely easy to pick up on and I think that they make the site an effective way of communicating about a single topic/project. For this reason, I am looking forward to seeing exactly how my group implements these features as we move forward. This format seems to be a great way to communicate with the people you are collaborating with, more so than other sites/services I have used in the past that are meant to serve the same purpose.

**Comment by loreese** [comment]
Initially, the command was so incredibly alienating I never thought I’d understand it. While I’m not 100% comfortable with it yet, and it’s still somewhat alienating, the more I utilize the thing the clearer the purpose becomes. There is a struggle until suddenly there isn’t (though I find a new struggle, don’t worry!) I still am not exactly sure what I’m supposed to be doing with Git and I’d like to get a better grasp on that. I think that not having needed to use it yet, it just feels abstract still. I’ve (unsurprisingly) found that once I utilize technology in context, I pick up on it and its potential quite quickly. Getting over that learning curve is the challenge.

I find Github fairly intuitive. While I haven’t begun utilizing it for project organization the way I’d like to yet, I don’t feel off-put by it. I’d like to start setting up project organization and tags in our project repo to visualize our work and keep on top of things. I think as things move along in terms of our project workload, it will feel more natural to interact with Github more naturally and necessarily

**Comment by AncientGreekGeek** [comment]
I initially found the command line and GitHub totally confusing and really hard to use. Since then I have become more comfortable in just the space of GitHub, e.g. how to post issues, create a repo, etc. And I have found it really useful in terms of our project as it is a space that we can post all of our updates so that we can look back at them later. I still am not quite confident in how to use the command line in order to create a repo or do anything with Git but I hope I will grasp this soon enough as we use Git more. I really want to learn more about how to use GitHub to better organize items in our project as that seems like a very valuable task that you can do in such a platform as this especially when dealing with a large corpus of texts.

**Comment by Nerdologist** [comment]
My first encounter with the command line in this class was not my first encounter with command lines, so it was not all that confusing or difficult. But since then I have gained a better understanding of the variety of commands we can use within the command line and what they are useful for. The primary obstacle to my understanding of the command line's use is that I am unsure how it will be helpful for our project.

On GitHub, the ability to create as many issues as desired and then converse within those issues enables us to post regular updates for the rest of the group and our other classmates and discuss where to go from there. I plan to regularly post links to the Midrashim I want to analyze and comment under the initial posts with my thoughts on how to mark up those specific texts and incorporate them into the project. I would like to know more about the utility of the "Insights" section of our repo.

**Comment by djbpitt** [comment]
@Nerdologist GitHub Insights is not well documented, but the idea is that the repo owner and other developers can examine summaries and graphic visualizations of different aspects of project development, and if any of the views don't make sense after you’ve poked at them a bit, please ask here and we’ll be happy to tell you more. I find Insights more of a curiosity than anything else.

**Comment by djbpitt** [comment]
@AncientGreekGeek Where you write:

>I still am not quite confident in how to use the command line in order to create a repo

the short answer is that we usually don’t create a repo from the command line. A more common strategy, because it’s easier, is:

1. Create a repo on GitHub first.
1. Clone the repo on your local machine.

The clone is the local repo for that project, and the act of cloning makes sure that it is properly associated with *origin*, which is the conventional label for its counterpart on GitHub.

It is possible to turn any directory on your local machine into a Git repo from the command line by typing `git init` inside the main directory for your project files (this may be the only directory for that project, but sometimes it contains subdirectories). The reason we don’t recommend this method is that then you have to associate it yourself with GitHub, and that’s a more complicated procedure than if you created the repo first on GitHub and then cloned it.

**Comment by djbpitt** [comment]
@loreese 

> I’d like to start setting up project organization and tags in our project repo to visualize our work and keep on top of things

This is a great idea! Please do follow up, whether on your own (you may be able to figure it out by poking at it) or in your project meeting (where you project mentor can help guide the process). We use Issues (including custom Issue labels) very heavily even in one-person projects, and they are all the more valuable with a development team. The same is true of Project boards.

**Comment by djbpitt** [comment]
@brenda275 Where you write:

> One thing I am still not too sure about is the process of uploading files from my local computer onto GitHub. Once that happens I hope to be able to manage my files into categories so I can easily find specific files, such as the main grouping of the corpus of my project.

You’ll practice this in your project meeting, and you’ll become adept at it quickly, but the way you upload new or changed content from your local repo to GitHub is described pretty succinctly at <http://rogerdudler.github.io/git-guide/>. Skip the beginning and read the slides labeled “Workflow”, “Add &amp; commit”, and “Pushing changes”.

**Comment by ddaud02** [comment]
My first encounter with GitHub was a little confusing, I had not understood the difference and I was almost two classes thinking that they were the same. Which is not true. I have worked a bit with both of them and I feel a lot more comfortable with GitHub, which has a much more logical or modern nature and I feel much more familiar with this type of interface. The same thing happened to me with Fetch at the beginning, but it's just a matter of practice and of making a mistake a thousand times until I see what is not right.

**Comment by djbpitt** [comment]
@ddaud02 Those thousands of mistakes are familiar to the rest of us, too! It’s similar to the way practice pays off when we’re learning to play a musical instrument. The good news is that you’ll become familiar fairly quickly with the commands you’ll use a lot.
