### ISSUE TITLE
Problem with installing Fetch

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#248]
I have been unable to download Fetch onto my computer because Outlook isn't receiving the email with the license information. I've reapplied and checked my junk folder. What else should I try?

**Comment by zme1** [comment]
I had similar problems when I tried installing Fetch. The emails may be getting quarantined by your spam filter. You can manually add "edulicense@fetchsoftworks.com" as a safe sender in your Outlook settings. There are some instructions [here](https://www.technology.pitt.edu/help-desk/how-to-documents/email-safe-or-blocked-senders) on how exactly to do that. If this doesn't help, let us know!

**Comment by djbpitt** [comment]
@sjw82 In addition to the spam folder in your Outlook client, Pitt runs a higher-level spam filter that is accessible only through my.pitt.edu. When you log into that, toward the bottom of the right sidebar there will be a link that says something like "virus and spam filtering". Clicking on that will take you into an Office 365 interface that provides access to that other spam filter. Several of our classmates had trouble setting up their GitHub accounts because the GitHub confirmation emails got trapped in that spam filter, and the same may be happening with your Fetch message. If you can’t get Fetch working by class and therefore can’t upload your HTML and CSS files, please email them to David, and ask one of the instructors before or after class to help you resolve the problem.
