### ISSUE TITLE
News from the DH trenches

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#25]
# Plagiarism Software Unveils a New Source for 11 of Shakespeare’s Plays

“For years scholars have debated what inspired William Shakespeare’s writings. Now, with the help of software typically used by professors to nab cheating students, two writers have discovered an unpublished manuscript they believe the Bard of Avon consulted to write ‘King Lear’, ‘Macbeth’, ‘Richard III’, ‘Henry V’ and seven other plays.”

Read more at: <https://www.nytimes.com/2018/02/07/books/plagiarism-software-unveils-a-new-source-for-11-of-shakespeares-plays.html>

**Comment by JosephDRogers23** [comment]
I've always thought that it was strange that Shakespeare contributed so many words to the English language - although there were theories that Shakespeare actually represented multiple people or an educated member of Queen Elizabeth's court, even with these factors in mind, he represented a highly educated and creative man. 

A similar question that my Gender & Sexuality in Black Popular Music has been exploring is arguing whether someone who (directly or indirectly) copies someone's work and becomes more famous for the resulting work is responsible for that success, or if the credit should go to the original creator. For example, Robin Thicke's "Blurred Lines" heavily copies Marvin Gaye's "Gotta Give It Up" and Thicke lost a lawsuit alleging that he copied the beat directly. We discussed if this means that Thicke's fame from this song is actually the work of Marvin Gaye instead of himself.

This raises the question: if Shakespeare copied or was heavily influenced by someone else's work, who deserves the credit for influencing and shaping the English language and literary works across the centuries?
