### ISSUE TITLE
Final Project Question: Relax NG

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#251]
Would it be most efficient to write one structural schema and as different group members do their xml have them add to it on their local machine then merge it in github afterwards and reevaluate the validity in the various documents; or to create one at the beginning that everyone updates on their local machine as soon as edits are made; or to each create schema individually which we unify later on?

**Comment by djbpitt** [comment]
@sjw82 I would recommend something like the following as a way to get started:

1. Think about the organization of the subdirectories of your repo, so that you don’t just dump all of your files into the top-level directory. You’ll probably want to review this with your project mentor in a meeting. At this stage you might want to start out with separate subdirectories for your plain-text source files, the XML you’ll be creating from those source files, and your schema, plus something for miscellaneous plain-text development notes to yourselves (see immediately below).
1. Document analysis. That can be all team members together (best done in person), or one team member can be responsible. If it were me, I would keep a record of the results of document analysis in plain language, in the miscellaneous subdirectory I mention above, since those results will guide the decisions as you create the schema. Push the write-up to GitHub, so that all team members will have access to it.
1. Create the schema. This can be done by one person on the basis of the plain-text write-up of the outcome of document analysis, or by the team if you want to discuss the formal modeling as you write the Relax NG rules. It’s probably easiest, though, if one person does the typing, so that you can keep track of the development (what parts should work as written, which parts will be invalid until other parts are added, etc.). Push it to GitHub when it’s ready for testing. If, in the course of formalizing the results of the document analysis as a Relax NG schema you realize that you need to modify the document analysis, update the plain-text notes immediately, so that they will be in sync with the schema.
1. All team members who are tagging should pull, so that they’ll have local copies of the schema, and then test it out by using it to create or tag content. If you’ve implemented the filesystem hierarchy I suggest above, the schema and the XML you are creating will be in different directories. You’ll make life easier for the team if everyone creates their XML at the same location in the filesystem hierarchy within the repo, since that way your schema association lines will all be the same. It’s common when we first road-test a schema to notice mistakes in our document analysis, and therefore in our schema design. I would suggest scheduling a brief period of quick and intensive testing (not necessary a lot of documents, unless they are very different, but try to field-test all of the schema features) and revision (revising the plain-text document-analysis write-up, as well). I would also recommend having only person edit the schema at this stage, since schema statements are heavily dependent on other schema statements (e.g., a label in a content model requires that the label be defined elsewhere), and inconsistencies are easiest to avoid if one person takes responsibility for making changes in the actual schema file. 

When you change the schema during this last step it is likely that you’ll have to change your XML documents to match. For that reason, at this stage the point of tagging the XML isn’t to create tagged XML, but to verify that the schema is adequate for the markup you need. In other words, small test documents with dense markup are probably the most useful at this point.

Once the team is reasonably confident that the schema matches the markup needs, you can move on to creating real content by tagging real documents. You may still discover schema errors that need to be fixed, and those fixes may still require going back and revising existing documents, but the goal is to stabilize the schema as much as possible before going full speed ahead on tagging real documents.
