### ISSUE TITLE
Single-Issue Class Discussion Post

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#257]
**Single-Issue Class Discussion Post**: 
Since your first encounter with the command line and GitHub, how has your understanding of these technologies changed? 
**1. What obstacles still affect your understanding of its use?** 
       One of the things that I still do not have very clear is to use #terminal. I have problems when writing the codes because sometimes I need a space or a symbol, and writing them in the correct order can be confusing.
**2. On GitHub specifically, which features stand out as useful tools for your project team?**
       One of the things that helps me a lot is the organization that has and the possibility of creating instructions so that we can all be at the same pace.
**3. How would you plan to implement them?** 
       In the "issues" section we will record all the comments or at least a summary of the steps to follow in the project. One of the most useful things is the possibility of interacting with the members of the project, commenting and making changes.
**4. Which features do you want to learn more about?**
       In the "issues" section we will record all the comments or at least a summary of the steps to follow in the project. One of the most useful things is the possibility of interacting with the members of the project, commenting and making changes.

**Comment by djbpitt** [comment]
@ddaud02 This is just a GitHub/Markdown pointer, which is likely to be useful for everyone: Because you indented your paragraphs, they are being rendered as if they were code blocks, and code blocks don’t wrap long lines. That is, indentation is one way that Markdown identifies a code block. As a result, when we look at your answer in GitHub Issues, above, we see single long lines that we have to scroll horizontally, which makes them hard to read. If you don’t have that indentation at the beginning, though, they will wrap to fit the frame, like regular paragraphs.

You can fix this by clicking on the three dots in the upper right corner of the frame, choosing “Edit”, removing the indentation, and then clicking “Update comment”. Please let us know if you run into any trouble with this, and we’ll look forward to reading your posting once the formatting has been adjusted!

**Comment by ddaud02** [comment]
Thanks, I just fix it.
