### ISSUE TITLE
Single-Issue discussion: Orbis

### ISSUE THREAD

**Issue by zme1** [obdurodon/dh_course#258]
Explore [Orbis](
http://orbis.stanford.edu/), designed to explore the economic geography of the ancient Roman world, with attention to more than distance. Contribute to the GitHub Issue in response to both research and design aspects of the site and to the responses of other students.

**Comment by Ethandaniel47** [comment]
When I first opened the Orbis page I was thrown off by the pop-up window that acted as a sort of secondary-home screen. Because the box was so large, I took it to be the entire interface and did not immediately locate the ability to close out of the window to access the actual site. In this first pop-up the  researchers have included a link to a You-Tube video tutorial on how to use their technology, implying that the experience of the map is not immediately intuitive to new users, which might be seen as a design flaw. For me, this was true in that I expected the map to calculate new routes in real time when the user selects clickable features, however, the rules of hierarchy made it so that the "Calculate Routes" button at the bottom of the screen was not recognizable at first as necessary to loading these new restrictions on the map. Generally speaking the images and features of the site were clean and evenly spaced, however, the page was busy and cramped with too many different pieces trying to draw attention.

**Comment by MLuckman** [comment]
I agree that the pop-up as a sort of home screen isn't intuitive. There's also a lot of information there, about the design, methodology, etc, that seems a little out-of-place to be stuck in an "about" pop-up that isn't necessary easy to navigate back to.

The transfer cost is poorly explained in the tutorial - why am I deciding what the cost is, why isn't it programmed in alongside the several different modes?

That being said, it's a really interesting tool. The ancient world is chalk-full of terrible numbers, whether it's the massively implausible armies or tales of wealth, and while I haven't run across any preposterous travel times, I don't imagine that they'd be any more accurate. This is a good tool for fact-checking some of that, in my view, in addition to the more socio-economic uses of seeing travel routes that the authors envisioned.

**Comment by sjw82** [comment]
Similarly, the first pop-up confused me and since it is a pop-up I just exited out so I couldn't tell you what it was trying to say. I just stabbed around for a while and have decided this website is so *cool* for something so hard to understand. Some of the features have descriptors that appear if you hover over them which I really value because defining a term or tool is a top priority for me and the left hand criteria box is communicative but the banner on the bottom left me with more questions than I'd had coming onto the site, especially since the text cuts off and the tabs don't have descriptors.
The clickable map is the best feature on this site in my opinion. Giving the users options within the graphic; the ability to hide or show the information they wanted; and color-coding are strong design choices that I will think about carrying into my project.

**Comment by gabikeane** [comment]
Hi all!
The pop-up is always a drawback. We're going to talk a little bit more about this on Wednesday, and we'll view some more examples of Stanford's Spatial History project in action.

For now, though, I want to direct some more of the discussion to the research premise here too! 
@Ethandaniel47 : did you watch the YouTube video? Was it helpful? If not, why not, and how does a developer (who knows their tool is difficult) get you to watch it?

@MLuckman : what do you mean by, "I don't imagine that they'd be any more accurate?" The times here are kind of like best guesses. We'll be looking at some other projects that make assumptions and guesses (even though they're historical projects). How transparent should the developers be about those assumptions.

@sjw82 : I'm glad you like it so much! When you didn't understand, what did you do then? Was the process of discovery the cool part, or was the working map cooler?

**Comment by ddaud02** [comment]
Very interesting project because it not only helps people to visualize data but also you can see them in "practice". Sometimes you see a graphical bar with information with difficult parameters to understand for those who do not have knowledge in statistics for example. It would be very interesting if the maps had a high satellite detail like google maps have, for example.
@Ethandaniel47 I always prefer the idea of show introductory videos instead of reading (or figuring out by myself) about something that I have never seen or heard in the first time.
@MLuckman and @Ethandaniel47 You guys talk about a youtube video but I can not find it, where is it? it is something that pops in?

**Comment by Guifindor** [comment]
<h2>Browser Used: Firefox</h2>
<p><i>(only mentioned this because of the compatibility pop-up)</i></p>
  
<p>Pop-up by default aside, the site is a rather interesting tool to use. To answer the first question, it seems that the site was designed to support research questions pertaining to travel. I can only imagine two main uses, comparing travel times of today versus back then, and verifying movements of Romans in both fictional and non-fictional works. Otherwise, I cannot imagine another research usage that doesn't fall under those two categories in some way. For these categories, the site answers them quite well. The filters of different travel types, being able to select which sites to include or not include when looking up routes all work really well and could easily serve that purpose.</p>

<p>From a design perspective, the site feels and looks cool! Instead of having to type out every city, they give you a drop down menu of choices for destinations/starting points. To me, this is convenient for both Developers and consumer, as neither no longer has to deal with case, misspellings, and other string input problems. The filters feel like they actually impact the results, and are as simple as checking them off (no "show filters" or "advanced search" or nonsense like that, just everything upfront). The "About" popup is actually really interesting once I got over it being open by default. It allows the user to browse info about the site without navigating away from the page, which I find to be a nice touch. The tutorial is very direct and points straight at which element of the page is talking about, and gives the option to stop at any point rather than being forced to click through all of the steps.</p>

<p>There is one design decision that is mildly infuriating though. There is a feature where if you click on a location site or most routes that it brings up a quick menu to search for road networks or directions between cities from that spot. This is nice and all, however, it seems to inhibit my ability to drag the map if my mouse is hovering on a location where this is applicable. For most of the map this is not a problem, but then there are sizable portions of the map that are locked into this quick menu selection and it's frustrating to suddenly run into that when moving the map.</p>

**Comment by rmf96** [comment]
I actually enjoyed the pop up. However, I think that the only thing keeping me from automatically exiting out of it was the fact that I read through the previously existing student comments about the pop up before entering the site. Because I had a preexisting understanding of the pop up before entering the site, it was a lot easier to navigate through it upon initial entrance. Taking the time to peruse and use the pop up was actually very helpful, allowing the user to get an initial overview of the sight's goals, news, etc.. in addition to a user tutorial. The youtube video showing how to actually use the sight was a very good idea because the content on the site is great, however it is pretty difficult to navigate if you are not primed with information on how to do so.

**Comment by spkellyo** [comment]
They clearly spent a lot of time on designing a professional looking site, but as far as user experience it left a little to be desired. I wonder if navigation tabs are going out of style, because I have noticed it with other sites we have looked at as well as with this one. The only way to get from the map to home was to click About, which is not intuitive. I was about to click the back button, which good sites should never make you do if they want to keep your eyes on their page, when I saw About and decided to see what happened. The fact that you need a tutorial to use the site for its intended purpose means that they may have made it more confusing than it needed to be. When I was just playing around with the map a lot of things popped up, but when I clicked in the little red boxes I got an error or it didn't do anything. Using different colors might have signaled to me that one box will tell me something new and another will not. This is a specialized site that is meant for people with certain prior knowledge or who have time to watch the video and tutorial. If I was reading a book and wanted to know what the travel from one location in my story to another, on the surface this site would seem like a good place for me to get that info and increase my reading experience. But, it is not meant for casual users. I think it is a great site, but they need to work on some of the Java and possibly rethink the number of things you can do on one screen. They could allow you to store information in a "cart" so you could look at different aspects of trips or locations without losing the data you just found. That would allow for comparison while making it easier to use.

**Comment by engeljonathan98** [comment]
I'm gonna talk about this as a research project because this is the coolest thing I've seen today.

I _really_ like the methodology described in the "Understanding" tab. Attempting to describe the Roman Empire as a complete political unit is really difficult, speaking from a historical perspective focused on territory or political rulership. What is essentially the "Roman Empire" is one of the most hotly debated subjects in European history (and one a lot of poor people have died on swords for): what territories describe what you need to _be_ Rome? Who needs to be _in charge_ for the state they run to rightfully call itself "Rome"? These are unhelpful questions producing a lot of conflicting answers. Taking instead the POV that the Roman Empire was a trade and information _system_, a _network_ of interactions between places under a certain set of routes and standards is a really cool solution to the problem. Here, the Roman Empire is a not thing people were, but a thing that people _did_, which solves most of our prickly problems of continuity and such.

I think taking the approach of normalizing and averaging data from across the Empire's history to produce costs and routes is, while a necessarily abstract and data-lossful approach to describing the entity, a really promising path to understanding that system. We can use these abstractions to simulate _doing_ Rome ourselves. We can ask: if I'm in Constantinople and I need to communicate with Rome, how long would that take and how expensive would it be? The numbers might not be exact, but by relating them to other costs, we can get a sense of what this journey would be _like_ for those undertaking and underwriting it.

This is a really useful tool for evaluating this period of history! It's hard to imagine what life and politics were like then. Classicists, I imagine, could use this to ask more interesting and more engaging questions about that period with this tool. We can use this to build, if not definitive evidence, but bases for arguments about _why_ people did as they did on this network.

In synopsis, this is a really cool conceptual framework and a great research tool. I love it as an unorthodox and illuminating approach and, like all great technologies, it has fun buttons.

**Comment by khuber116** [comment]
While I'm sure this website is useful for those who are interested in the topic enough to sit down and really figure it out, I do not think that it is intuitive at all. The best feature (as previously mentioned) is the ability to click on elements within the map itself. However, there are many drawbacks. I don't think the pop-up was a poor choice, but if you need to provide so much information in order for a user to even begin navigating the site then there are probably some issues with the site. Thinking back to the guest lecturer from last week, the site should be easy to follow from a first glance, but this page is just too busy to allow for that. Additionally, the actual information such as cost, time, etc. about the chosen route ends up in a cramped box at the bottom of the page. I'm sure it's a wonderful tool for learning about this time period, but from a design/usability perspective there is definitely some simplifying and cleaning up to be done.

**Comment by k-busko** [comment]
I find that the initial pop-up page is very misleading to users, almost as though they would feel they were not at the correct homepage when in fact they are. Also I find that it would be more conducive to have a more identifiable icon such as 'Home' instead of 'About' if a user needed to get back to that initial homepage. Going back to the guest lecture about web design, even just making that icon a stand-out color like bright yellow would lead people to click on it in hopes of finding the homepage. I think one of my favorite aspects about this site is the interactive map. The map is customizable which can prove to be extremley helpful for researches looking for particular features (for example, someone just looking for road networks and no other features like waterways). The tutorial feature is also nice in that it gives clear instructions for how to follow along but also gives users the option to skip through if they do not feel like they need it after starting it. I have used websites in the past where you are forced to complete the entire tutorial with no option of exiting it prematurely so I think this was a beneficial addition for users.

**Comment by loreese** [comment]
While there were some really cool features this site provided once you got into it, I agree with what many others have noted on its lack of intuitive usability. The site felt like more trouble than it was worth to use. I was a bit disoriented with the pop-up screen right off the bat. The myriad tabs on that initial screen were somewhat overwhelming upon the first contact, and the fact that you could see the "main" page behind the screen before having made a single selection was off-putting. Flipping through the tabs, there was a lot of information being thrown at you, and it strikes you as just the warm-up with the main page looming in the background. One of the feelings I kept experiencing with this site echoes the UX lecture from last week, and that was the feeling that I was doing something *wrong* because I didn't quite know where I was or where I was going as I was trying to navigate. That lack of intuitive flow made using the site a learning process in itself, which made all the actual learning provided less engaging. 
The fact that there is a tutorial provided was helpful, but again, the site itself is a learning process.

**Comment by brenda275** [comment]
At first, I didn't even notice the pop-up screen. The pop-up page seems to work like any other homepage. The main purpose of this site is their interactive route map. Navigating that map alone is a bit tricky, so its possible the creators' intent for the pop-up page is to allow an easier way to provide any heavy information on the site, as well as a tutorial on how to navigate their interactive route map. The interactive map has many features but that makes it overwhelming to look at. Navigating the site itself takes quite the amount of effort. Normally I would have clicked away from this site because it is not easy to follow. There's no doubt that Orbis is a professional site, but its focus is not on the site being user-friendly.

**Comment by AncientGreekGeek** [comment]
I also didn't notice that the pop-up screen was a pop-up at first. However, I did find the pop-up page really useful as an introduction to the purpose and background behind the site. I like how they put it in a pop-up page so that they do not have to clutter the main page with all this information that is necessary but not the focus of the webpage. Overall, I think the webpage is super cool. It did take a bit of time to figure out what is going on, since there is just so much on the page. However, it became easier the more time I spend looking at the page. The calculate route feature is I think the coolest part. To be able to manipulate all of the features and create a version of the map that is really specific is really cool for the user and I can see how this could be really useful for a researcher. I also found the clickable cities on the map a very interesting feature. This provides another way to calculate the route that could show the user a different set of data. While it seems kind of intuitive I really like that there is an option to reset the map. This is something super small but if they didn't have this feature this map would have been super burdensome to use. In parallel with this the history function was a super interesting addition as this allows the user to look upon their previous work without losing it completely when they reset the map. Overall, I do agree that the page is a bit hard to use at first. However, I think it is designed really well for its audience, researchers and students of history and classics. As a classics major I really would love to use this if I needed to in further research.

**Comment by emmamamula** [comment]
I was initially confused by the pop-up as well, but I kinda think it is a cool element. It features everything that would appear to be on the main page of a site. It probably is not an efficient way to present information, since as other students have noted it is a pop-up and our first reaction is to exit out of it. I also though that using the interactive map as a bit tricky, but I like how they also included normal images of maps in the gallery, unfortunately, it was again on the pop-up of the website.I agree that the tutorial is helpful, but the fact that there is a need to include a how-to video shows the difficulty of the site. 

In terms of design, the site is cohesive and has a pretty neutral color scheme, with red being the color that pops (but is not distracting). The theme even carries over into the map and routes included, which enables an overall smooth transition, visually, from the pop-up to the map. Probably my favorite part of the site is the icons they used to represent the seasons, the simplistic outlines are overall pretty cool. The map is obvious the bulk of their site and an impressive design feature, but perhaps the link to the tutorial should be available after the pop-up in case the user needs to reference it again. Overall a really cool looking site that is complex in use, but the aesthetic of the site is quite simple.

**Comment by pickettj** [comment]
This is a pretty incredible site; it's hard to even wrap one's mind around the effort that went into it. (This level of detail would not even be possible for other periods / places in history, no matter how much effort scholars put into it.)

The design of this site is both intuitive, and has depth to it; i.e. casual users can quickly mess around with features, but investment in the full range of capabilities pays off. That is a difficult balance to strike.

These kinds of geospatial networks are reshaping our understanding of what concepts like "the Roman state" even meant. When you see those shaded maps with nice, clear borders, what do those lines actually mean? Projects like Orbis provide a different way of thinking about the question.

**Comment by Nerdologist** [comment]
I was not bothered by the pop-up window, but it would have been helpful if the site creators made it clearer that, once you close the window, you click "About" to open it again. To be fair, it is somewhat intuitive that the pop-up is the "About" section of the site, at least if you paid attention to the content of the pop-up when it first appeared. But the user might waste time looking through all the other links in the navigational apparatus surrounding the map, trying to find the one that sounds most like it leads to the pop-up, before clicking on "About." It would take less thought to figure out how to bring the pop-up back if it had an "About" heading, if the "About" option in the navigation bar were highlighted while the pop-up is open and not while it is closed, or if the "About" option in the navigation bar were visibly connected to the pop-up while open.

The "Research" part of the "About" section is very useful to researchers who are looking to save money since it contains a collection of open-access (free!) academic publications. The "Media" feature is also nice in that it provides users with links that explicate the significance and utility of ORBIS; users may initially find themselves unimpressed by the site or unsure of how to use it, but the "Media" feature can change this, if the users manage to locate the feature. Of course, the "Tutorial" option in the main navigation bar above the map also explains how to operate the site, but it does not seem to explain the useful ways in which those operations can be implemented. Why bother to calculate a route on the Roman map? The "Media" feature introduces us to the news-worthy applications of ORBIS, and thereby shows why calculating routes matters.
