### ISSUE TITLE
XPath Number 1

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#264]
What kind of medium/file should we use when uploading the answers? Microsoft Word? I wrote all my answers in a Microsoft Word document already.

**Comment by djbpitt** [comment]
Thank you for asking! The answer is that nobody should ever write code in Microsoft Word. The reason is that by default Word will use *smart quotes* (converting straight apostrophes and quotation marks into curly ones), *smart hyphens* (changing a sequence of two hyphens into a dash), *smart capitalization* (capitalizing your variable `i` because it thinks it’s the first person pronoun), etc. Even if you turn those “features” off in your copy of Word, we haven’t, so we can’t open and write into your document safely.

Please submit all descriptive code assignments (the ones where you have to describe what you did, as with the regex assignments, and now the XPath ones) in Markdown, using code delimiters for code snippets and code blocks, and checking that the formatted view of your document looks correct. You can remind yourself of the code delimiters at <https://guides.github.com/features/mastering-markdown/>; scroll down to “Examples” and click on “Code”. If you run into any Markdown problems or questions, please ask here!

**Comment by ddaud02** [comment]
I did re-write the answers already, I still upload the word.doc next to the markdown just in case. Thanks.
