### ISSUE TITLE
XPath #2

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#266]
I tried looking everywhere online and wasn't able to answer my question.. but what is a metrical line? I understand what to look for when using XPath to find it but I just genuinely don't know what it means. Anyone?

**Comment by emmamamula** [comment]
I also did not know what a metrical line in poetry was had to research. From what I found (and I think I understand), metrical lines have varied numbers of syllables but a defined number of stressed syllables (Wikipedia). I think it also means that it is a line based more so on rhythm and stress than rhyme.




Here is the link:
 [https://en.wikipedia.org/wiki/Metre_(poetry)](url)

**Comment by djbpitt** [comment]
Shakespearean plays are said to be in iambic pentameter, which means that each line has ten syllables (sometimes eleven) and there is a strong tendency for stress to fall on even-numbered syllables. For example (from _Hamlet_, with syllable division added and stressed syllables embolded):

>Good **Ham**-let, **cast** thy **night**-ed **co**-lour **off**,  
And **let** thine **eye** look **like** a **friend** on **Den**-mark.  

The preceding are _metrical_ lines because they have a regular metrical structure, that is, a regular syllable count and a regular distribution of stressed and unstressed syllables. But some lines don't conform to this pattern, and those are considered non-metrical, e.g.:

>“O dear Ophelia, I am ill at these numbers; I  
have not art to reckon my groans: but that I love  
thee best, O most best, believe it. Adieu. “Thine  
evermore, most dear lady, whilst this machine is to  
him, HAMLET.
