### ISSUE TITLE
Problems with GitBash

### ISSUE THREAD

**Issue by enb34** [obdurodon/dh_course#27]
I was attempting to commit a file to my project repo. I was able to add the file without any difficulty, but when committing the file, I believe I made a typo of some kind and a vim editor was opened. I couldn't figure out how to fix the problem within the vim editor, so I exited it to retry or reset the commit, and since then I haven't been able to do anything in GitBash except move between files. I consistently get the same error message whenever attempting to use GitBash for any reason.
![gitbash-error](https://user-images.githubusercontent.com/35206825/36065061-587aaef0-0e63-11e8-9033-9e2f7878c9b7.png)

If anyone has advice on how to fix this, that would be greatly appreciated. Not being about to commit any of my files to my repo has been a bit of a setback.

**Comment by ebeshero** [comment]
@enb34 I bet you're in a state of "conflict" in which you need to pull in changes from the remote repository before you can push a new commit. The vim editor takes a little "trick of the fingers" because you can't use your mouse to navigate it. When it opens, it's inviting you to commit a special kind of change--a "merge" of changes from the remote repository with the changes you've made locally.

To deal with vim, you usually need to add a commit message--this time without quotation marks--in a blank line near the top. To do that so you can type in that space, you need to position your cursor where you want to type (using an up arrow if necessary), and type the letter i on your keyboard, and you can type. Add a message like "resolving merge" or "coping with merge issue" or some such. When you're finished, you need to get out of vim, and you can do that with the following keyboard combination: `esc`:wq  (which means, "escape: write quit") That will "write" your commit message, and send you back to the command line. You should then do a `git status` and see where you are...

To verify you're in a state of conflict, simply try to do a `git pull`--I bet that sends you straight into vim.

**Comment by djbpitt** [comment]
@enb34 If I’m reading the message in your screen shot correctly (and thank you for including that; it makes responding a lot easier!), git thinks you have one of two problems:

1. Either you have a commit or other process running, which is blocking you from doing something else; or
1. You *had* another process running, it got interrupted, and the repo is still hung up (locked) by that defunct earlier process.

I don’t know how to check for running processes on Windows, but one of the Windows users in this forum might be able to step in and advise. You could also take the quick and dirty approach and just shut down and reboot, which will kill all running processes. My guess, though, is that you have the second of the two situations listed above: when you closed the window in which you were running vim without exiting vim cleanly (for future reference, see Elisa's explanation above of how to operate within vim), the lock on the repo wasn't removed. The git error message prompts you about what you can do here: you can remove the index.lock file, and that should unfreeze the repo. To do that, from the main directory in your repo, type:

```bash
rm .git/index.lock
```
The `rm` command means ‘remove’ (that is, ‘delete’), and the file you’re removing is the `index.lock` file inside the `.git` subdirectory of your main repo directory. Notice that the directory name begins with a dot, which you need to include in the path.

Please let us know whether this helps. If not, if you can bring your laptop to class Friday, we’ll help you sort it out there. We recommend not doing <https://xkcd.com/1597/>, although the fact that there’s a cartoon about it tells you that you’re in good company as a new user who is learning her way around git.

**Comment by ebeshero** [comment]
@djbpitt @enb34 I'd be worried that the lock file is there *for good reason* because a process didn't finish in the vim editor before. Those processes are generally a good idea to complete, because they're typically trying to reconcile states of your repo. I'd recommend simply reopening your bash shell, trying a `git pull` and see if that opens up the vim editor to complete a commit. If it does, follow it through. 

If you're not sure that's the best thing to do, go and take a look at the web version of your repo and compare the files in it and their latest completion with those you have locally. Has anyone else committed changes to files (or new files) that you don't have? If so, you need to be able to pull those in without losing your changes--and the vim editor work is going to be necessary for that.
