### ISSUE TITLE
Placement of a function in the logic of XPath

### ISSUE THREAD

**Issue by pickettj** [obdurodon/dh_course#270]
One way of counting all the <sp> elements in Bad Hamlet that contain neither <ab> nor <l> as immediate children is:

```
count(//sp[not(l or ab)])
```

The function takes all of the "returned nodes" (correct terminology?) from `//sp[not(l or ab)]` and counts them.

I'm curious about the logic behind placing functions elsewhere. For instance, the following "works" (i.e. does not return an error message), but returns 20351 items:

```
//count(sp[not(l or ab)])
```

What is going on there? That's more than the total number of elements in the entire document (`count(//*)`=6783), so what is it counting?

**Comment by djbpitt** [comment]
The leading `//` is equivalent to the `descendant-or-self::` axis. (We’ve been saying that it’s equivalent to the `descendant::` axis because most of the time the difference doesn’t matter, but since we’re now in the weeds. we’ll be precise.) To see what’s going on, we can simplify the task by getting rid of the bits that aren’t responsible for the result you’re seeing. If we run:

```xpath
/descendant-or-self::node()
```

We start at the document node and retrieve all nodes in the tree. We’ve been concentrating on elements because in Real Life that’s where we do much of our work, but XML documents contain seven types of nodes: document, element, attribute, text, comment, processing instruction, and namespace. Our simplified expression tells us that there are 20351 nodes of all types in this document, and we’re returning all of them.

Because the last part of your `//count(sp[not(l or ab)])` expression that returns nodes is the leading `//` (the rest does something at each node, but it doesn’t select nodes to return), it’s returning every node, of every type, in the entire tree. For each of those nodes, it is then counting how many `<sp>` children they have that meet the specified condition. When you run it, it may look like it’s returning nothing but 0 values, but you can see that there are others by trying:
```xpath
distinct-values(/descendant-or-self::node()/count(sp))
```
which returns a lot of different numbers.

Where the function goes seems confusing until we think about what each function does. For example, why do we sometimes wrap `count()` around a specific lower or inner path step, while at other times we wrap it around the entire expression? The answer is that the function has to be wrapped around its input, that is, around the think on which it is supposed to operate (for `count()`, the thing you want to count). If you want to count the scenes in each act, you have to get to each act with a path expression like `//body/div`, which sets the new *current context* (for the next path step) to each act in turn. So if you extend this to `//body/div/count(div)` it counts the `<div>` children of each act (that is, the scenes in each act) separately. But if you instead write `count(//body/div/div)`, you’re returning all of the scenes in all acts and then counting them all at once.

The fact that each path step starts from the sequence of items returned by the preceding path step means that we have to think about what the value of the XPath expression is at each step. In `//body/div` it’s a sequence of the five acts. in `//body/div/div`, it’s a sequence of all the scenes in all of the acts. With respect to where to put the `count()` function, we need to focus on what it is that we want to count.
