### ISSUE TITLE
Xpath attribute names question

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#275]
I am doing the 4th Xpath homework and I understand that somehow I have to tell Xpath that I am looking for an attribute xml:id that starts with sha-ham and is followed by 6 digits and then a letter and possibly(?) a digit, but I have no idea how to express this. I have been looking everywhere but i don't even know how to ask the question that will return relevant results. I don't know what to do. I can't even start the second question.

**Comment by djbpitt** [comment]
@spkellyo You can take advantage of the fact that you don’t have to match the entire pattern. For example, `@xml:id` values on lines in this document don’t include uppercase “M” except to indicate a middle line. That means that you don’t have to know about the “sha-man” or the digits in order to find line elements that have an `@xml:id` value that you need. You’ll need the `contains()` function, which you can read about at Kay 730–32.

If you were looking to match the entire `@xml:id` pattern (which would be a more robust approach, but also trickier to implement, you could use regular expressions, which requires the XPath `matches()` function (Kay 828–30). In that case, the pieces you would need are all described at <https://www.regular-expressions.info/quickstart.html>. including anchors (for “starts with”), literal characters (for “sha-ham”), and shorthand character classes and repetition (for “6 digits” and "possibly").

**Comment by zme1** [comment]
@spkellyo The XPath expressions for this assignment can be rather daunting to begin, so we provide you with the functions we used in our solution to get you started. On the assignment page, we say that we used the `count()` and `contains()` functions to get our answer. 

So, what *are* we looking for? Well, what we ultimately want is a count of all the lines whose `@xml:id` values contain the character `M`. It would help to first figure out the number of arguments that a function takes. In other words, we need to figure out how many different pieces of information are intended to go inside the parentheses of a specific function.

Referring to [our overview of XPath functions on obdurodon](http://dh.obdurodon.org/functions.xhtml), we can see that `count()` takes just one argument (the sequence that it's tasked to count), while `contains()` takes *two different strings*. When we use this function, we want to know whether the first string we supply contains our second string. In other words, our first string is our context, and our second string is what we're looking for in that context. Here's what that looks like:

`//tagName[contains(string1, string2)]`

Two notes: when we are inserting an element or attribute name inside one of these positions, we don't use quotation marks. When we want to look for an actual string of text, we do. Also, remember the default property of the XPath parser to refer to the child axis, unless you say otherwise.
