### ISSUE TITLE
Gender Analysis of Serbian women's Songs

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#276]
To whom it May Concern, The link that redirects for our project do not work [http://serb-songs.obdurodon.org/](url) or something that I do not know is happening. If anyone knows please tell me what to do. Thank you.
<img width="597" alt="screen shot 2019-02-24 at 9 12 17 pm" src="https://user-images.githubusercontent.com/46380238/53310006-fd650d80-3878-11e9-8851-9e02f8466dae.png">
<img width="1123" alt="screen shot 2019-02-24 at 9 12 37 pm" src="https://user-images.githubusercontent.com/46380238/53310008-ff2ed100-3878-11e9-937b-700a2bee522f.png">

**Comment by djbpitt** [comment]
@ddaud02 Oops! The reason you are seeing the test page instead of your main project page is because you seem to have deleted most of the content of your project site, including the main page. Here’s the output of the `tree` command inside your main project directory on Obdurodon:

```text
.
├── img
│   ├── 1.jpg
│   ├── 2.png
│   ├── 3.jpg
│   ├── 4.jpg
│   ├── 5.jpg
│   ├── 6.jpg
│   ├── 7.jpg
│   └── 8.jpg
└── media
    └── Serbian-folk-song.mp3
```

In other words, your main directory contains an *img* subdirectory with some images and a *media* subdirectory with an *mp3* file, but you don’t have any HTML or CSS files anywhere. If you upload a file called *index.xhtml* to your main directory, though, that should replace the test page the next time you access the site through a browser, and you can upload other HTML pages, CSS, etc. similarly.

**Comment by ddaud02** [comment]
Thanks, @djbpitt, however, it has to be something else because I do see files on my page, 
<img width="956" alt="screen shot 2019-02-24 at 10 51 41 pm" src="https://user-images.githubusercontent.com/46380238/53313372-196fab80-3887-11e9-93b3-9861dd4cefb6.png">
<img width="742" alt="screen shot 2019-02-24 at 10 53 19 pm" src="https://user-images.githubusercontent.com/46380238/53313377-1bd20580-3887-11e9-9418-fe583c6ffcf6.png">

**Comment by djbpitt** [comment]
@ddaud02 This is a common source of confusion. Your screen shots are of GitHub (where your files are correctly in place) and your local (laptop) clone of your GitHub repo (where they are also correctly in place). But your web site lives on a different server, on Obdurodon, so to put your files there you need to upload them explicitly with Fetch. Pushing to GitHub is separate from uploading to Obdurodon because the two sites have different functions. GitHub is for project management and development, while Obdurodon is for publishing your project on the Internet.

Notice, though, that the organizational hierarchy in your Git repo (both your local clone and on GitHub) puts your XHTML files in their own subdirectory. That’s okay in your Git and GitHub development enviroment, but on Obdurodon at least the *index.xhtml* file needs to be in the main project directory, since that’s how it becomes your default main page, and we'd suggest an organization like the one below, which puts all of the XHTML files in the main project directory. I've based this example on Gabi’s *Ghost hoax* project, but I’ve simplified it a bit to remove some advanced details. Note that this is their directory space on Obdurodon, and not on GitHub or their laptop:

```text
.
├── analysis.xhtml
├── background.xhtml
├── conclusion.xhtml
├── css
│   ├── local.css
│   └── VGSplash.css
├── images
│   ├── VGimgbackground1.jpg
│   ├── VGimgbackground2.jpg
│   ├── VGimgbackground3.jpg
│   └── VGimgcc.png
├── index.xhtml
├── JohnCharringtonsWedding_markup2.xhtml
├── methodology.xhtml
├── ShadowintheCorner_markup2.xhtml
├── stories_showhide.js
├── stories_showhide.xhtml
├── vauxhallwalk_markup_2.xhtml
├── wade_oldnurse_markup_3.xhtml
├── wade_walnut_markup_3.xhtml
└── wn_richnesstable.xhtml
```

All the XHTML files are in the main project directory. Her CSS and her image files are in separate subdirectories.

**Comment by ddaud02** [comment]
Thanks again, I just figure out.
