### ISSUE TITLE
Class discussion: text element

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#279]
Someone was talking about a `<text>` element in class yesterday. If I remember, the workaround is as follows and I checked in oxygen for this.

Given xml file 
```

<text>
    <book>
        <page>Word word word</page>
    </book>
</text>

```

The relax NG schema would be

```

start = thing
thing = element text {book}
book = element book {page}
page = element page {text}

```

The relevant bit is that you need to tag the element as something else eg `start=thing` then equate the thing into the element text, as on the second line.

**Comment by djbpitt** [comment]
@MLuckman Thank you for the reminder about working around reserved words in Relax NG! This is exactly the right answer.

You can make your posting easier to read by putting the triple backticks on their own line. For example, where you wrote:

    Given xml file ```<text>
        <book>
            <page>Word word word</page>
        </book>
    </text>```
it all gets rendered as one run-on line (see the original posting, above). To retain the hierarchical layout, change that to:

    ```
    <text>
        <book>
            <page>Word word word</page>
        </book>
    </text>
    ```

which is rendered as:

```
<text>
    <book>
        <page>Word word word</page>
    </book>
</text>
```

Skip a line before the opening triple backticks and after the closing ones, so that interpreter won’t think they run continuously with whatever precedes or follows the code block.

**Comment by engeljonathan98** [comment]
How frequently would one encounter a `<text>` element, because of this problem? I imagine that, if most XML markup in Digital Humanities is done with RNG in mind (and I'm sure it is!), it would therefore be unconventional to call an XML element `<text>` so as to avoid confusion.

Is that the case? And the adjacent question: how much do conventions actually dictate real world, non-TEI usage of XML to markup humanities texts? Are those conventions evolving as the field grows?

**Comment by djbpitt** [comment]
@engeljonathan98 `<text>` elements are staggeringly common because TEI uses `<text>` as a core feature and TEI is very influential in DH circles. The `<TEI>` root element typically has two children: `<teiHeader>` for metadata and `<text>` for text. TEI predates the emergence of Relax NG, but because the workaround Mitchell describes is easy, and because developers author a lot more with XML than Relax NG, having to work around an awkward moment in Relax NG would probably not exert a lot of influence on decisions about element names. Or, at least, it wouldn’t for me.

Standards, like XML or HTML, are enormously influential. Conventions, like TEI, which have more modest claims to normativity, don’t carry as much weight. But conventions are important for community, interchange, and interoperability, so if you want to be able to benefit directly from the hard work of other smart people, there’s a payoff for doing things the way they do, at least as long as that’s consistent with your own research agenda.
