### ISSUE TITLE
Number Changes Lose My CSS?

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#28]
Hey everyone! For my latest CSS assignment, I found something bizarre. After changing document names from "schatten-1.css/xhtml" to "schatten-2.css/xhtml," including in the <link> header line, as a test, the otherwise-identical files no longer find each other when uploaded to Obdurodon, showing the xhtml page without any formatting! What's up? The schatten-1 page still loads fine!

**Comment by djbpitt** [comment]
Both of your pages are rendered with styling for me. The new one is at <http://obdurodon.org/~das228/schatten-2.xhtml> and the old one is at <http://obdurodon.org/~das228/schatten-1.xhtml>. 

The difference in the HTML content is easy to see because the `<h1>` header text is different. 

The reason the styling looks the same is that the only thing you’ve changed so far is that you’ve specified a color for `<div>` elements. Since your only `<div>` contains `<p>` elements, the color you specify for the `<p>` elements overrides the color you specify for the `<div>`. To see that you are able to apply styling to your `<div>`, try specifying a background color (since you don’t specify a background color for the `<p>` elements, you won’t see that overriding effect here).

In general, CSS properties are inherited down the tree when that makes sense, until you override the value by specifying another one. So the color you specify on your `<div>` would be inherited, except that you override it at the next level, on the `<p>` children of the `<div>`. What it means to “make sense” is subjective, but typically you get the behavior you expect. For example, if you specify that a list should have a border around it, you wouldn't expect separate borders around all of the list item children of the list. But if you specify a font for the list, you would expect all of the list item children to use that font.

**Comment by Idi0teque** [comment]
Apparently my browser was opening files such as schatten-2(1), schatten-2(2), etc, losing layout in the process. And yeah, changed a few more minor things. Thanks!
