### ISSUE TITLE
Schematron Exercise Question

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#281]
Hi all! So I was able to get my schematron doc to validate against my XML doc and show my error message if I set it to report an error for anything greater than 100, however when I replace my `gt` with  `eq` or `=` it says my XML  doc is valid when the sum is 101 and not 100... suggestions?

**Comment by zme1** [comment]
@rmf96 Would you mind posting a code snippet? I think I may know the issue, but I’m not entirely sure.

**Comment by rmf96** [comment]
`number(100) lt sum(child::stooge)`

is what I have which works for creating an error when the numbers are greater than 100, but when  I replace it with eq it says my xml doc is valid when it adds to 101 and not 100

**Comment by zme1** [comment]
@rmf96 It sounds like you're writing this inside a `report` element, which may be part of the confusion. 

`report` and `assert` are the two possible choices you have in writing Schematron rules. They both effectively do the same thing, but with inverse logic. When you write a `report*` you want the schema to flag an error when the condition written in your `@test` attribute is **true**. When you write an `assert` element, you want the schema to flag an error when the condition written in your `@test` attribute is **false**. 

Whether you use one or the other is entirely up to you, and whichever is more easy to conceptualize. You can either say "Here's a pattern. Let me know when my XML doesn't match with  it" with `assert`, or you could say "Here's a pattern. Let me know when my XML does match with it."

In your snippet, it looks like you're saying "Make a report any time the sum of my `stooge` elements is less than 100." If you change the comparison inside your `@test` without changing your element here, you're saying "Make a report any time the sum of my `stooge` elements is exactly 100."

Let me know if this helps!

**Comment by djbpitt** [comment]
Thanks, @zme1, for foregrounding the reciprocal symmetry between `<assert>` and `<report>`. For what it’s worth, I often stumble over the formal logic of these kinds of tests, and I have to pause and walk through examples in order to make sure that I’ve understood what my rule is saying.

@rmf96 By the way, you don’t need the `number()` function around your `100` because, since you don’t have quotation marks around the digits, XPath will know that it’s a number. You would need `number()` for `number("100")`, though, since the quotation marks make it a string, and the `number()` function then turns the string into a number. I needed the `number()` function in my demo, even though there were no quotation marks, because XPath interprets any value that it pulls from the XML as a string, even though a human can plainly see that it isn’t. But since you’re typing your `100` literally though (no quotation marks and not read from inside an XML document), you don’t have to coerce it with `number()`.

**Comment by rmf96** [comment]
This helped a lot! I think I was definitely confused by the difference between `<assert>` and `<report>` but it's much clearer now. Thank you!
