### ISSUE TITLE
Class Discussion Post: Difference Between 'assert' and 'report'

### ISSUE THREAD

**Issue by k-busko** [obdurodon/dh_course#282]
I think I left class the other day with the impression that both 'assert' and 'report' as functions of a Schematron document were interchangeable elements. I was wondering if I could get some clarification as to if this is correct or (and this is more likely the case) if I am wrong and what the defining differences between these two are since they both seem to serve the same if not similar purpose in the schema.

**Comment by loreese** [comment]
I'm a bit unsure that I have the difference down pat as well, so if I'm missing the mark I'd also apprectiate clarification. The way I'm thinking about assert and report is that they *can* be used in any situation, it just depends on how you're expressing an XPath formula. One might be more conducive than the other depending on what you're trying to flag and why.
Think of it in terms of a true vs. false return. An assert element will flag and return a result if the XPath expression proves something false in the document you're running the schematron against. Conversely, a report element will return something if the Xpath expression proves true in the document. 
Say you're trying to write an expression that returns any negative number values in a document. You could write an assert element that expresses all numbers must be positive values, or you could write a report element that expresses no negative numbers can appear in a document. The assert element (which expresses all numbers must be positive) would return any negative numbers because all the numbers are *not* positive, and therefore makes the expression *false*; the report element (which expresses no negative numbers can appear in a document) would return any negative numbers because negative numbers cannot exist in the document, and therefore makes the expression *true*.

**Comment by zme1** [comment]
@k-busko @rmf96 had a similar hiccup in her own Schematron assignment. Discerning the logical differences between `assert` and `report` is often a point that deserves continuous and careful attention, since, as @loreese says, the two can effectively perform the same constraints, but with inverse approaches. Your use of either approach depends entirely on whichever seems more comprehensible to you as you write your Schematron.

**Comment by djbpitt** [comment]
As @loreese observes, _asserting_ that a certain condition must be true can alternative be expressed by _reporting_ if its opposite is true. But we need to be cautious about defining that opposite condition. For example, non-negative real numbers are not necessarily positive, because they could also be equal to zero, so the opposite of negative is not “positive”, but “positive or zero”. The individual values that are easy to overlook during testing are called _edge cases_.
