### ISSUE TITLE
Schematron - Class Discussion Post

### ISSUE THREAD

**Issue by khuber116** [obdurodon/dh_course#283]
As we began learning about Schematron I was struggling a bit. I didn't really understand what was happening other than it used XPath to find things. However, having completed one assignment involving it, I feel much more comfortable than I did before. I also found [this](http://schematron.com/an-overview-of-schematron/why-is-schematron-different/) page that offers a really easy-to-digest explanation of what exactly Schematron is and what it can be effectively used for. I found reading it to be very helpful and I think some others might as well.

**Comment by Ethandaniel47** [comment]
I think I personally found Schematron difficult from the start because it seems to be a hypothetical tool. It appeared to me as if you were only to use Schematron if you had already noticed a mistake in your code, however, I wasn't entirely sure that it was worth it to create an entire new schema association as opposed to just fixing the mistake. I recognize now that it is meant to be use preemptively to avoid making those same mistakes a second time. I appreciate its ability to standardize more so than anything.

**Comment by djbpitt** [comment]
@Ethandaniel47 You”re right about this: Schematron is useful both preemptively and as a way of responding to errors by adding a rule that prevents the same error from going unnoticed. In my own work, I typically do a combination of those methods: I write the rules in advance that address mistakes I think are likely, and then add more when I make a mistake that I hadn’t anticipated. The link that @khuber116 provides in his message at the start of this thread does a good job of illustrating where and why Schematron is useful.
