### ISSUE TITLE
Schematron

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#284]
While I was completing the homework, I was referencing the example we did in class as well as the Github posts, but I could not come up with the correct condition to list in the rule. I know my problem was that I could not figure out how to properly say that the average must equal 100. This is what I had:
`<report test="avg(//results) =100">`

**Comment by zme1** [comment]
@emmamamula It looks like you didn’t wrap your snippet in code delimiters. Would you be able to reformat your post so we could see it?

**Comment by Nerdologist** [comment]
@emmamamula I would suggest using the condition that the sum must equal 100, rather than the condition that the average must equal 100. If you use the former condition, your Schematron will not rule out all the sets of percentages of votes you want it to rule out. The average may well equal 100 even though the percentages add up to more than 100, but you want to rule out any sets whose sum isn't 100.

**Comment by djbpitt** [comment]
@emmamamula Yes, @Nerdologist is right. The issue is that you want the *sum* of the stooge percentages to be 100, and not the average. Your XPath syntax is exactly corrects; the only problem is that you're taking the wrong measurement by calculating the average instead of the sum.
