### ISSUE TITLE
GitHub update issue

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#286]
I was told not to use the Vim editor in GitHub, but to use Notepad++ instead, which I did. Now GitHub wants me to update, but when I switch the drop down to Notepad++ the next button is greyed out. Should I just ignore the update or should I choose one of the other options, and if so, which one? I also clicked on the Notepad++ link thinking it wanted me to do something with that, but that didn't help. Thanks!
[update question.docx](https://github.com/obdurodon/dh_course/files/2912367/update.question.docx)

**Comment by djbpitt** [comment]
@spkellyo  The vim editor is unfriendly to new users, so unless someone is already comfortable with it, we usually recommend that they use something less alienating, and Notepad++ seems to be a popular choice on Windows. Because I’m not very familiar with Windows, though, I can’t tell just from your screen shot where you are in the configuration process. Let’s try the following:

1. If anyone reading this is a Windows user, I would be grateful if they could chime in and help.
1. If nobody suggests a way forward, stop by and I’ll take a look at it with you in real time. I’ll write to you by email about possible meeting times.

**Comment by enb34** [comment]
@spkellyo I also use Notepad++ instead of the vim editor, so I have some experience with this. That being said, I haven't had to deal with this issue that you're currently having, so I can't say for certain how to go forward from here. I'm unsure of what your other options are for the update, but I'm assuming that you'd have the option of keeping the default vim editor. If this option will allow you to continue with the update, because you can change the editor to Notepad++ using `git config`, my best suggestion is to update with the default vim editor and then change it after the update is completed. I've linked the article I used below that talks about how to change the default git editor to Notepadd++ specifically:
[Setting the Default Git Editor](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-set-Notepad-as-the-default-Git-editor-for-commits-instead-of-Vim)

You can later check if you were successful in switching the editor by forcing git to create and open a global .gitconfig file with the command `$ git config --global --edit`. If you were able to change the editor, the file will open in Notepad++, and you'll see a code like this one in the content of the file:
`[core] editor = 'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin`

**Comment by spkellyo** [comment]
Great idea, I should have thought of that. Thanks!
