### ISSUE TITLE
XSLT Troubleshooting

### ISSUE THREAD

**Issue by Ethandaniel47** [obdurodon/dh_course#291]
I wasn't in class on Monday when we did a bit of an introduction to XSLT so I have been spending the day trying to teach myself how to do it. So far, for our assignment do in the morning, I have been able to get XSTL debugger to return the Act Titles and the Scene Titles as two separate list elements but as a single list.
`<li>Act One, Act Two, Act Three, etc</li>`
I have yet to figure out how to create a list item element for each act title and scene title individually. I have seen a lot of tutorials using the for-each attribute, but as we arent supposed to use that on this assignment, I am unsure of where to go from here.

**Comment by djbpitt** [comment]
@Ethandaniel47 From the information you provide, it sounds as if you are applying templates to the heads of acts and scenes, but you don't have a template rule that matches them, so you're getting the default, which is just to write the text into the output. Forget the scenes for now and try applying templates to the acts and then writing a template rule that matches acts, creates a list item for each act, and get the value of the head inside the list item. 

Once you have that working, you apply the same strategy to reach down one more level, so that, much as you process all of the acts in the play, you then process all of the scenes in each act.

A first XSLT stylesheet is always a challenge, and you're at a disadvantage because you weren't present when we introduced it. If you don't see a way forward after making a reasonable attempt, submit it as is and we'll go over it in class.
