### ISSUE TITLE
XSLT Exercise 1 (Bad-Hamlet) 

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#294]
Hi, I'm having a lot of trouble understanding how to finish (or even how to start it), the tutorial is not being helpful and we did not have enough time in class to explain it. Could anyone tell me where is that I suppose to write? and where it should appear? on the "Text Output" side or the "XHTML Output" side?

**Comment by djbpitt** [comment]
@ddaud02 The output appears simultaneously in both the Text and the XHTML tabs because it’s the same output. The Text tab shows you the raw HTML, which is what you would see if you did a “view source” on a web page. The XHTML tab shows you what the formatted HTML would look like in the browser. When we were running the transformations in class, we looked at both of those views at different times. You won’t see anything in the XHTML view, though, unless you are creating some output inside the HTML `<body>` element, because that’s the only part of a web page that is visible in the browser window.

When you switch into the XSLT debugger view inside \<oXygen/\> (by clicking on the little icon in the upper right that says XSLT and has a red bug on it—be sure to click the one that says XSLT, and not XQ), there are three panels. Your XML documents are on the left, and your XSLT documents are in the middle. For this exercise you'll probably have just one XML document and one XSLT document open. So you don't type on the XML side (that’s just the XML file, which you open and then don’t edit), you do type in the middle (that’s where you’re writing your XSLT), and you don’t type on the right (that’s where the output of your transformation will appear.

**Comment by ddaud02** [comment]
Thanks, @djbpitt, In the beginning, I was using the bad-hamlet that we used in classes but then I was left in doubt if I had to use a new XML using the format that appeared below. 
![untitled](https://user-images.githubusercontent.com/46380238/53857037-b676c680-3fa2-11e9-8738-bfcc8ed895e4.jpeg)

**Comment by djbpitt** [comment]
@ddaud02 The input is our familiar bad-hamlet XML. The screen shot above is the HTML output your transformation should create.
