### ISSUE TITLE
XSLT Issue with inputting 'Acts' and 'Scenes'

### ISSUE THREAD

**Issue by k-busko** [obdurodon/dh_course#295]
I am having great difficulty figuring out how to create the in-order list of 'Acts' and 'Scenes' using <ul> and <li> in the XSLT #1 assignment without manually plugging in what is required. I understand that doing so would defeat the purpose of this assignment but after re-reading the XSLT basics reading and the assignement's directions I am still stuck. Maybe I am thinking too narrowly about how to get this accomplished?

**Comment by djbpitt** [comment]
@k-busko We can’t read your code above because you didn’t use markdown delimiters to identify it as code. As a result, it disappears. Please fix this, which you can do by clicking on the three dots in the upper right of the panel where your message is being displayed, choosing the option to edit it, and putting the correct delimiters around it. You can read what those are by clicking on the “Styling with Markdown is supported” link lower on this page and reading about how to style code with Markdown.

The way you get the output without typing it manually is to use XSLT, together with XPath, to extract it from the source XML. The XML already says “Act 1” or “Act 1, Scene 1” in appropriate places, and XSLT can find those for you and write them into the output. This is always a confusing task on a first XSLT stylesheet because XSLT is so weird, so if you aren’t able to get it to work, don”t worry about it, but do what you can, and we’ll complete it together in class.
