### ISSUE TITLE
XSLT Basics: Discussion Post

### ISSUE THREAD

**Issue by khuber116** [obdurodon/dh_course#296]
I know I post a lot of links to other websites, but after struggling to really even begin to understand what exactly XSLT is/does I found a [tutorial](https://www.webucator.com/tutorial/learn-xml/xslt-basics.cfm) that uses a lot of examples which is extremely helpful if you're someone like me who needs these visuals to help them learn. I think this is going to be very beneficial to me as we continue with the XSLT assignments and I hope it helps some other people too.

**Comment by djbpitt** [comment]
@khuber116 Thanks, Kyle! Different users benefit from different explanations, so we always welcome links to sites that people find clear and effective. 

For reasons we’ll discuss later in our XSLT unit, we don’t recommend using `<xsl:value-of>` the way they do in that tutorial. It has a use, and we will work with it later, but the way they use it in the tutorial is not appropriate to a lot of types DH data, so it isn’t a good first strategy . And they don’t teach `<xsl:apply-templates>`, which is a key element, along with `<xsl:template>`, for working with the type of data that is common in DH projects. One point of this first assignment is to approach it using `<xsl:apply-templates>` in a relatively simple situation, as a way of easing into more complex situations later. You can solve this particular task in other ways, but those aren’t the ways you’d be likely to use in your projects, so they aren’t the ones we emphasize.

The more general issue is that a lot of XSLT tutorials (and XML-related tutorials) of all types assume that everyone’s XML will be like database records. The `<person>` and `<beatle>` elements on the tutorial site you identify is that type of data: there are labels (like name) and values, but the hierarchy is shallow and there is no mixed content. DH data, though, is often deeply hierarchical, with mixed content at all levels, where paragraphs contains mixtures of plain text and other elements, and those other elements contain mixtures of plain text and other elements, etc. That’s the most common type of data in our course projects, it cannot be processed without `<xsl:apply-templates>`, and `<xsl:value-of>` does not normally produce types of output that we need. For that reason, we emphasize using `<xsl:template>` with `<xsl:apply-templates>` from the beginning, and we avoid `<xsl:value-of>` untll it’s really the right strategy.

If you’d like to read ahead, the issue is one of when to use **push** and when to use **pull** methods, as described in the “Push and pull design” section of our <http://dh.obdurodon.org/xslt-basics-2.xhtml>. That’s an advanced topic so we don’t lead with it, but since it comes up in discussing how the approach in the tutorial you identified differs from ours: their approach is heavily pull, which is an okay fit with their data, but not with our project data. The method we emphasize is heavily push. The difference will become clearer once we’ve had a chance to explore where each is appropriate.

**Comment by loreese** [comment]
Thanks for posting a link to this- I'm finding myself heavily relying on visuals as we're progressing through these units. In addition to visual aids, I've tried a few YouTube tutorials for when I get really stuck. While the videos themselves are pretty hit or miss, sometimes it helps with recalling things from class or connecting concepts when you hear a verbal explanation of the process while having it demonstrated. I came across this one pretty early on when trying to conceptualize what I was doing with my xsl: templates and xsl: apply-templates https://www.youtube.com/watch?v=AfMUd7kjGS8
Like I said, they're a bit dry, but it's 10 minuets that might help jarr something upstairs.

**Comment by djbpitt** [comment]
@loreese Thanks, Lo! Looking at multiple sources of information is a Good Idea, both because different presentations will suit different learning styles and because repetition of key points in different ways will help reinforce them.

What I like about this tutorial is that:

1. It shows how to step through a transformation in \<oXygen/\> and watch it unfold step by step. We haven’t been doing that in class, but when I don’t get the results I want or expect, the step-by-step processing lets me check the effect of each line of code, so that I can see where things go off the rails. 
1. I like that he accidentally started processing the wrong *instance* (a technical term that means “XML document”) and had to stop the transformation, select the correct one, and begin again. As we mentioned in class, that’s an easy mistake to make, and by leaving it in the video instead of reshooting, he reminded us that it happens even to experienced developers.
1. The video illustrates using `<xsl:apply-templates/>` without a `@select` attribute. We haven’t covered that yet, but what it means is “apply templates to all of my children”. That’s a common idiom, and we’ll see later why it’s useful.

The video was made in 2009 and uses XSLT 1.0, which is very different from the 3.0 that we use today. For the most part 2.0 teaching materials have retained their value when we learn 3.0, but 1.0 had some serious limitations. They don’t matter in this tutorial, so this is more of a general warning that, when other things are equal, 2.0 and 3.0 tutorials are better than 1.0 ones.

My specific concerns with methods he illustrates are that:

1. It uses `<xsl:for-each>` and `<xsl:value-of>`, which, as we said in class (and see above), are often the first choice for flat, database-like XML, but usually not a good fit for the deeper hierarchies and mixed content that we find in humanities documents. What we usually do instead of `<xsl:for-each>` is apply templates. For example, in class we did something for each act, and for each scene of each act, but by applying templates to them (and not with `<xsl:for-each>`). And what we usually do instead of `<xsl:value-of>` is apply templates to a node without creating a matching template, so that the built-in (default) will kick in and give us the text. We did that to get the textual value of the `<head>` elements into our output. We will see situations where we need `<xsl:for-each>` and `<xsl:value-of>` later, but it’s more useful to learn how to use `<xsl:template>` and `<xsl:apply-templates>` first. 
1. The tutorial is a little careless in its description of how processing flows through the document. As we saw in class, when we applied templates to acts and then wrote an empty template to process acts, it caught them and prevented further processing. In other words, the children of an element are not processed automatically when we process the element itself; if we want to walk down the hierarchy, we have to specify that explicitly with an `<xsl:apply-templates>`.
