### ISSUE TITLE
Problems with Pulling from Repo

### ISSUE THREAD

**Issue by Nerdologist** [obdurodon/dh_course#299]
The last time I successfully pulled from the repo for our Midrash project, the number of files in my local repo was reduced to two, but there are many more files in the repo. So I used the "git status" command to see what the issue was, and I got this:

![image](https://user-images.githubusercontent.com/46368238/53896775-b8707200-4002-11e9-83d8-d4c8793919bb.png)

This indicates that I need to pull some more times to catch up with those 6 commits, but when I attempt to do so, I get this message:

![image](https://user-images.githubusercontent.com/46368238/53897645-9677ef00-4004-11e9-80c2-4de8ed0623a1.png)

In response, I tried deleting the file and pulling again, after which the file I deleted reappeared in my local repo but no new files appeared, and I received this message:

![image](https://user-images.githubusercontent.com/46368238/53897858-025a5780-4005-11e9-8209-81ebf1d57aed.png)

The only way I seem to be able to get my local repo up to date or nearly so is by using the following command:

![image](https://user-images.githubusercontent.com/46368238/53898145-83195380-4005-11e9-8b9c-4195b47af655.png)

After doing this, everything that the message in the first picture says was deleted appears in my local repo. But if I use "git status," this is displayed:

![image](https://user-images.githubusercontent.com/46368238/53898616-70ebe500-4006-11e9-910f-f670d6425be9.png)

So I executed "git add Resources/" as suggested, and then executed "git status":

![image](https://user-images.githubusercontent.com/46368238/53898859-ec4d9680-4006-11e9-83b2-d53b9ef0b487.png)

But I still get a "fatal" message when I use "git pull" at this point, and my local repo is reduced to the same two files I started with:

![image](https://user-images.githubusercontent.com/46368238/53898892-00919380-4007-11e9-922c-1dd37ae88e8b.png)

Where do I go from here? How can I get "git pull" to function properly?

**Comment by Guifindor** [comment]
You need to rename that directory "XML:Relax" to not include a colon. The colon character is an illegal character to use in directory names, at least on Windows. I believe that's what is causing your issue at the bottom there.

**Comment by djbpitt** [comment]
@Nerdologist In addition to the suggestion from @Guifindor (which explains the error message in your third screen shot), you have spaces in your filenames (see your second screen shot, above). You need to get rid of those. As we write at <http://dh.obdurodon.org/file-naming_conventions.xhtml>: “Course project files, though, must still have correct extensions and must not use any characters except for letters, digits, periods, hyphens, and underscores (in particular, no spaces and no other punctuation).”

The warning message in your first screen shot is because, apparently, you have a file locally that has the same name and location as the one on GitHub, they both have different changes, and you haven’t committed your changes locally. This can happen if someone else pushed one version of the file to GitHub while you were working on your own version. It can also happen if you or someone else edited the file directly on GitHub, which is why we advise against ever doing that (all changes should be made on the local machine and pushed). It isn’t necessarily an error; usually it’s just Git’s way of ensuring that you don’t accidentally overwrite something you might want to keep. How to deal with it depends on what you want:

1. You can throw away your changes and just accept the version that’s on GitHub.
1. You can commit your changes and then pull the version that’s on GitHub, which will merge the two sets of changes (assuming they can be merged).
1. You can move your changes out of the way, pull the version that’s on GitHub, and then restore your changes and resume editing. 

How to decide, and how to implement the decision, is a bit intricate, and difficult to explain in writing, but if you’ll stop by during one of our office hours, we’ll walk you through it.
