### ISSUE TITLE
Relax NG Test

### ISSUE THREAD

**Issue by danakaufhold** [obdurodon/dh_course#30]
Does anyone else have a problem with their Relax NG where in validating the schema, even though you've continually saved/updated everything, Oxygen seems to be a few steps behind? For example, I'd saved/validated my schema many times, and I was still getting an error message for something I had fixed. I couldn't figure out what was wrong, so I submitted my schema. When I opened Oxygen later, it had finally caught on and decided to show me what was actually wrong with my schema. Is there a way to avoid this?

**Comment by djbpitt** [comment]
When this happens to me, it's because I'm saving a copy of my schema file in the wrong place, without realizing that I still have the old one associated with my XML. I fix the problem, save the copy, but because the copy I'm saving isn't the one that I've linked to my XML, it looks as if the changes aren't being implemented. Is that type of scenario possible in your case?
