### ISSUE TITLE
Background images won't appear

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#305]
I am following the rules about background images, but for some reason they aren't appearing. I used `url("image.jpg")` but nothing is happening. I tried `url(images/image.jpg")` but that doesn't work either. Images is the folder where are images are. I am not uploading and trying everytime, I am just saving my work and refreshing the url I opened using my xml. I associated the .css so I am not sure what the problem is. Any help is appreciated. Thanks.

**Comment by gabikeane** [comment]
Looks like we're both having fun with CSS this evening!

That "url" path used to find the image is read as relative to the CSS's position. For example, if I try to open something from my desktop that has a background in "images/image.jpg", the folder called "images" must be on the same level as the CSS file that is calling on the image it contains, otherwise the system doesn't know where to look.

So, if my file hierarchy looks more like this: 
- site_files (contains HTML, CSS, images)
- HTML (contains my_html.xhtml)
- CSS (contains my_css.css)
- images (contains image.jpg)

then my CSS link path in my HTML will look like this:
`../CSS/my_css.css`

my image link path in my `url()` will look like this:
`../image/image.jpg`

**Comment by gabikeane** [comment]
When I need to troubleshoot this, I most often stick a few working files on my desktop and see if I can get it to work with the simplest possible file path. Then, once I've Gabi-proofed it, I start to figure out the path from there and test it for real.

**Comment by djbpitt** [comment]
@spkellyo I don’t know whether this is related to your problem, or whether you just misstyped here, but you’re missing a quotation mark where you write `url(images/image.jpg")` above.

One annoying issue in CSS development is that the browser sometimes caches and reuses an old version of a CSS file even when you’ve made changes and want it to reload it to use the new information. Sometimes a forced reload will help (see <https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache>) and sometimes *private browsing* (<https://en.wikipedia.org/wiki/Private_browsing#Support_in_popular_browsers>) does. 

Most of the time, though, when my web page can’t find my image, it’s because I didn’t specify the path correctly, as Gabi wrote above. That you aren’t uploading is fine; the CSS you’re developing should work normally if you load aa page locally from your file system, as you’ve been doing.

**Comment by spkellyo** [comment]
Thanks both of you!  I realized that I was working on an xml and css file in a totally different directory (on my hard drive not my repo) and the images are in the repo directory, so that explains that. 
So, one thing I wanted to be clear on, do I use double quotation marks or single? Above was a typo, I was using single.

**Comment by gabikeane** [comment]
Either works, but if you keep it consistent you'll have an easier time spotting errors.
