### ISSUE TITLE
XSLT CSS

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#308]
Every time I insert the link element in my HTML document:

`<link rel="stylesheet" type="text/css" href="fox_03-18_CSSforXSLT3.css"/>`

and hit the run button it disappears..?

**Comment by djbpitt** [comment]
@rmf96 Are you inserting the `<link>` element in your XSLT so that it gets written into the HTML, or directly into the HTML? Since the HTML gets created by running the transformation, each run will overwrite the output of the last one. To get the `<link>` into the output, you need to put it into the XSLT and let the transformation write it into the output for you.
