### ISSUE TITLE
XSLT 4 fail

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#312]
While working on XSLT 4, I was not able to successfully obtain the Roman Numerals, but I had the rest of the document set up. I figured I would try and create the table of contents despite not having the Roman Numerals, which was a bad decision. I cannot insert the code I used because it low key broke <oXygen/>, but whatever I did removed the sonnet structure and line breaks. The note at the bottom of the screen said something about the text being too large and having to wrap, it remained loading in debugger view for like 20 minutes before I forced quit. So I am not sure what happened, but I know it was not good.

**Comment by djbpitt** [comment]
@emmamamula It isn’t clear (well, to me) from your report what went wrong, but it is clear that, as you write, it was Not Good. It sounds as if you may have had a bottomless recursive operation. For example, inside the template that processes `<sonnet>` elements you might have applied templates to `<sonnet>` elements, which would keep calling the same template repeatedly, with no way to break out. Try it again and save after each change, so that if something breaks, 1) you won’t lose your work up until that point, and 2) you’ll know which step broke the code.
