### ISSUE TITLE
Peculiar XSLT Debugger Error message

### ISSUE THREAD

**Issue by pickettj** [obdurodon/dh_course#316]
I abruptly began receiving the following XSLT debugger error message: 

> The source document is in namespace http://www.w3.org/1999/xhtml, but all the template rules match elements in no namespace (Use --suppressXsltNamespaceCheck:on to avoid this warning)

(This is different from [the last debugger error](https://github.com/obdurodon/dh_course/issues/301) I had, and updating Oxygen seems to have solved the previous issue.)

I get this error message even when running the exact code from the [posted solution to XSLT no. 4](http://dh.obdurodon.org/xslt-assignment-04-answers.xhtml). 

Moreover, the output does not register the `<xsl:apply-templates>` calls, instead resulting in raw text after the title area:

```
<body>
      <h1>Shakespearean Sonnets</h1>
      <h2>Contents</h2>
      <ul/>
      <hr/>
   
      Shakespearean sonnets
   
   
      Shakespearean sonnets
      Contents
      
         I. From fairest creatures we desire increase,
         II. When forty winters shall besiege thy brow,
         III. Look in thy glass and tell the face thou viewest


```

I.e. actually formatted in the raw code, but jumbled together in the HTML tab:

![image](https://user-images.githubusercontent.com/25989796/54775671-d7ffc100-4be4-11e9-8efc-ead207f3f2cb.png)

Help appreciated.

**Comment by gabikeane** [comment]
Are you using Command + U to open the URL directly? Your source document shouldn't be in the HTML namespace. I think fixing that error message should help the other issue. If it does not, can you please post a code snippet from the XSLT so we can see what's going on?

**Comment by pickettj** [comment]
I was indeed opening it directly from Command +U, and saving it to my hard drive did indeed solve the problem. Thanks!

So... what is the difference? Does the server add it into the html namespace somehow, despite it being an XML file? Similarly, how come it worked before without any issues?

**Comment by djbpitt** [comment]
@pickettj Is it possible that you were loading our sample output (which is in the HTML namespace) and not the input XML (which is in no namespace)? The reason you were getting raw text instead of the results you expected from your templates is that if the document was in the HTML namespace and your templates weren’t, you effectively had no templates (since you had none that matched elements in the HTML namespace), so the built-in behavior did all the processing, and the built-in behavior throws away the markup and gives you the text. The server can’t add a namespace; the only explanation I can think of for the document being in a namespace was that it was an HTML document, and not the XML one. If you can bring your laptop to class Friday, let’s try to replicate the problem.

**Comment by pickettj** [comment]
Yes, I think that is exactly what happened. Thanks! Learned something in the process of a stupid mistake though...
