### ISSUE TITLE
Stylometry for a Thought

### ISSUE THREAD

**Issue by brenda275** [obdurodon/dh_course#324]
This project requires a lot of collaborative work. It just made me realize how important it is to come together as a group to share our ideas (no duh right?). As I read through the project updates of other groups I noticed that most groups are dividing up the work based on overall tasks, such as xml markup and CSS/html. The only difference between the tasks is that one deals with the analysis of the text and the other deals with the representation of the information. It is just one way to divide the work, but it made me wonder if doing it that way will affect the outcome of our results opposed to if we had each member contribute some work to each task. Would there be a noticeable difference between the two methods? Or is it mostly dependent on how well we can communicate our ideas to each other to reach a mutual agreement?

**Comment by djbpitt** [comment]
@brenda275 Some teams divide the labor for practical reasons, such as knowledge of the language of the texts being used in the project. Other teams may divide the work by personal interest. For example, it’s often the case that one team member geeks out on CSS and is eager to do that All The Time, while the other team members would prefer something else. Sometimes one team member wants to try something that isn’t a core component of the course, like topic modeling or network analysis, and branches off to do that while the others stick with the major project tasks. And there are teams where everyone does a bit of everything because they all want the breadth of experience. All of those are workable models as long as everyone is on board.

Our only general advice is that, whatever approach you take to dividing responsibility, the team members should consult closely, so that everyone knows what everyone else is doing. That avoids the risk of winding up with uncoordinated output, such as different aspects of the project that don’t cohere effectively. If you check in with one another regularly, it also gives you a chance to discuss places where you might be stuck or uncertain, and to ask for—or offer—help.
