### ISSUE TITLE
Test Number 6 (XSLT)

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#325]
I'm having a problem while doing the table of contents. Every time that I try to create the table all the previous information appears, I want it to start on `Act 1` and not include all the information above **text** and `tags` How can I fix this?

<img width="921" alt="Screen Shot 2019-03-29 at 10 36 52 PM" src="https://user-images.githubusercontent.com/46380238/55270266-37a83d00-5273-11e9-9424-794e663c35e1.png">

![1](https://user-images.githubusercontent.com/46380238/55270286-60303700-5273-11e9-9209-22bece731d8f.jpeg)

**Comment by djbpitt** [comment]
@ddaud02 What are you applying templates to that winds up generating content that you don’t want? What happens if you apply templates only to what you want to process?

**Comment by ddaud02** [comment]
I am applying specific templates for each component (e.g. for title, author, translator, publication statement, cast list, cast item, act, speech, speaker, line, stage, quote). For "act" I have a "regular" template that creates the actual content, and a "toc" mode. No matter where I put the "toc" apply-templates, it seems to include all the text (as plain) until it reaches the first <act>. I am not using a general apply-templates; I'm using <xsl:apply-templates mode="toc">.

![body](https://user-images.githubusercontent.com/46380238/55296492-33516080-53e8-11e9-9b5d-63ec630274ce.jpeg)

**Comment by djbpitt** [comment]
@ddaud02 When I wrote “What happens if you apply templates only to what you want to process?”, that was about not `@mode`, but `@select`. If you apply templates without a `@select` attribute, you apply templates to _all_ of the child nodes of the current context. If you haven’t written your own templates (in the specified mode) to handle all of those children, the ones you are not processing by your own rules will be processed by the default, built-in rules, and the built-in rules will typically give you text. If you don’t want the text, or anything else, for those other children, you can use `@select` when you apply templates to avoid applying templates to them, that is, to keep them from being processed at all in that mode.

**Comment by ddaud02** [comment]
Thank you for quick response. Using <xsl:template select="act" mode="toc"> makes the unwanted text goes away, but the TOC links for Act I Act II also disappear (see figure 1). If I use @select to individually apply each template (for example select="title", select="author", etc), then everything disappears... but the unwanted text is still there (second figure) :(

The only thing that works (kinda) is moving <meta> and <castList> to the end of the input file. That makes the TOC appear correctly! But of course also moves the title/author/translator to the end of the HTML...

![Fig1](https://user-images.githubusercontent.com/46380238/55297220-22a5e800-53f2-11e9-9aa3-bef895513c7f.jpeg)

![Fig2](https://user-images.githubusercontent.com/46380238/55297224-276a9c00-53f2-11e9-8020-6b13657ac3e0.jpeg)

**Comment by djbpitt** [comment]
@ddaud02 I don’t think I should debug this any further, but it sounds as if you’re on the right track now in that you’re thinking about the interaction of `@select` (which wasn’t part your strategy earlier) and `@mode` and the contexts in which you apply templates.
