### ISSUE TITLE
Single-Issue discussion: The hermeneutics of screwing around

### ISSUE THREAD

**Issue by zme1** [obdurodon/dh_course#328]
If you read *The hermeneutics of screwing around*, write your response to the reading here.

**Comment by MLuckman** [comment]
I read *The Hermeneutics of Screwing Around*; or What You Do With a Million Books. I thought that the writerly texts discussed at the end were similar to the Lo-Fi Manifesto in that they both (by my understanding) seemed to advocate for/appreciate anarchic/open-source/decentralized systems as a way of doing scholarship.

**Comment by emmamamula** [comment]
I think that "The hermeneutics of Screwing Around; or What You Do with a Million Books" is persuasive in that Ramsay succinctly states why it is important to distinguish the act of searching from browsing, especially on a digital platform. He does express that not all research is the same, he uses the example of finding information on Reddit or Digg versus on a research database or library site. In my opinion, this distinction is overly generalized similarly to how teachers in high school acted as though Wikipedia is entirely useless and unreliable, when in fact, viewing the sources used to write the wiki page can be helpful. Ramsay's argument is persuasive, but the main drawback is how he discredits methods of research that are less orthodox.

**Comment by ddaud02** [comment]
_The Hermeneutics of Screwing Around; or What You Do with a Million Books_, has some interesting points, there is not enough time to read all the books that had been written in the world, neither record of all of them. However, proyects that try to digitalize all the written word, could present us a whole new world of posibilities and computational analysis. **Humanities** tend to depend more on this kind of works/texts more than others sciences or disciplines. I remember when I was a teneager and I discovered Microsoft Encarta, which is the old version of Wikipedia, it was not only a good source to find information but also it was a tool that developed efficiency and accuracity.  Many people believe that just relying on theese kind of tools is making us not to think anymore. However, I beleive that you need a lot of skills also to find the exact information. We live in a world where information is just two clics aways, that is why we need to sharpen our information search skill.

**Comment by engeljonathan98** [comment]
Ramsay has hit on something I think about often, which is "What is the 'canon' of the world?" Or, put another way, "Who should we be listening to?"

Because that, ultimately, is what this conversation is about. If we take the humanities as the collection of knowledge about humans, from art to academia, by asking what about that collection is definitive we are inherently asking what authors should be heard and what experiences should be had.

Ramsay describes research as the practice of "go[ing] to the archive to set things right—to increase the likelihood that your network of associations corresponds to the actual one" (pg. 6). That is to say, we read to confirm that what we have learned reflects reality. Thus, our understanding of reality is based on our prior readings.

In the online world, we understand more than ever the problem of the "information bubble". The basic anxiety goes like this: what if I'm not reading the truth? What if I'm reading a collection of similar lies and I can't escape these lies so my _sense_ of reality has nothing to do with _actual_ reality? This problem is not new to the recommender algorithm-driven web world, but one as old as time. Our reality is inherently constructed and the issue of how we get materials to construct that is crucial.

A manifestation of this problem: be honest with yourself. How many African philosophers have you read? Not African American, though also African American, but African. Any? How many Asian? How many Native American? Etc. Our political status quo defines who is read. It does this in such a way to recreate itself. "The divine right of kings seemed inescapable," to paraphrase Ursula K. LeGuin.

Taking this hermeneutical crisis of canon to heart, our only response can be to be radically _iconoclastic_ in what we read. We must relentlessly pursue the unconventional, read the thing nobody else has read, pursue the perspective unheard. This is the _only_ way to pursue truth. It is necessarily an impossible and incomplete task. That is OK. But it is the task before us.

**Comment by k-busko** [comment]
"The hermeneutics of Screwing Around; or What You Do with a Million Books" was an interesting read as someone who regularly uses open sources like Reddit and Google daily.  I think that this article informs readers about an interesting distinction between systems we use to search versus ones we use to browse. I think the distinction here is that with 'searching' there is a more direct and specific goal with the search. The user knows, usually exactly, what they are looking for. Whereas browsing as a means of looking for information consists of less direction and purpose. The quote at the end of the reading "the pleasure of the text" harkens more with the that of browsing due to its leisurely pace of information processing compared to the speed of general searching.

**Comment by brenda275** [comment]
The phrase, “So many books, so little time” never hit me so hard until I read _The hermeneutics of Screwing Around; or What You Do with a Million Books_. It is definitely an insightful read on the difference digital humanities is making in terms of supplying texts. I found it quite amusing that Ramsey kept referring to browsing as "screwing around". Or even the fact that they draw a distinction between searching and browsing and how browsing has changed since digital humanities. Apparently, or at least what this article has led me to believe, reading a book or cultural knowledge doesn't necessarily mean reading it from start to finish. And without a doubt through computational tools it is easier to extract certain information from texts. In that sense, there is less time being wasted.

**Comment by Ethandaniel47** [comment]
Ramsay's text is concerned with the aspects of literary research (and other textual analysis) in a way that prioritizes efficiency. To browse a text in the way that one might browse a store assumes leisure in terms of time and perhaps a lack of direction in terms of a research questions. Researching can mean many different things, but using techniques and tools to zero in on certain aspects of texts when searching them instead of browsing them can expedite the research process and thereby expedite the road to research results.

**Comment by khuber116** [comment]
I think this is an interesting look at humanities research. As some other's have mentioned, I think that the distinction between browsing and searching is especially important. While one can browse without direction, though it may be inefficient there is still value in what they may find. Searching, on the other hand, leads to more direct results but could cause someone to miss out on something valuable.

**Comment by rmf96** [comment]
"The hermeneutics of screwing around" was a rather interesting read. I enjoyed reading about the difference between searching and browsing, or screwing around, and I thought that the author was pretty persuasive in his writing. By relating the concept to an example of the library, looking for a specific book or just looking around, it made his argument much easier to understand. I, for one, am a big fan of "browsing", however there are drawbacks with browsing for research rather than searching. Our project actually came to a crossroads with this issue: whether or not we would pick memes that we found funny while browsing around or doing a "search" and choosing the first 50 appropriate memes with no bias. We figured it was best to search rather than browse in order to mitigate any issues with data skewing.
