### ISSUE TITLE
Single-Issue discussion: In praise of pattern

### ISSUE THREAD

**Issue by zme1** [obdurodon/dh_course#329]
If you read *In praise of pattern*, write your response to the reading here.

**Comment by AncientGreekGeek** [comment]
I found this article really interesting because he described his process of how he came to rewrite his program StageGraph in order to conduct literary analysis on Shakespeare's plays. It was really interesting to see how he built up the program from having no idea what he was looking for to then trying to do data mining experiments with StageGraph to trying to make sense of what he found. I really like how at the end he brings back the idea that using computational methods to analyze certain data sets in the humanities is not supposed to give definite answers but is supposed to make us think of other questions that we need to consider.

**Comment by Nerdologist** [comment]
I noticed a weakness in Steve's argument that it is odd that visualizations used in text analysis are usually meant to demonstrate facts rather than to present open interpretive possibilities. He goes on to point out that StageGraph, and visualization-producing computer programs in general, force one to pick one interpretive possibility to display in one's visualization. If that is the case, it is no wonder, and nothing Steve can fairly complain about, that visualizations in text analysis rarely present a range of exegetical possibilities. Perhaps visualizations drawn by hand would not have this limitation, but it is to be expected that text analysts will often prefer generating visualizations with a computer to drawing them by hand. Also, given that there are computer programs that can reproduce any drawing one makes by hand, it is highly questionable whether Steve is correct that computers force one to choose one interpretive possibility to show in a visualization.

**Comment by sjw82** [comment]
I found Ramsay's argument very persuasive. He really won me over with, "if we interpret our graphs and tables in this way [subjectively], are we not introducing humanistic inquiry where it doesn’t belong; inflicting an inappropriate humanism upon the cherished positivism of scientific inquiry? Well, yes." (189) I appreciate a scholar with bold honesty and a field that is willing to put itself out there and grow along with technological revolutions rather than defer to "higher" scientific truth. The whole article he struggles with the duality of digital vs humanities and by the end arrives at the digital is a tool of the humanities, as much as we may try to keep it scientific. In his work mapping Shakespeare plays, he had to make some decisions in an unscientific way and in using software to do it he managed to arrive at some more unambiguous observations the goal of which was "to say something new, provocative, noteworthy, challenging, inspiring," (189) not necessarily to discover the underlying truth of all things. Humanities are inherently subjective (which actually came up in a [different article](https://www.chronicle.com/article/There-Is-No-Case-for-the/242724) I was reading by Justin Stover in the Chronicle of Higher Education in defense of higher education which in fact claimed that it needed no defense which I disagree with strongly, however, he would accuse me of being an instrumentalizing progressive so who is to say) and tied up in what some would see as the minutiae of the niche, that being the very thing that makes me question my role in the humanities, but Ramsay proffers the evolution of an arcane into a new era. In defense of research founded in subjectivity, Ramsay says to cast off the limitations of self-conscious apologetics, "not because interpretation must be careless and bold, but because it has to risk the perils of subjectivity in order to keep true to its own objectives—objectives which, in the context of literary study, seldom involve the amassing of verified facts." (190) What his article really dances around is the objective of the humanities. In some ways, I think his approach of beginning with a technology and arriving at a question is what can sometimes best suit this new field. The humanities are bogged down in the overspecialized (which Stover would argue is fine because it's always been that way) and perhaps extrapolating into new methodologies is the way to overcome that. Mapping Shakespearean plays may actually strongly influence the study of Shakespeare and who knows that domino effect that may have. By walking through his process rather than focusing on his product, Ramsay helped me to see a value in his work, perhaps because I too am conditioned in the positivism of the hard sciences, beyond his actual topic which to me matters so much less. The pursuit of knowledge rather than the pursuit of truth is in my opinion the point of scholarship, if not study more generally, and Ramsay's argument augmented my belief.
