### ISSUE TITLE
MALLET Stopwords Problem

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#332]
After several variations, I have been unable to remove an additional list of stopwords when running through mallet. I'm following [this guide](http://mallet.cs.umass.edu/import-stoplist.php) but am coming up short. I'm running this command to import documents:
`./bin/mallet import-dir --input /All --output tutorial.mallet --keep-sequence --remove-stopwords --extra-stopwords bib_stop` (I also tried bib_stop.txt because it is a text file)
And this command to output them:
`./bin/mallet train-topics --input tutorial.mallet  --num-topics 10 --num-iterations 10  --optimize-interval 10  --output-state topic-state_6.gz --output-topic-keys all_keys_6.text --output-doc-topics all_composition_6.text`
and am still getting stopwords in the output.

**Comment by djbpitt** [comment]
@sjw82 Let’s make an appointment to look at this together. But in case it’s helpful, the filename has to match exactly, so that `bib_stop.txt` requires the file to have that exact filename, and `bib_stop` requires *that* exact filename. The file also has to be findable, and your specification looks for it in the current working directory. I’m guessing that you already know all of that.
