### ISSUE TITLE
svg 3

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#334]
I implemented some `<xsl:variable>` elements into my svg 2 assignment, but now all of my bars are the same height and I am not sure why. 
<img width="1102" alt="Screen Shot 2019-04-04 at 5 49 24 PM" src="https://user-images.githubusercontent.com/46690872/55590868-20999d00-5702-11e9-8aed-83416ef0c828.png">
<img width="1101" alt="Screen Shot 2019-04-04 at 5 49 44 PM" src="https://user-images.githubusercontent.com/46690872/55590869-22636080-5702-11e9-8e46-2f503cf82daa.png">

**Comment by zme1** [comment]
@emmamamula Your stylesheet variable `$barheight` is set to a value of `300`. When you multiply that number by the percentage of democratic votes in a state, you likely generate bars that grow past the visible window of your SVG. Rather than calculate a *bar height*, try to scale your y-axis with a variable, so that the percentage of votes for a party multiplied by this scale value will give you a height that you expect.

**Comment by djbpitt** [comment]
@emmamamula One way to check whether your bars are really the same height, or just look that way because they are running off the top of the visible area, as Zac suggests, is to look at the raw, angle-bracketed output. Do they have the same `@height` or `@y` values?

**Comment by emmamamula** [comment]
So I checked the heights and the rectangles do not have the same `@height` and `@y` values. But I do not know what variable I should put into the bar height. I initially thought to make it equal to the dempercent, but that is a local variable and when I made the local variables general ones, it messed up the entire graph. I'm not sure how to proceed.

**Comment by djbpitt** [comment]
@emmamamula The bar height will be different for each bar, since Democrats won different percentages on the votes in different states, so it should be a local variable, and if you’re getting different values for each one, it sounds as if you’re on the right track. You can look at our posted solution to SVG #2, you know. Don’t just copy it without trying to figure out how it works, but it shows how we plotted the rectangles.

Do the `@y` values range between 0 and 100 (or, rather, 0 and -100, since `@y` values should be negative if you’re plotting in the upper right quadrant)? Since they’re percentages, they should. If you’re drawing in the upper right quadrant and then shifting the objects down with `@transform` and `translate()`, are the values consistent with what you’d expect? Try figuring out one `@y` value by hand: if you’re drawing in the upper right quadrant, that should be a negative value, and when you add the amount by which you’re shifting downward inside the `translate()` function, where do you expect that corner of the rectangle to be rendered?
