### ISSUE TITLE
Best practices for marking up gloss

### ISSUE THREAD

**Issue by pickettj** [obdurodon/dh_course#335]
As Elisa Beshero-Bondar noted in the guest lecture, footnotes can easily be encoded within the sentence hierarchy. E.g.: 

```
<s>The dog chased the stick.<note>Footnote text.</note></s>
```

What are the best practices that will make my life easiest later on for encoding *gloss* associated with a specific string?

For instance, one way would be to include the gloss text within the attribute value. E.g.:

```
<s>The <glossed_text gloss = "In fact, the dog chased his tail'>dog chased</glossed> the stick.</s>
```

With long glosses, that would seem a bit messy (i.e. make the XML difficult to read without transformation). Anther way would be to associate ids:

```
<s>The <glossed_text id = "1">dog chased</glossed> the stick.</s>
<gloss id="1" type = "clarification">In fact, the dog chased the stick.</gloss>
```

Anyway, I see some of the tradeoffs, and imagine that it can in principle be done either way. But I am interested in recommendations, so that I don't regret life decisions down the road.

**Comment by djbpitt** [comment]
@pickettj Keeping the glosses in line, instead of using `@id` associations, is more robust because you don’t have to think about which annotation goes with which textual snippet; the markup does the association automatically without cross-reference values. This protects you from mistyping the cross-reference value. The only limitation to specifying the gloss as an attribute value is that attribute values cannot contain markup, so if you need to include markup inside a gloss, you’ll need a different strategy. You could, for example, use child elements, along the lines of:

```xml
<s>The <glossed>
        <target>dog chased</target>
        <gloss>In fact, the <animal>dog</animal> chased his tail</gloss>
    </glossed>
the stick.</s>
```

By the way, if you do use cross-reference values:

1. Use `@xml:id`  instead of `@id` in your XML. It’s more idiomatic. But use `@id` in XHTML.
2. `@xml:id` and `@id` values cannot begin with digits, although they can contain digits. You can fix this by just prepending a letter, e.g., `g1` instead of `1`. (The restriction with `@xml:id` is a little more complicated than the way I’ve just described it because it’s tied up with schema validation, but the short version is that you don’t want your values to begin with digits.)
3. `@xml:id` and `@id` values have to be unique in a document, so you can’t use the same combination of attribute name and value twice. The easiest way to manage this is to use `@xml:id` for the thing you want to point to (the thing the gloss explains) and use an attribute like `@ref` to point to it. That might look like:

```xml
<s>The <glossed xml:id="g1">dog chased</glossed> the stick.</s>
<gloss ref="g1" type="clarification">In fact, the dog chased the stick.</gloss>
```

**Comment by pickettj** [comment]
Thank you! Cross-referenced ids seems like a big pain for this purpose; I'll use the nested solution, as you suggest.

```
<s>The <glossed>
        <target>dog chased</target>
        <gloss>In fact, the <animal>dog</animal> chased his tail</gloss>
    </glossed>
the stick.</s>
```

Is the `<target>` element strictly necessary? Couldn't the glossed text simply be everything in the `<glossed>` element not within the `<gloss>` nested element?

**Comment by djbpitt** [comment]
@pickettj From an information perspective you don’t need the `<target>` wrapper for the main text, since, as you write, the structural logic would be that any child of `<glossed>` other than `<gloss>` is part of the textual content. But handling mixed content (`<glossed>` contains both plain text and elements) in XSLT is sometimes trickier than handling element content (`<glossed>` contains only element children, and always the same two), and if that proves to be the case here, the extra wrapper may be able to simplify your XSLT.

**Comment by pickettj** [comment]
Thanks! That makes sense.
