### ISSUE TITLE
Spacing issue between titles

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#338]
Our page has a header that is perfectly positioned. Then we have a subtitle that is in a smaller font, but it is way below the header. Then on the same page I have the title of the book and there is a huge space between that and the sub title. It looks terrible on a laptop, it might look better on a big screen, but there shouldn't be so much space between them. Here is what we have:
` <body>
                <header>
                    <h1>Detecting Orientalism in Sherlock Holmes</h1>
                </header>
                <xsl:comment>#include virtual="../ssi/navbar.xhtml" </xsl:comment> 
                        <h2 class="title"> Orientalism in the Victorian Imagination</h2>
                <h1 id="booktitle">The Sign of the Four</h1>`
Also, in CSS I set the size of `<h1>` for each id, but it doesn't care and it doesn't get bigger or smaller no matter what I change it to. Does anyone have any ideas? Below is a screen shot of what it looks like.

 I also can't get the table of contents to be centered, nor can I get it to work, but I'm working on that. Why won't it center? We have a lot of divs. I named the div, but it just won't center. I used to have two CSS files and it worked fine, but once I merged the two CSS files it no longer centers. I feel like I should just go back to how I had it, even if its not "how things are done."
![image](https://user-images.githubusercontent.com/46850090/55689032-dd336e80-594d-11e9-8391-94f4631a9bad.png)

**Comment by zme1** [comment]
@spkellyo It looks like the generous spacing between your header elements is caused by your `padding: 25px;` property on your `div class="head" element in your booktxt.css file. When I removed that, the spacing seemed to be better on my end. Additionally, between your `div id="head"` and `div id="book title"`, you've inserted a `br` tag. That tag also includes some additional spacing which bloats the rendering a bit. For what it's worth, the structural `section` elements have some default spacing properties that we don't need to encode in HTML (just like `p` tags do). That is to say, when one `section` ends and another begins, we can let the automatic styling properties to the work of spacing the elements out, without writing `br` tags in as well.

In your `div class="toc"` element, you set a margin property of exactly 25px all around (when you don't specify left, right, top, or bottom margin, the same value is applied on all sides). When I changed that margin value from 25px to auto, it centered the table of contents to the center of my screen. Let us know if you have any more issues.

**Comment by zme1** [comment]
(All my comments here are from the code I read in your booktxt.css file.)

**Comment by spkellyo** [comment]
Gabi told me to put everything in one CSS file, which I did, but it is a hot mess. I think I will take that stuff back out and just have a booktext css file so that it looks clean. I have been messing with it all day and I couldn't fix anything,
