### ISSUE TITLE
XQuery Assignment #1 

### ISSUE THREAD

**Issue by brenda275** [obdurodon/dh_course#344]
I just started the assignment and I already encountered a problem. Do I have the right code at this point? 

`declare namespace tei="http://www.tei-c.org/ns/1.0";
collection('/db/apps/shakespeare/data')//tei:title`

My intent was for it to return all the titles and then I would further filter it later but it only returned 10 results. None of which contained:
```
<title xmlns="http://www.tei-c.org/ns/1.0">Othello, the Moor of Venice</title>
<title xmlns="http://www.tei-c.org/ns/1.0">The Second Part of King Henry the Fourth</title>
<title xmlns="http://www.tei-c.org/ns/1.0">The Taming of the Shrew</title>
```

I thought maybe my XPath expression was wrong, so I just went to http://dh.obdurodon.org/bad-hamlet.xml and hit ctrl + f to find "Othello" but no results showed up. Am I using the right text?

**Comment by MLuckman** [comment]
When I use your code, I get 378 items. These are the titles of the plays, but they also include titles you don't want (like the *Wordhound Shakespeare* or whatever the compilation name is) and acts for example. You can filter it to titles that are actually play titles by only finding titles that are descendants of `titleStmt` (at least one method).

I have no idea why you only got ten items, but try copy-pasting that code you posted here because it works when I do it.

Finally, you won't find Othello in bad-hamlet because those are two different plays.

**Comment by djbpitt** [comment]
@brenda275 @MLuckman eXide returns 378 items, as Mitchell reports, and you can see that in the little popup that appears near the bottom right that says “Query returned 378 item(s) in ...”. But it only shows 10 at a time. If your output window is wide enough, you’ll see double black left-pointing triangles at the upper left of the results panel and right-pointing ones at the upper right, and you can click on those to page through the results 10 at a time. But nobody does that; typically you filter the results (along the lines Mitchell suggests) to trim the results down to what you want.

If you want to see them all without having to page through 10 at a time, you can wrap the results in something that will cause them to look like just one result that happens to have 378 inner pieces. Since eXide paginates only the top level of the return, it will see only one item and return all of it. The following code (which we’ll examine in class on Wednesday) does that:

```xquery
declare namespace tei="http://www.tei-c.org/ns/1.0"; 
<ul>{
    collection('/db/apps/shakespeare/data')//tei:title ! <li>{.}</li>
}</ul> 
```
Here we’re returning just one item, a `<ul>` element, which happens to wind up with 378 `<li>` children, so we’ve tricked eXide into showing us what we want all at once. You can read about the XPath _simple map operator_ (the exclamation mark) in §4.3 of <http://dh.obdurodon.org/xslt3.xhtml>.
