### ISSUE TITLE
Why Won't This Work?

### ISSUE THREAD

**Issue by Ethandaniel47** [obdurodon/dh_course#347]
I don't understand why the code i'm using here wont return the count i'm looking for. It returns an error message saying that I cannot have <count()> and that I should replace that with something else???
collection('/db/apps/shakespeare/data')//tei:speaker[count() gt 40]

**Comment by khuber116** [comment]
I also ran into issues at this step and while I didn't get the results I wanted I think that the `count()` needs to include the `tei:speaker` as in `count(tei:speaker)` for it to return what you're looking for. I could be wrong.

**Comment by Guifindor** [comment]
First off, I must mention that your XPATH as is will return all speakers in all plays. This is not what you want.

Moving on to the question at hand, you need to have something in your count function for it to work. Like Kyle mentioned, you'll want the speaker in the count function. However, this also means you need to apply your filter at a level higher than the speaker element for it to work. The homework description mentions the root TEI element, so I would start with that.

**Comment by djbpitt** [comment]
@Ethandaniel47 You can see how we did this in our posted solution. As @Guifindor writes, you need to apply the filter in the right place. For example, if you can get the titles of all plays, you need to add a predicate to filter the plays and keep only the ones with at least 40 distinct speakers, and then get the titles of just those. The rest of your XPath expression is unchanged; the difference is that you’ll be starting from just those 14 plays, instead of all 42.

Where you write:

```xquery
collection('/db/apps/shakespeare/data')//tei:speaker[count() gt 40]
```

you start with the collection (so far, so good) and then get all of the `<speaker>` elements in the entire collection. You don’t remove duplicates, and you don’t retrieve them separately for each play, which means that you can’t tell whether a particular play has more than 40 or not. You have a syntax error because the `count()` function cannot have empty parentheses; some functions can and some can’t, which is sort of confusing, and the good news is that eXide notifies you (see the red text at the bottom of the window) of the error before you even run the expression.

You have a lot of the pieces; try stepping back from the code and trying to explain, in plain, step-by-step language, the process, and then see whether you can translate those steps into XPath path steps and predicates. You’re welcome to look at our posted solution, but when you do that, think about what each path step and each predicate contributes to the overall meaning, and how they interact.
