### ISSUE TITLE
Alternate Methods of getting rid of tags?

### ISSUE THREAD

**Issue by k-busko** [obdurodon/dh_course#348]
I used /string () in my XQuery expressions for the homework to get rid of the <title> tags for some of the questions but I was wondering if there were any other methods you guys used to get rid of the tags. I tried looking up alternate methods but a lot of them didn't seem like they were even for XQuery.

**Comment by djbpitt** [comment]
@k-busko As we mentioned in class, `string()`, `data()`, and `text()` can all return strings, but each of them operates a bit differently from the others. For what it’s worth, unless there is a compelling reason to do otherwise, my go-to way of getting the string value out of an element is the `string()` function.
