### ISSUE TITLE
XQuery vs XPath

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#350]
What the advantages are for using XQuery over XPath? I was wondering this while I was doing the homework, is the main draw that you can search the database and not have to download the xml files?

**Comment by loreese** [comment]
I've been wondering this as well since they seem to have a lot of over lap. I think that since XQuery allows you to find things through multiple documents/files, it's just a more streamline way to extract information across documents. At least that is how I'm conceptualizing it. So similar to XPath where you direct it to go into a single document and find X, XQuery allows you to find X (using XPath) across several documents.

**Comment by djbpitt** [comment]
@emmamamula You can think of XQuery as a superset of XPath. XQuery has access to all of the XPath functions, and, as we saw in the first XQuery homework, the simplest XQuery expression is just a single XPath expression. One of the main things that makes XQuery more powerful than just XPath alone is FLWOR expressions; XPath does have support for `for`, `let`, and `return`, but not for `where` or `order by`. XPath is also limited by the fact that an XPath path expression is a single line, so you can’t set up variables as easily in pure XPath as you can in XQuery. As @loreese writes, XQuery excels at working with multiple files, and while `doc()` and `collection()` are regular XPath functions (that is, you can use them in XSLT and in stand-alone XPath), they are most useful inside an XML database like eXist-db.
