### ISSUE TITLE
Distinct-values and keeping markup

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#353]
In xquery 2, I tried using distinct-values to get the distinct values, but once I do that, it becomes a string and I can't navigate from there. How do I make something distinctive but still keep it as a node I can navigate from?

My other method was to try and use ancestor to navigate up the tree, but all "Messenger" speaker elements each only have one ancestor, for example. I'm just sort of lost and two hours of work has gotten me nowhere.

**Comment by djbpitt** [comment]
@MLuckman `distinct-values()` returns *values*, rather than nodes. That is, it *atomizes* the objects it touches (= turns them from nodes into *atomic values*, which, in this case, are strings). As you note, it isn’t possible to navigate from an atomic value because it isn’t a node in the tree.

A general strategy for working around that limitation, in *pseudo-code*, is:

1. Find all of the distinct values.
2. Inside a `for` loop that loops over the distinct values ...
3. ... find all of the nodes of the correct type (e.g., `<speaker>` nodes) that are equal to the particular distinct value that you’re looking at during that pass through the loop.

`<speaker>` elements have lots of ancestors: moving up the tree they’ll hit speech, scene, act, body, text, and root. If you’re finding only one ancestor, something must be amiss with the path expression you’re using.

**Comment by MLuckman** [comment]
```xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";
let $plays := collection('/db/apps/shakespeare/data')
let $speaker := $plays//tei:TEI/distinct-values(descendant::tei:speaker)
let $snode :=$plays//tei:TEI//tei:speaker
for $speaker in $plays
where $speaker = $snode/string(.)
return $snode```

This isn't close to complete but I'm having trouble progressing. Exide gives me a warning on line 4 that $speaker is an unused variable - but I'm at least *trying* to use and don't know why it's saying it's unused.

**Comment by Ethandaniel47** [comment]
i think you're using "speaker" as a variable in two different cases, one in the way in which we used $play in class, and one wherein its a variable for the speaker elements. These two uses arent the same, and it seems likely that thats why its giving you an issue? maybe change the for $speaker to something like for $play like we used in class? Maybe?? I haven't figured the assignment myself.

**Comment by MLuckman** [comment]
When I do that though, $play just becomes an unused variable. I don't understand how to do a `for` clause and a `let` clause because I end up with an unused variable error no matter the permutations I've tried.

**Comment by gabikeane** [comment]
when you use `for` you are creating a new variable. The construction is a bit confusing but basically, you say "Call $speaker the sequence of things contained in my existing variable $plays". It's a way to define a new variable iteratively, not use an existing variable to do something.

This is good, because it means if we have 41 plays we can do something 41 times very quickly and easily. However, in what you've written, you're writing over $speaker in your for loop in the process of doing that.

**Comment by MLuckman** [comment]
But even when I define a new variable, as in the below attempt it's still counted as unused, as in plays here - and it also doesn't loop over the "distinct values" like Dr. Birnbaum suggested in the first response, and I don't know how to choose what it loops over.

```xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";
let $plays := collection
let $s := $plays//tei:TEI/distinct-values(descendant::tei:speaker)
let $a := $plays//tei:TEI[descendant::tei:speaker=$s]//tei:titleStmt/tei:title/string()
for $play in $plays
return count($a)```

**Comment by gabikeane** [comment]
You're getting closer to an answer, I think. What does this output, and what is the error?

**Comment by MLuckman** [comment]
Unfortunately, I don't think that's the case, because this (once I put in the collection description which I accidentally deleted in the comment) just returns "37" 42 times (and takes an impossibly long time to run). I can also make it give me a list of titles that include speaker elements, or a list of distinct speakers, but progress beyond that is proving difficult.

It claims that $play is an unused variable. Actually, now it's just claiming everything is unused and it's taking a really, really long time to send anything back to me - is the site down again?

**Comment by gabikeane** [comment]
Yes, it would seem so. Give us a minute...

**Comment by djbpitt** [comment]
@MLuckman @gabikeane eXist is up. It may be slow because everyone is accessing it at once, especially if people are starting their paths with slashes, that is, forcing it too look at every file in the entire database, and not just the Shakespeare plays.

Meanwhile, let’s look at:

```xquery
declare namespace tei="http://www.tei-c.org/ns/1.0";
let $plays := collection
let $s := $plays//tei:TEI/distinct-values(descendant::tei:speaker)
let $a := $plays//tei:TEI[descendant::tei:speaker=$s]//tei:titleStmt/tei:title/string()
for $play in $plays
return count($a)
```
The second line is wrong because it doesn’t specify the collection. You need `collection('/db/apps/shakespeare/data')`.

Calling your variables things like `$s` and `$a` is asking for trouble. You’ll have forgotten what they mean in a few days, and other people who read your code (like ... er ... people on this list) have to puzzle out what you mean. Use meaningful variable names.

With that said, your `$s` variable gets the distinct values of the speaker names *in each play separately*, which isn’t what you want. That’s because you don’t invoke `distinct-values()` until after you have already separated the plays with the path step that reads `tei:TEI`. Since each path step becomes the current context for the next one, you’re saying “find each play and then, separately for each play, get me the distinct speaker names”. This isn’t what you want because, for example, it will return `Messenger` separately for each play that has a speaker with that name. Wrap your `distinct-values()` around the whole expressions instead; don’t invoke it separately for each play.

Your `$a` variable finds all plays that have any speaker equal to any value in `$s`. This finds all plays because all plays have at least one speaker who appears in `$s`, since `$s` contains all speakers in all plays (some of them repeated). So get rid of this line. What you want to do instead is loop over the distinct speaker names and check how many plays each of them appears in. In other words, don’t loop over plays; loop over distinct speaker names, and for each speaker name, count the plays that include that speaker name. 

We’ll stop here for now, but we hope this will get you reoriented.
