### ISSUE TITLE
Problem with eXist loading

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#354]
Every time I try to go on to http://obdurodon.org:8080/ , I get a message that says "This site can't be reached. obdurodon.org refused to connect. 

Not sure if maybe this is just a high volume time? I'll try again in a few hours.. but it hasn't worked for me the last few times I've tried to get on the site.

**Comment by rmf96** [comment]
I also didn't have this problem accessing it on Monday/Tuesday to do the 1st XQuery assignment.

**Comment by djbpitt** [comment]
@rmf96 Someone crashed eXist and didn’t tell me. When I saw your message, I restarted it. 

**Everyone:** if eXist return the error message that @rmf96 reports above while you’re using it, you need to tell me so that I can restart it. It happens, and it isn’t a big deal ... unless you don’t report it, in which case your classmates can’t do their work!

**Comment by ddaud02** [comment]
@djbpitt eXide was very slow all afternoon and the evening too.

**Comment by ddaud02** [comment]
This is what I have done so far:

This code doesn't work yet, but instead of looking at all <speakers> within each <play>, I am trying to look at all plays for each speaker. In other words, instead of "play >> speaker" I am trying to do "speaker >> play":

xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";
let $plays := collection('/db/apps/shakespeare/data')
let $speakers := distinct-values($plays//tei:speaker)
for $speaker in $speakers
let $count1 := $plays//tei:TEI/count($speaker)
where $count1 gt 40
return $count1
