### ISSUE TITLE
SVG Exam 

### ISSUE THREAD

**Issue by Ethandaniel47** [obdurodon/dh_course#357]
I'm working on the SVG Exam at the moment and I am having trouble getting the code to return any "y" values for the rectangles. They appear either as `y="-"` or `y=""` despite my using the same pattern for inputting y values we have used on previous assignments using set variables. I am also running into the problem where my code returns nine rectangles for each `<pasta>` value instead of nine rectangles altogether - one for each pasta. I assume this has something to do with the value I'm inputing when I start my second xsl:variable? This occurs when I have it set to select "pasta" however if I change it to "pasta_poll_results" it returns no rectangles whatsoever. 

`       <xsl:template match="pasta">
        <xsl:variable name="xPosition" select="(position() - 1) * 30"/>
        <xsl:variable name="totalVotes" select="sum(pasta)"/>
        <xsl:variable name="AngelVotes" select="pasta[@type='angel_hair']"/>
        <xsl:variable name="ElbowVotes" select="pasta[@type='elbow_macaroni']"/>
        <xsl:variable name="FarfalleVotes" select="pasta[@type='farfalle']"/>
        <xsl:variable name="FettuccineVotes" select="pasta[@type='fettuccine']"/>
        <xsl:variable name="FusilliVotes" select="pasta[@type='fusilli']"/>
        <xsl:variable name="LinguineVotes" select="pasta[@type='linguine']"/>
        <xsl:variable name="PenneVotes" select="pasta[@type='penne']"/>
        <xsl:variable name="RigatoniVotes" select="pasta[@type='rigatoni']"/>
        <xsl:variable name="SpaghettiVotes" select="pasta[@type='spaghetti']"/>
        <xsl:variable name="angelPer" select="$AngelVotes div $totalVotes"/>
        <xsl:variable name="elbowPer" select="$ElbowVotes div $totalVotes"/>
        <xsl:variable name="farPer" select=" $FarfalleVotes div $totalVotes"/>
        <xsl:variable name="fetPer" select="$FettuccineVotes div $totalVotes"/>
        <xsl:variable name="fusPer" select="$FusilliVotes div $totalVotes"/>
        <xsl:variable name="lingPer" select="$LinguineVotes div $totalVotes"/>
        <xsl:variable name="pennePer" select="$PenneVotes div $totalVotes"/>
        <xsl:variable name="rigPer" select="$RigatoniVotes div $totalVotes"/>
        <xsl:variable name="spagPer" select="$SpaghettiVotes div $totalVotes"/>
        <xsl:variable name="acro" select="@type"/>
        
       ` <rect x="{$xPosition + 22}" y="-{$angelPer * 300}" stroke="black" stroke-width=".5" fill="red" width="20" height="{$angelPer * 300}"/>
        <rect x="{$xPosition+22}" y="-{$elbowPer * 300}" stroke="black" stroke-width=".5" fill="orange" width="20" height="{$elbowPer*300}"/>
        <rect x="{$xPosition+22}" y="-{$farPer * 300}" stroke="black" stroke-width=".5" fill="yellow" width="20" height="{$farPer*300}"/>
        <rect x="{$xPosition+22}" y="-{$fetPer * 300}" stroke="black" stroke-width=".5" fill="green" width="20" height="{$fetPer*300}"/>
        <rect x="{$xPosition+22}" y="-{$fusPer * 300}" stroke="black" stroke-width=".5" fill="cyan" width="20" height="{$fusPer*300}"/>
        <rect x="{$xPosition+22}" y="-{$lingPer * 300}" stroke="black" stroke-width=".5" fill="blue" width="20" height="{$lingPer*300}"/>
        <rect x="{$xPosition+22}" y="-{$pennePer * 300}" stroke="black" stroke-width=".5" fill="purple" width="20" height="{$pennePer*300}"/>
        <rect x="{$xPosition+22}" y="-{$rigPer * 300}" stroke="black" stroke-width=".5" fill="black" width="20" height="{$rigPer*300}"/>
        <rect x="{$xPosition+22}" y="-{$spagPer * 300}" stroke="black" stroke-width=".5" fill="white" width="20" height="{$spagPer*300}"/>
        
        <text x="{$xPosition + 20 div 2 + 22}" y="20" text-anchor="middle">
            <xsl:value-of select="$acro"/>
        </text>
    </xsl:template>                         `

**Comment by djbpitt** [comment]
@Ethandaniel47 If for each pasta you are getting a new set of rectangles for *all* pastas (so that you get 9 * 9 instead of 9 * 1 results), you’re probably applying templates to *all* pastas repeatedly, instead of to *one pasta at a time*. Check for spurious paths like `//pasta` where you mean `pasta` (no leading double slash) or something similar.

If you are getting empty `@y` values (and, I’m guessing, also `@height` values, since the XPath expressions are the same), that may be because your arithmetic isn’t working the say you think it is. Strip back your XSLT (or create a new one) to output each step in your arithmetic process: your expression that sets $AngelVotes, then the one that uses that to set `@angelPer`, then the one that uses that to set `@y`. You won’t be creating SVG that can be rendered, but you can look at the values in the angle-bracketed output and see whether you are getting what you expect. This is why we write one step at a time and check the results before writing the next one. It’s easier to catch mistakes as they happen than to write a bunch of code that doesn’t work and then try to hunt backwards through it for the mistake.

A template that matches `pasta` looks for things on the child axis of the `<pasta>` element that it’s processing at the moment. That means that inside a template that matches `<pasta>`, a statement like `<xsl:variable name="AngelVotes" select="pasta[@type='angel_hair']"/>` will look for a child `<pasta>` element of the `<pasta>` element that you’re processing at the moment. Since `<pasta>` elements don’t have `<pasta>` children, it won’t find any.

**Comment by Ethandaniel47** [comment]
So I've tried to start by creating a single rectangle using variables set for a single <pasta> type in a separate XSL doc, but now instead of creating 81 rectangles, I am returning none whatsoever. The output doesn't even have a <rect> element in the code. When I first changed the <//pasta> in xsl:apply-templates to just <pasta> on my original doc it returned nine rectangles - still without y values - but now that document too returns no rectangles. 

`<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/2000/svg"
    exclude-result-prefixes="#all"
    version="3.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <svg height="375">
            <g transform="translate(30, 330)">
                <line x1="20" x2="20" y1="0" y2="-320" stroke="black" stroke-width="1"/>
                <line x1="20" x2="550" y1="0" y2="0" stroke="black" stroke-width="1"/>
                <line x1="20" x2="550" y1="-150" y2="-150" stroke="black" opacity="0.5"
                    stroke-dasharray="8 4" stroke-width="1"/>
                <text x="10" y="5" text-anchor="end">0%</text>
                <text x="10" y="-145" text-anchor="end">50%</text>
                <text x="10" y="-295" text-anchor="end">100%</text>
                <xsl:apply-templates select="pasta"/>
            </g>
        </svg>
    </xsl:template>
    <xsl:template match="pasta">
        <xsl:variable name="xPosition" select="(position() - 1) * 30"/>
        <xsl:variable name="totalVotes" select="sum(pasta)"/>
        <xsl:variable name="AngelVotes" select="pasta[@type='angel_hair']"/>
        <xsl:variable name="angelPer" select="$AngelVotes div $totalVotes"/>
        <xsl:variable name="y" select="$angelPer*300"/>`
        
       ` <rect x="{$xPosition + 22}" y="-{$y}" stroke="black" stroke-width=".5" fill="red" width="20" height="{$y}"/>`

`</xsl:template>
</xsl:stylesheet`

**Comment by djbpitt** [comment]
@Ethandaniel47 With reference to the code above:

1. Inside your template that matches the document node you apply templates to `<pasta>` elements on the child axis. The document node doesn’t have any `<pasta>` children, so it isn’t finding them.
1. Inside your template that matches `<pasta>` elements you set variables (`$totalVotes`, `$AngelVotes`) that refer to the `<pasta>` children of those `<pasta>` elements. Since `<pasta>` elements don’t have `<pasta>` children, the code won’t find anything there.

Each template matches something (document node, a specific `<pasta>` element) and XPath path expressions inside the template are relative to the thing that got matched, which is called the *current context*. Scrutinize what you are matching in each template and the XPath path expressions you invoke inside those templates to make sure that you are navigating from where you think you are navigating from, and navigating to where you think you’re navigating to.
