### ISSUE TITLE
Integers in xpath

### ISSUE THREAD

**Issue by gmd29** [obdurodon/dh_course#36]
What did everyone do about the "1" in the path expression on the homework. It does not allow integers and I wasn't sure what to do. (I can't remember if we mentioned this in class or not.

**Comment by djbpitt** [comment]
Are you accidentally misreading an "l" (lower-case "L") as the digit "1" in http://dh.obdurodon.org/xpath-assignment01.html, question 2a? Stand-alone digits aren’t allowed in path expressions in places where element names are expected because XML element names are not allowed to begin with a digit. That is, it’s essentially an XML well-formedness constraint, rather than an XPath issue. Does this help?
