### ISSUE TITLE
Presentation ideas

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#360]
How do people generally intend to structure the presentation, and do people plan to create a powerpoint/other presentation aid or just use their website for the visuals?

**Comment by djbpitt** [comment]
@MLuckman I’ve seen lots of different approaches. It’s important to cover the research focus, so the presentation shouldn’t just be a tech demo, but insofar as the technology is there to enable the research, the technology is typically an important part of what there is to say. With only 8 minutes, switching between PowerPoint and live, interactive browser access to the project site can sometimes cause stumbling or confusion, so although it’s reasonable to use both PowerPoint and a browser, you might consider as alternatives just PowerPoint (using static screen shot images from the site) or just a live site walkthrough (where the research perspective and discussion are in your narration, and not on slides).

If you find tag-team presentations, where each person speaks for a few minutes before passing the proverbial baton, distracting, it’s find to have one person speak on behalf of the team. Alternatively, there’s nothing inherently wrong with having everyone speak, but in that case I’d suggest rehearsing the hand-offs, so that they go smoothly. I’d also suggest thinking ahead of time about who will *drive*, that is, manage the keyboard and mouse. For simple things like PowerPoint slides the speaker might be able to do it, but as the interactions become more complex, it may be smoother to do what we do in class, and put one person in charge of the display while someone else speaks.
