### ISSUE TITLE
Centering drop down bar

### ISSUE THREAD

**Issue by k-busko** [obdurodon/dh_course#362]
We found that with our website, the drop down bar stays centered on the homepage but whenever we click on an icon on the drop down menu, taking us to a different page, the entire drop down bar shifts to the left side of the screen. This is the case for any of the pages we click that are not the homepage. Is anyone else having this problem/ how did you fix this if you did?

**Comment by Guifindor** [comment]
Forgive me if I'm missing something since neither me nor anyone in my group has done a drop down menu, but I will try offering some advice.

Have you tried opening the pages directly, instead of navigating to them from the homepage? If you get the same issue despite not having gone to the home screen, something is wrong with your underlying HTML/CSS (or JavaScript if it's done solely through JavaScript). If it only happens when you navigate to it using the links on the homepage, this tells me the transition is causing a change to some value that's responsible for rendering it (though I have no idea what would cause this particular issue). Nonetheless, examine your code that's responsible for keeping it centered, and ask yourself what causes it to work on the homepage. Then see if anything is different about these factors when looking at your other pages. This is one method I employ for "It works in this situation/location, but not this one" troubleshooting.

**Comment by djbpitt** [comment]
@k-busko Your project team should have been advised to use server side includes (SSI) for your menu, which would help ensure that it behaves the same way everywhere. Because you seem to have copied the raw HTML from file to file instead of using SSI, there’s a greater risk of inconsistency. You can remind yourself about SSIs at <http://dh.obdurodon.org/ssi.xhtml>, and if you need help implementing them, write to the instructors and we’ll be happy to meet with you.

When you get different behavior unexpectedly, you need to look at what’s different in the files. Is the HTML for the menu (including everything around it: its parent, etc.) the same? Are the files linked to and using exactly the same CSS? For example, I notice that your *index.xhtml* file includes a line that reads `<div id="Menu" class="menu">`, but _Methodology.xhtml_ has `<div id="Menu">` (without the `@class` attribute). Is there styling that you’re applying differently in your CSS according to the value (or absence) of the `@class` attribute? If so, that could explain the difference in behavior.
