### ISSUE TITLE
CCS in a SSI

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#366]
![image](https://user-images.githubusercontent.com/46380238/56481044-f1698680-648a-11e9-9527-b9a5ff003886.png)

**Comment by djbpitt** [comment]
@ddaud02 A selector like `.hasBackground span.AdjMalePos` applies to all instances of `<span class="AdjMalePos">` that are descendants of any element that has a `@class` value of `hasBackground`. The difference between having a space between the two parts of the selector, as in this example, and having a `>` is that the space means “descendant” and the `>` means "child". Whether the CSS is inside an SSI or hard-coded into the HTML can’t make a difference because the CSS is applied only in the browser, and by the time the HTML gets to the browser, SSIs have been processed and the browser cannot know whether the CSS came from an SSI or was part of the HTML originally.

If the preceding doesn’t help, email me to set up an appointment for us to look at it together today.
