### ISSUE TITLE
Project Proposal - The Song of Songs

### ISSUE THREAD

**Issue by EsRessel** [obdurodon/dh_course#393]
## Introduction and About the Text
This project will focus on the *Song of Songs*. This text is the first of five megillot (scrolls) in the Ketuvim (writings), the last part of the Tanakh (Hebrew Bible). The subject matter of the writing is the celebration of sexual love. It highlights the voices of two lovers (in this case a man and a woman) and also features observers to their love, including a chorus of the women of Jerusalem. The text is interpreted differently across cultures. Jewish tradition interprets it as an allegory of the relationship between God and the people of Israel, while the Christian tradition interprets it as an allegory of the relationship between Jesus Christ and the Church.

The translation that I plan to use is from *The Holy Scriptures According to the Masoretic Text*    
(pp. 966-972), published by the Jewish Publication Society (JPS) in 1917. This publication can be found in the public domain at [this site](https://opensiddur.org/readings-and-sourcetexts/mekorot/tanakh/translations/tanakh-the-holy-scriptures-a-new-translation-jps-1917/) and includes a downloadable .txt file. JPS publications are among the most authoritative and preferred English translations of Hebrew scriptures. 

## Research Question
I intend to explore gender roles in the *Song of Songs*, ultimately moving toward an answer to the question: 
1. What gender roles does the *Song of Songs* perpetuate and 
2. How are these roles manifested in the allegories utilized by the different cultural traditions that read the text?

## Approach
I plan to primarily examine the dialogue between the characters in the text. 

I will track:
* the number of times the woman speaks
* the number of times the man speaks
* the number of times each is spoken to or about

I will also track and asses:
* adjectives and their connotations
* verbs
  * whether the verb is passive or active
  * the connotation of the verb

The use of the adjectives and verbs will be put into context in each applicable verse by associating each with the character who has performed the action, had the action performed on them, and to which character the adjective refers.

**Comment by sjw82** [comment]
@EsRessel Great use of markdown here! And excellent proposal! You've thought this out extensively and brought to the table a very thorough write up. Plus, you're working on the Jewish literature which, as I mentioned, I also focused on for my project, though I used the Midrash, so definite brownie points.
I just have a few questions about your approach:
1. How does the frequency of speech correlate to gender roles? I'm not asking because I believe it doesn't, I'm just asking to clarify. The way I'm imagining it, the role it would most indicate is the subservience of women but perhaps not gender roles more broadly.
2. Would you track adjectives and verbs only in the dialogue or in the whole text? If it is the latter, you're likely going to have to focus on a smaller corpus. If the prior, can you make an argument for the word choices someone makes indicating something about their gender role conformity? Again, not to say you can't, just to say that it might be necessary.

Overall, this is some fantastic legwork on your project.
