### ISSUE TITLE
Project Proposal: Don Quixote 

### ISSUE THREAD

**Issue by cjw102** [obdurodon/dh_course#403]
## Introduction
*El ingenioso hidalgo Don Quixote de la Mancha* by Miguel de Cervantes is one of the most notable works of literature from the “Spanish Golden Age”, published in two parts during the early 17th century. The book tells the story of Alonso Quixano, a man who becomes infatuated with "chivalric romances" and eventually treks on a journey to save his nation as a knight. One of the more distinctive attributes of the text is its use of Old Castillian, a derivative of Latin spoken in the Iberian Peninsula from the 10th century to the early 15th century. This may also hint at the protagonist’s fascination with the medieval ages, a recurring theme throughout the novel. Since its initial publication, Don Quixote has been translated into numerous languages, with some speculating it is only second to the bible in terms of being the most translated book in history. 

## Question
My research question involves trying to uncover the specific ways in which the Old Castilian in Don Quixote has been adapted into other languages, namely English. In lieu of the Old Castilian used in the original Spanish novel, the English text presumably an “older” form of English to emulate the medieval fascinations of the protagonist. However, as with many translations, meaning and style can be contorted when switching from one language to another due to linguistic nuances. I would like to study how the syntax differs between the Spanish and English versions, and how this affects the overall tone and mood of the progression of the story. Below are links for both the English and Spanish versions for publicly available text of the story:

English: http://www.gutenberg.org/files/996/996-h/996-h.htm
Spanish: http://www.gutenberg.org/files/2000/2000-h/2000-h.htm#1_x

## Approach
To begin the research project, I would have to tag specific portions of the text in Old Castilian and their corresponding English texts. I would then mark up certain attributes pertaining to the syntactic structures of both. Additionally, I will want to pay specific attention to descriptive words in the text and how they contribute to the meaning and feel of it as a whole.

**Comment by setriplette** [comment]
Hi! My name is Stacey Triplette, and I'm a professor at Pitt Greensburg. Elisa Beshero Bondar asked me to leave a comment because I happen to be a Quixote scholar.

A couple of things to make your proposal stronger:

1. Don Quixote isn't in Old Castilian (do you mean medieval Spanish / español medieval?). It is definitely not in vulgar Latin! 

Don Quixote is classified as modern (1605 and 1615 for the two parts). You could describe it as seventeenth-century Spanish or early modern Spanish but there's only a few quirks that are different from the Spanish we speak today. There's a future subjunctive and the formal future has a split conjugation (instead of os llamaré, llamar os he). There's also vos and Vuestra Merced used as subject pronouns. There are also some spellings that would be a little different. On the whole though it is mutually intelligible with twenty-first century Spanish. Any good critical edition (I use the Cátedra and the Castalia ones) will point all of these features in footnotes. There are also some "linguistic archaisms" in Don Quixote that would sound more medieval; Howard Mancing's book <i>The Chivalric World of Don Quixote</i> has a chapter on them which includes a chart.

2. Is the English translation that project Gutenberg happens to have (Ormsby 1885) interesting in any way? What approach did it take? The most famous translation is the Thomas Shelton translation of Part I (1612)--one of the first translations of anything from Spanish to English. Other good ones are the recent Edith Grossman and Tom Lathrop. Grossman goes for readability and Lathrop for scholarly accuracy. The Ormsby is convenient, but before working with it, it might be good to read about it and try to figure out the translator's approach. There are reasons to be more and less exact in a translation. Wikipedia describes the Ormsby as scholarly, but there are probably better sources to describe it more fully. Your project is likely to tell you more about how the Ormsby translation works than how compatible early modern Spanish and English are. From my experience of working with translations, English and Spanish are similar enough that a very exact translation can be made. The translator does not always do this, for reasons of art, ignorance, politics, or taste.

3. You're right that Don Quixote the character is fascinated with a phenomenon from the past, in the case the romances of chivalry (books about knights and ladies). Romances of chivalry are associated with the Middle Ages in France, but in Spain, they did not become popular until much later. Don Quixote's obsession, Amadís de Gaula, is from 1508, and the other books in the character's library are all from the sixteenth century and are thus not medieval. (The end date for the Middle Ages in Spain is often said to be 1492--it's a date of convenience but it will work for your purposes). There's nothing medieval about the Quixote. Cervantes is describing a person who is imagining himself living in his grandfather's era; still in the early modern / Renaissance period, but the turn of the sixteenth century rather than the seventeenth.

I hope this makes sense! If you end up working on this project, I'm happy to answer questions on anything Cervantes.
