### ISSUE TITLE
Reflection Post: GitHub

### ISSUE THREAD

**Issue by cjw102** [obdurodon/dh_course#416]
Although I still have very limited experience with using GitHub and still have much more to learn in terms of using all the features, I have come to better understand GitHub a bit more since I first began using it. One of the more interesting aspects of GitHub is the use of Pull requests. I think this is a very interesting way to update data on a project as well as collaborate with others, even if the process is a bit complicated and hard to perform sometimes. This is a feature that I would like to learn more about, and specifically why this particular method was used to foster collaboration. Typically, I am used to collaboration on projects with programs such as Google Docs or OneNote, which allow people to update the same project online in real time. This was convenient because you could see the changes as they occurred and know what was update, which is more difficult to do in GitHub. I wonder, for example, if two people download a version of the Git project at the same time and work together to make changes, how can the changes all be properly merged? Overall though, I think that pull requests will be very helpful in allowing our group to collaborate, even when we are not together.

**Comment by djbpitt** [comment]
With Git it’s possible for two developers to commit changes to the same file at the same time, and as long as they’re on different lines, Git can normally merge them. If you try to merge two versions with line-level differences, Git generates a report about a *merge conflict*. These happen from time to time and they’re fixable, but they’re best avoided, typically by pulling and pushing often, so that teammates integrate one another’s changes before conflicts arise.
