### ISSUE TITLE
<div> positioning

### ISSUE THREAD

**Issue by danakaufhold** [obdurodon/dh_course#42]
A roadblock that I ran into this morning while creating more pages for our site is the problem of positioning two divs next to each other. For some reason, even though I've coded each with the exact same code except for left/right positioning, one shows up at the bottom of the page instead of next to the other one. (I hope this makes sense?) You can see what I mean [here](alice-jpn.obdurodon.org/text.xhtml). Anyone have any clues as to why this is happening, or how to fix it?

**Comment by djbpitt** [comment]
For anyone else reading this, the link to the sample is <http://alice-jpn.obdurodon.org/text.xhtml> (you accidentally omitted the "x" in "xhtml" in your link above).

`<div>` elements have a default CSS `display` property value of "block", which means that they are rendered after the preceding block and before the following block vertically. There are two main ways to fix this:

1. The better way (because it’s a more capable and useful technology in general) is to manage the layout with CSS flexbox technology. The tutorial that we used to learn about flexbox is pretty accessible to new users: <https://css-tricks.com/snippets/css/a-guide-to-flexbox/>; we’d suggest starting with that, and post an inquiry here should you get stuck.
1. The quick-and-dirty way (what we used to do before the advent of flexbox) is to set explicit `display` property values of "inline-block" for your English and Japanese `<div>` elements. You can read about the "inline-block" property value at <https://www.w3schools.com/css/css_inline-block.asp>, and there’s a comprehensive list of valid `display` property values at <https://www.w3schools.com/cssref/pr_class_display.asp>.

You can also control the placement through the `position` and `float` properties, but we’d strongly recommend using flexbox instead (which is also what we do on our new pages, although we have some old ones lingering around that use these older, less capable methods).

**Comment by Idi0teque** [comment]
Okay, that's actually really good to know! We hadn't yet run into that issue in our project but I had placed two divs next to each other in one of our marked-up stories, and should something go wrong there I'll know what might be the issue. I can probably spend a little while learning Flexbox, since while on my site I did use some positioning it was very much trial-and-error.
