### ISSUE TITLE
Discussion Post on GitHub

### ISSUE THREAD

**Issue by lillianforrest820** [obdurodon/dh_course#421]
I have a better understanding of GitHub now that I have begun working with it for my project. While I am more familiar with it, I definitely do not understand every aspect. For instance, I still don't quite understand what a 'Pull Request' is. I think the most useful feature of GitHub for my project team is its ability to facilitate collaboration. GitHub makes communication and collaboration very easy which I appreciate. Even though we have only had our project teams for about a week, my team has already begun using GitHub as a platform to communicate different ideas. I think that we will continue to use GitHub as the center for all of our collaboration for the remainder of this project.

**Comment by djbpitt** [comment]
Pull requests are part of *code review*. The idea is that instead of pushing directly to the master branch, you issue a *pull request*, which is a proposal to integrate changes into master. A teammate can then review your code and either execute the merge (that is, accept the request) or reject it with comments. We don’t typically use pull requests much in course projects, but we do in professional development, so once you have the Git basics down, feel free to experiment. You can, in principle, accept your own pull request, although that would be odd in Real Life, since a big part of the point is to get a second pair of eyes to review the proposed changes before merging them into master.
