### ISSUE TITLE
Class discussion post Feb. 26

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#43]
Has anyone found any aspects of the reading assignment that sounded particularly useful?  Of course, the features that were described are probably well beyond our project but did anyone find anything to use?

**Comment by djbpitt** [comment]
@mtm80 Please tell us what _you_ found potentially useful in the reading! Ignoring for the moment whether the concepts are too complex for our little 15-week course (some are, some aren’t), which of them could enhance how _you_ imagine delivering _your_ project, and how?

**Comment by brucknerp** [comment]
I read the chapter on Process Flow (CH 8) and it talked a lot about user retention by making things as simple as possible. It was useful for me personally because while designing a site it's easy to assume that the use will be present for all the steps, but forget that most people decide within 5 sec whether they will stay on the page or not (me too). So less about a specific feature or high level coding, I focused more on making sure that our site has the easiest process flow possible when accessing our data/writeup/etc.

**Comment by enb34** [comment]
I found the chapter on direct selection to be particularly insightful, especially when dealing with interacting with a text. Our project will likely be displaying versions of the _Alice_ text on our site, and the chapter was able to give me some ideas on how to display certain features of the text that we're tracking and making those features interactive to a viewer.
