### ISSUE TITLE
Discussion Post: Images and Copyright

### ISSUE THREAD

**Issue by charlietaylor98** [obdurodon/dh_course#430]
As we've begun learning HTML, CSS and web design, I've noticed that although we're marking up documents, our group is dealing with something highly visual in character. We'll probably want to add images of van Gogh's paintings to our final website, and I'm sure many of you will want to use images as well. Luckily, [artstor,](https://library.artstor.org/#/browse/library) which is partnered with jstor and which all Pitt students have access to, provides images from from museums (not just art galleries, but anthropological and modern history museums as well) around the world, free for use in "noncommercial educational and scholarly activities." Just wanted to put this resource out there!

**Comment by Islam-M-Farag** [comment]
Thank you for sharing this website. I checked it out; it is really useful and would save tons of time. 
But I still wonder about google images that has no authorship. Websites are full of such open access images without making a reference or hyperlink because the found it from google images with no authorship declaration. I wonder how developers deal with the copyright issues.
