### ISSUE TITLE
Single Issue Discussion - Orbis

### ISSUE THREAD

**Issue by EsRessel** [obdurodon/dh_course#445]
This site utilizes GIS mapping that can be used to explore travel across the Roman Empire. It provides many different toggles and configurations and does a good job of combining human-related factors such as available roads, modes of transport, and priority of travel with natural features such as season, terrain, and the physical distance between places. 

When first launching the page, I was overwhelmed by the number of options. There seemed to be a cluster of checkboxes and sliders everywhere I looked. Though the site provided a tutorial, it was difficult to navigate. Its design could be more intuitive by including buttons to navigate backward and forward through the tutorial sections. I liked that a majority of the text-based information was hidden away in the "about" tab, and could be easily accessible if needed. The "gallery" was also helpful to highlight previously simulated conditions and to give examples of ways to configure the many options of the site.

**Comment by Islam-M-Farag** [comment]
I do agree with you that it was an overwhelming  floods of information, especially when I opened the website and a tutorial popped up and it took a while to be able to navigate the features and explore the website. As you said, it could be simply designed much better than its current design.

**Comment by djbpitt** [comment]
One of the challenges in UI/UX design is identifying a *target audience*. First-time visitors to Orbis often find the site confusing, with too little documentation for so much implicit functionality. When we new visitors think it’s poorly designed, what we may mean more precisely is that it wasn’t designed in a way that optimizes the experience of new users.  Experienced users, on the other hand, might be grateful that the screen isn’t cluttered with instructions or other information that they memorized subconsciously long ago. 

The most common user for a site like this (and, perhaps, more generally) is what the UI/UX community calls the *perpetual intermediate*, that is, those who are no longer beginners, but do not seek to become experts. See the description of why this happens, quoted from Alan Cooper. at <https://blog.codinghorror.com/defending-perpetual-intermediacy/>.

E-commerce sites need to cater to beginners because they don’t want to risk losing even a single sale. Academic research sites may cater to experts because the target audience is serious researchers, who will make an investment in learning the details. But for most sites, most users will wind up in the perpetual intermediate category. How well does Orbis serve that demographic? Once you had looked through the tutorial and explored the site a bit, were you able to use it without feeling lost?
