### ISSUE TITLE
skyrim text error

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#45]
I downloaded the link and control u-ed it into oxygen and it immediately gives me an error with a message "I/O error reported by XML parser processing http://dh.obdurodon.org/test.sch: 404 Not Found for: http://dh.obdurodon.org/test.sch".  It doesn't point  to any typos or other errors.  Any ideas?

**Comment by gabikeane** [comment]
This merely means the schematron file is not where it's supposed to be.  The XML is well-formed, so you can proceed with the assignment as you planned.
@djbpitt, did something get moved that could cause this?

**Comment by djbpitt** [comment]
The error means that &lt;oXygen/&gt; is trying to validate the XML document against a Schematron file (a type of schema) called `test.sch`, which isn’t available. I’ve just edited the `skyrim.xml` file on line to change that reference, so if you close the XML file in &lt;oXygen/&gt; and then reopen it (with control+u), it should be okay this time.

What the error message means is that the XML isn’t valid against the `test.sch` Schematron schema, which is sort of misleading, because the real issue is that there isn’t any `test.sch` schema. I fixed it by changing the pointer to a different Schematron file, called `skyrim.sch`, which does exist. But, as Gabi writes, as long as the XML is well-formed (even if it isn’t valid against the declared schemas), you can still run XSLT against it.

Ask us about this in class on Friday. It’s a good opportunity to talk about the difference between well-formedness and validity. But in the short run, if you close and then reopen the file in &lt;oXygen/&gt; with the control+u keystroke combination, the error message should no longer be there. And even if the XML isn’t valid against a declared schema, as long as it’s well-formed, you can transform it with XSLT.
