### ISSUE TITLE
Homework Help

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#46]
Hey, how did people get their cells in tomorrow's homework to not contain ALL values of their attributes? For example, each name cell I make outputs "UrielSeptim hero Jauffre MartinSeptim MehrunesDagon MankarCamoran" in the same cell.

**Comment by djbpitt** [comment]
It sounds as if you may have a spurious leading `//` when you apply templates, so you’re applying templates inside the cell to _all_ of the names in the document, instead of just the one for the character you’re processing at the moment. 

Inside a template rule, the current context, the place where XPath expressions start out, is the node being processed at the moment. You can use that information to navigate to just the name (etc.) that’s relevant for that particular node, instead of all of the names in the document.
