### ISSUE TITLE
Single-issue discussion post

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#468]
For Wednesday, 04-08 we ask you to read one of two articles by Steve Ramsay: [”The hermeneutics of screwing around“](https://web.archive.org/web/20140604085234/http://www.playingwithhistory.com/wp-content/uploads/2010/04/hermeneutics.pdf) or [“In praise of pattern”](http://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1056&context=englishfacpubs). Instead of an individual response paper, this is a _single-issue discussion topic,_ which is to say that we ask you to post your comments here in response to both Steve’s article and your classmates’ comments. Postings should be comments on this issue, and not new issues.

Although the topics are different, what the essays have in common is that they explore how research methods in a digital environment may differ from research methods elsewhere in humanities scholarship. In what ways are Steve’s arguments persuasive (or not)?

**Comment by cjw102** [comment]
I read the article "In Praise of Pattern" by Stephen Ramsay.

Overall, I thought his argument of how digital humanities research has the potential to be much more ambiguous or open ended in terms its progression when compared to STEM research was very interesting. In our team-VanGogh's letters-to some extent, while doing research, I can understand Ramsay's experiences describing digital humanities work. Our project involves investigating the mental state of VanGogh through an analysis of his letters. While we do have a concrete research question, deciding what exactly to look for in each letter was definitely a challenge.

Because language pertaining to emotional states can be ambiguous at times, I felt that at times I was marking things based on my own judgement, and not necessarily be an objective measure, as one may do in STEM research. Ramsay seems to struggle with somewhat similar issues in his work at times. Specifically on pages 6 and 7 of the pdf, he admits to making a "guess", although an educated guess, on the scene changes of play Antony and Cleopatra, given how unclear scene divisions in this play were.

Furthermore, he admits to beginning he research on the works of Shakespeare without any concrete purpose in mind, instead just exploring the capabilities of technology in the humanities work. Though not necessarily in research, but in some of my humanities classes in general, I do feel like I take this more "open ended" approach of exploring the interesting portions of the text, when doing things such as writing an essay.

**Comment by EsRessel** [comment]
In "The hermeneutics of screwing around", I was most struck by Ramsay's distinction between browsing and searching and their connection to digital humanities research. To me, it seemed that Ramsay presented search as rote and mechanical, while browsing, though it can be seen as "screwing around", can lead to richer understandings of connections between topics and of a topic itself. I don't think that browsing alone if a research methodology, but rather browsing and searching are intertwined. 

After reading this piece, I see browsing as a preliminary step in research. I would use it to find topics I'm interested in and hopefully, it will lead me to something that can be explored more deeply. However, it is inefficient to browse forever and direct searching will be needed to fill in the gaps and make connections. Thus, browsing can help refine one's search. 

I resonate with Colin's point about deciding what to look for when developing our projects. Though my group also felt we had a solid research question, it was difficult to narrow down which texts we wanted to use and it took multiple iterations of markup to decide what mattered in those texts. At the start, I could articulate my search terms and keywords but I quickly learned that these were not enough. Browsing digital collections and indirectly related materials is what led us to find our texts. There are parts of Ramsay's arguments that confused me and that I found difficult to process. I'm not sure if I am entirely persuaded by his arguments, but in my few months of digital humanist research and many years as a browser on the internet, I resonate with many of his points.

**Comment by 22smaenner** [comment]
I read "Hermeneutics of Screwing Around".

Like Evan, I am intrigued by the idea of browsing as a kind of research, and I guess this is what he means by "screwing around." I never really considered it when I would think about what research is, but thinking back to all the times I have done research for essays or projects, the more I realize that I have done exactly that as part of my process. I start with a single source, and pull on that thread until something else that may seem relevant to my search is shaken out, and then I go pursue that lead. This also may happen in the form of Wikipedia rabbit holes, which happen far more often than I'd care to admit.

I am also interested in the whole idea of cataloguing sources to help hermeneutics, or interpretation. In a way, that does seem familiar to what we are doing in our projects: we take different sources, aggregate them, and analyze what we see as a commentary on their contents.

**Comment by dap167** [comment]
I accidentally read both because I assumed so. Whoops. Go me.

On this same topic of "screwing around" mentioned inside _Hermeneutics of Screwing Around_, there is a similar kind of thread inside _In Praise of Pattern_ when he applies StageGraph to Shakespearean plays. In both, Ramsay finds a kind of struggle between pure, objective research and the intrinsic subjectivity of working in the humanities. As @cjw102 and @EsRessel, it becomes difficult to determine how to mark or interpret a document at times. In a way, it's relieving that even someone vastly more experienced has this kind of trouble in the intersection between neutral observation and textual interpretation. It can't be helped. One point that I especially noted was how Ramsay argued how he went all in with StageGraph's 'flawed' analysis because "there is no level at which assumption disappears." We can only own it.

**Comment by nmcdowell00** [comment]
I read The Hermeneutics of Screwing Around; or What You Do with a Million Books. The part I found most interesting was when he talked about how modern technology has revolutionized browsing. He says that the type of access one now has with the world with the world wide web allows for much more effective browsing or "screwing around". I do not know if I find this argument persuasive because I believe that the part of the internet that the majority of people use is not tailored fro browsing. Google and other browsers are designed to give you the most specific result. It would seem that you could bounce from subject to subject and "browse" more effectively but I feel like this is an overly optimistic viewpoint. Google and others limit browsing by providing extremely specific information in as a concise a way as possible. If you were to be looking around and find a book that interests you and it references someone you dont know a simple google search will give you a blurb that gives their general information and it is unlikely that one will find something very interesting from a styleless blurb covered in text.

**Comment by lillianforrest820** [comment]
I read "The Hermeneutics of Screwing Around". I was fascinated with Ramsay's discussion of the evolution of browsing. I agree that, while it may at first be aimless, "screwing around" is a powerful research tool. Now that we have the world at our fingertips via the internet, its power is only amplified. Of course, I will admit that searching the web generally requires one to have a concept in mind to begin before searching (unlike the experience of actually wandering through bookshelves without aim) as Nate points out, but I still find it very useful. Also, as Evan discussed in his post, it was through internet surfing that we came upon the texts that are now the crux of our research. I think it is important to recognize the significance of browsing in research projects, and I am glad this piece does that. Moving forward, I will be sure to appreciate "screwing around". You never know what hidden gem of you may come upon!

**Comment by marionbriley** [comment]
I read _The Hermeneutics of Screwing Around._ First impression: the linguist in me loved the connection Ramsay made between the idea of "planting a seed" and a seminar. I never noticed the shared etymology there! Fascinating, and such a good way to begin an article on this topic! We really are set loose in academics with the best foundation professors can give us, to just screw around until we find our way. I think browsing and researching are a bit more closely intertwined than Ramsay presents them; goodness knows how often I begin by researching something specific and find myself two hours later on some random tangent that interested me--or vice versa. Very rarely am I able to do one without doing the other, at least to some degree. I like that Ramsay discusses the ever more present online dialogue between scholars presenting and comparing their different findings. I appreciate this collaboration-I don't know if there has ever before been such a complex community of people able to bring together such a wide range of resources. It's the most modern and large scale application of the Socratic method we see today.

**Comment by charlietaylor98** [comment]
In "The Hermeneutics of Screwing Around", I was most interested in Ramsay's assertion that a "screwing around" approach to research can change the way we canonize certain materials over others: "Could we imagine a world in which 'Here is an ordered list of the books you should read,' gives way to, 'Here is what I found. What did you find?'" This is particularly relevant at a time when universities are beginning to rethink their approach to introductory survey courses-- I'm thinking of how a few months ago Yale announced that it would cut its art history 101 course. The idea is that by teaching a course on all of art history, you canonize certain materials as part of a broader History of Art and dismiss others as unimportant.

Maybe screwing around can help widen our accepted Western canon, but as @nmcdowell00 pointed out, search engines organize their results (and have to do so, so as to not overwhelm us with their wealth of information). Specifically, the most popular results tend to be displayed first, herein lies the problem with screwing around: there is far more information on those items which have already on some level been accepted into a canon. If you wander into the library knowing vaguely that you are interested in Renaissance art, the wealth of information on Raphael might lead you to ignore the more obscure yet captivating Giuseppe Arcimboldo. Digital research alone, although it makes tangential and somewhat more imaginative research possible, can't cure the ills of the established canon.

**Comment by mjyb16** [comment]
In "Hermeneutics of Screwing Around", what I found most convincing was Ramsay's explanation of how the way we do research has changed. I think the "conventional search" of the humanities of the past correlates well to experimental research in the sciences, while the "screwing around" method is more akin to observational methods in the sciences (such as those used in my field, astronomy). This parallel is particularly powerful due to the coincidentally simultaneous ascendance of observational astrophysics in the light of the failure of physics experiments to find anything "interesting" due to the vast parameter space (read: too many books). This has little to do with digital humanities at first glance, but it may provide a hidden insight: the humanities, perhaps, have started to run out of "interesting" research directions, and are looking to the web for inspiration, much as physicists have increasingly turned to the night sky in search of new discoveries. @EsRessel makes a good point, however: browsing alone is not sufficient. Observations must be followed up with experiment (hopefully in a much more fruitful direction than before), and likewise, a targeted search must follow web browsing. I think Ramsay made an astute observation about the trends of research today: in an ever-expanding bath of knowledge, we do not know what we are looking for, so we must first explore; once we have found an interesting path, we follow it to its conclusion by the traditional methods of research.

**Comment by Rober-Igtm** [comment]
I read Ramsay's "Hermeneutics of Screwing Around" and was struck by how brutally honest his approach to humanities and search browsers are. Whether we are an expert on a subject or looking at it for the first time we are still forced to draw assumptions - to say to the browser "“I just
got here! How can you help me find what I’m looking for when (a) I don’t know what’s here and (b) I don’t what I’m looking for?” Ramsay approaches research in a completely honest way, and with this honesty he finds how to make it more human and more useful. With browsers, we gain the power to "browse", to accept the enormous sea of text alongside the miniscule limitations of human understanding. Browsers act as a starting point by which we can delve into research, having been given a list of texts. 
As Ramsay points out, most texts that we read are because they're 'canonical' (i.e. everyone else has read them). For example, Hamlet is widely read as it is considered a 'classic', but countless other plays, texts, and poems from the same period are merely left to the dustbins of history. As @charlietaylor98 points out, browsers use lists, and thus are far more likely to present works of/on 'canonical' texts, and not hidden gems like Giuseppe Arcimbaldo. This may be true, and effort will certainly be needed to break this mold, but the web provides the unique opportunity to browse and come across these hidden gems in a way few other media could. With forums and blogs, as Ramsay discusses, non-canonical texts can be uncovered, analyzed, and appreciated through browsers, and perhaps break the dominance of the canon.

**Comment by rasaula** [comment]
I read "The Hermeneutics of Screwing Around," and while I was also struck by Ramsay's validation of browsing as a form of research, what stuck with me most was on page four, when Ramsay discussed the value in knowing how to talk with confidence about something you have no familiarity with. This is something I do a little too regularly with essays in many of my classes, so seeing Ramsay describe it as a sort of tool instead of slacking off (which was how I always viewed it) struck me as something to really examine. Ramsay includes some wonderful quotes on the topic, and in reading them I began to see what he meant about how reading (or maybe just skimming, or maybe starting but not finishing) books and then discussing them is an invitation to community just as much as it is an invitation to knowledge. As Bayard says, there are many ways of reading a book, and interacting with the ideas of one after skimming it can lead to just as much as fully digesting the full three volumes. 

Oftentimes, I've wondered how I got a good grade on an essay after winging it. But Ramsay's ideas nudged me to start thinking about why that happens, and the answer is that I tend to know what I'm talking about more often than I let myself believe. Imposter's syndrome is very real in the academic field (and everywhere else), and what I've come to see as "winging it" very well may be a valid way of processing information, and then sharing ideas. This was a thought I found very relevant to this course, where I often feel like I'm faking it until having to explain my homework to a friend.

"Your ethical obligation is neither to read them all nor to pretend that you have read them all, but to understand each path through the vast archive as an important moment in the world’s duration—as an invitation to community, relationship, and play."
-Ramsay

**Comment by djbpitt** [comment]
I learned to conduct research in the humanities before the World Wide Web came into existence. There was an Internet by the time I was in graduate school, and I had access to it because I was at a research university, but the universal online font of all information that we use now really came into existence only with the Web, and, specifically, with the democratization of the Web. 

In those days, the searching part of research typically started with an idea for a research question, which might come from thinking about something I was reading or from thinking about a humanistic question that occurred to me without being suggested by someone else’s work. Not only was there no Internet, but library catalogs were on cards, so I would start by looking in likely places. That might include the subject catalog in the library, the author catalog for authors I knew to have worked on the topic, published (printed) indexes of journals in my field, the tables of contents in the journals I knew well in my field (I was in a small field, Slavic historical linguistics, which helped), and others. If I could find a recent article or two, I could trace back through the bibliography, and then the bibliographies of those sources, and try to benefit from what others had discovered. It was normal to maintain a bibliographic log, a record of where I had been and how I got there, so that I didn’t wind up retracing steps. Once I stopped finding new references, I had probably found all that I was going to find using that method. This meant that I would find things that I might not have known about on my own, but I would find only things that had already been found by someone else.

The browsing part of research in The Paper Age was that the library had open stacks, as Hillman does today, and when I looked up a book, found its shelfmark, and went to retrieve it, I could skim the adjacent titles, which were grouped hierarchically by topic. When I had to work in libraries that had closed stacks, I missed the browsing, which led to serendipitous discoveries. Browsing is easier on the Web than on a library shelf because Web content doesn’t have the same constraints of physical proximity as library books; a page can be one click away from several others, on very different topics, while library books can only be near books that are also near one another. In that sense, browsing on the Web differs from browsing in the stacks more as a matter of degree, and the degree is great, rather than as a totally new way of conducting research.
