### ISSUE TITLE
Returning error "item type xs:base64Binary" during batch transformation

### ISSUE THREAD

**Issue by charlietaylor98** [obdurodon/dh_course#475]
I'm trying to use a batch xsl transformation to return a single, consolidated document from multiple letters using the following code:
`<xsl:template name="xsl:initial-template">
        <letters>
            <xsl:for-each select="collection('All_XML')">
                <xsl:copy-of select="letter"/>
            </xsl:for-each>
        </letters>
    </xsl:template>`

I'm using the oxygen debugger, which returns the error "Required item type of context item for the child axis is node(); supplied expression (.) has item type xs:base64Binary" on the line `<xsl:copy-of select="letter"/>`

**Comment by djbpitt** [comment]
@charlietaylor98 Does the *ALL\_XML* directory contain anything that isn't an XML document? If so, try it with only XML documents in that directory. If that isn’t the problem, can you push the XSLT and the *ALL\_XML* directory to GitHub so that I can pull it and try to debug it? 

By the way, your XSLT runs together as if it were a single line because you surrounded it with single backticks. That works for small, inline snippets, but for multi-line code blocks, you can keep the lineation and indentation by *fencing* the block with triple backticks, on their own lines, with a blank line before the opening backticks and after the closing ones. See <https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks>.

**Comment by charlietaylor98** [comment]
They're all xml documents; I'll push the directory and the xslt

**Comment by djbpitt** [comment]
@charlietaylor98 I can run your *full\_text.xsl* in \<oXygen/\> without error. Was the problem with a different XSLT stylesheet?

**Comment by charlietaylor98** [comment]
Nope, that's the stylesheet I used. Not sure why I'm getting that error. Maybe if I try to run the transformation from the command line instead?

**Comment by djbpitt** [comment]
@charlietaylor98 If you can’t get it to work, we can try screen sharing and debugging together over Zoom. I’ll look for the next update.

**Comment by charlietaylor98** [comment]
Looks like the command line is returning the same error

**Comment by djbpitt** [comment]
@charlietaylor98 I have an appointment at 6:30 p.m. today, but if you’re free before then, we could try to trouble-shoot it over Zoom. Let me know.

**Comment by charlietaylor98** [comment]
@djbpitt I'm free until 6 or after 7 today, so if we could meet over Zoom soon or after your meeting (if it's not too long) that would be best

**Comment by djbpitt** [comment]
@charlietaylor98 Let's try now, in our regular Zoom classroom. I'll start a session now ...

**Comment by djbpitt** [comment]
@charlietaylor98 For the record, the culprit was *.DS\_Store*. Now fixed; closing this issue.
