### ISSUE TITLE
Struggles with the Test

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#48]
Hey everyone, sorry about the late post but I just got back from my uncle's funeral and have just started the test. I was able to get questions 1 and 2 relatively easily but 3 has me entirely stumped; all variations on either `//body/div[count(//sp)]` or `//sp[count(//body/div)]` either return 0 results, or, for some reason, exactly 20, with no discernible difference between the 20 "discovered" items and the rest of the //sp nodes. At this point, I'm just looking to find out why I get 20 results, and not the 1137 or ~200 results I should be seeing, even if this code is constructed entirely incorrectly? Thanks!

**Comment by Idi0teque** [comment]
Also, with regards to 5, why am I finding speeches with 0 lines when I search for `//sp//count(l)`?

**Comment by djbpitt** [comment]
@Idi0teque With respect to your original inquiry, predicates don't return the nodes they reference; they use those nodes to filter the nodes in the preceding path step. When you write `//body/div[count(//sp)]`, you’re asking for `<div>` elements, not counts of `<sp>` elements, because your last path step says “give me the `<div>` elements that satisfy the condition specified in the predicate”. You _are_ counting `<sp>` elements, but you’re using the count as a numerical predicate to select `<div>` elements only in certain positions. Similarly, when you ask for `//sp[count(//body/div)]`, you’re asking not for a count, but for `<sp>` nodes that are in a certain numerical position, because your `count()` function will return a number, so you’re using a numerical—that is, positional—predicate.

And the next question is: _Which_ `<sp>` elements are you counting in your first expression? Hint: not the ones you think you’re counting. What does your predicate construction, `count(//sp)` return, and why?

**Comment by djbpitt** [comment]
@Idi0teque With respect to your second question, you aren’t finding speeches at all; you’re finding integers. If the last path step were `<sp>` nodes (with or without a predicate), you’d be finding `<sp>` nodes. But since your last step is the `count()` function, and the `count()` function returns integers, you’re finding integers. 

But if your question was also about whether there are speeches in the play that contain 0 `<l>` elements, the answer is that there are 432 of them. You might want to review XPath assignment #2, where you explored the various elements that can occur as children or descendants of `<sp>`.

**Comment by Idi0teque** [comment]
(Second question) Thanks, got it! Now just need to figure out how to actually find the speech (part c)...

**Comment by djbpitt** [comment]
One step at a time ...

**Comment by danakaufhold** [comment]
I'm still not understanding how to correctly position the count function, then. I'm also having problems with filtering the string-length by greater than 4000 characters. 
1. If `//body/div[count(//sp)]` asks for the `<div>` elements, then why does `//body/div/sp[count(sp)]` not ask for the `<sp>` elements?

2. I tried //sp/string-length(.) >4000, but that just gives me one value and says "true" - it doesn't tell me which string it is or give me a position. I looked in the book for how to do this and searched in multiple places on the Internet (including the class site) and haven't come up with anything.

**Comment by djbpitt** [comment]
@danakaufhold 

1. `//body/div/sp[count(sp)]` _does_ ask for `<sp>` elements. Specifically, it asks for all of the zeroeth `<sp>` children of each act. Since there aren’t any (for two reasons: acts don’t have speech children, and there is no zeroeth anything because XPath starts counting from one), it returns all zero of them. Can you figure out why your predicate is evaluating to 0, and therefore asking for the zeroeth `<sp>` child of each act?
1. With your `//sp/string-length(.) >4000`, remove the part that reads `> 4000` and run it again, and you get a sequence of integers. That’s because for each `<sp>` you are reporting its string length. The `>` does a _general comparison_ (see the discussion of general comparison toward the bottom of <http://dh.obdurodon.org/functions.xhtml>), which means that it reports true if any item on the left (your sequence of integers) is greater than any item on the right (there’s just one, the integer value 4000). Since there is at least one `<sp>` longer than 4000, it returns true (and it would return true just once even if there were more than one long speech). An XPath expression returns the last path step, which in your case is integers, and not speeches. If you want it to tell you _which_ speeches are longer than 4000 characters, you need to make the speeches (not their lengths) your last path step. You can test the lengths inside a predicate, that is, instead of returning the lengths; use them to filter the speeches and control which ones get returned.

**Comment by mtm80** [comment]
I'm a bit confused about the first question in number 5.  At first, I read it as a total count of all <l> lines in all <sp> elements.  For that I got 2809 with count(//sp/l) but now I'm second guessing myself and thinking that I might have had to break down counts of <l> lines by individual <sp> elements.  Clarification?

**Comment by djbpitt** [comment]
@mtm80 The number of lines in _each_ speech element is a sequence of numbers, with one number per speech. If, for example, there were exactly three speeches in the entire play, you would want an XPath expression that gave you exactly three numbers: the number of lines in the first speech, then the number of lines in the second speech, etc.

With respect to your `count(//sp/l)`, that counts the total number of line _children_ for all speeches, but the question says “Here and in the other parts of this question, count the descendants of the speech, not just the children”. So if you did want just the grand total of all lines in all speeches, you’d use `//sp//l` or `//sp/descendant::l` and you’d find 2949, not 2809.

**Comment by mtm80** [comment]
Number 2 is also giving me trouble.  I get as far as //body/div[4]/div which focuses on act 4 but when I add the rest to make //body/div[4]/div/string-join(distinct-values(//@who), ';') I get a list of all of the speakers from the whole play rather than just the ones in act 4.  Any points?

**Comment by djbpitt** [comment]
You've wrapped `distinct-values()` around an XPath expression. What is that expression? What does it begin with? What's the effect of that beginning?

**Comment by gmd29** [comment]
Check what //@who returns without any of the functions to see if //@who is really the xpath expression you want.
