### ISSUE TITLE
Homework question

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#49]
After creating an xlst for the skyrim file, I created the HTML to pair with a CSS file but the HTML appeared as not well formatted even though the xslt was fine.  Did anyone else encounter this problem?  The following line was inserted between the <head> and <title> elements:
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
If I removed it, the other 6 elements that we used for the body were also marked as not being well-formed.

**Comment by djbpitt** [comment]
@mtm80 Since you were developing your code on step at a time and testing it after every step, what was the step that caused the output to stop being well formed? What was the specific well-formedness error? That is, when you opened the output HTML in &lt;oXygen/&gt;, where was the red squiggly line and what did the error message say.

If you reread your posting, you’ll notice that the markup you entered (except for the `<title>` tag) isn’t visible. That’s because in Markdown angle brackets are processed as tag delimiters, and not rendered literally, and that means that the “tags“ themselves are not shown. The easiest way to fix this is to wrap back ticks (the thing that looks like a grave accent: `\`; it’s usually in the upper left on the keyboard, to the left of the “1” key) around the markup that you want to render literally. You can edit your own posting to fix this error by clicking on the icon that looks like a pencil in the upper right.
