### ISSUE TITLE
XSLT 6

### ISSUE THREAD

**Issue by gmd29** [obdurodon/dh_course#53]
For XSLT 6 I used the xml from our jpop project. We have different sections of the song (i.e. chorus, verse etc.) which I want to delineate using spacing and CSS. But I'm not sure how to write templates for them that output them in the correct order. Any thoughts?

**Comment by Idi0teque** [comment]
Can you be more specific? Are you concerned about the order of your CSS or your XSLT?

**Comment by jachinn** [comment]
Rather than writing specific apply-templates for each song section, you
should write a single apply-templates with no @select. Then you can write
templates for each element to specify any additional styling. You should
review [XSLT #3](http://dh.obdurodon.org/xslt-assignment-03.xhtml) for more
details on this.

Including what code you have so far is a good idea when asking for help.
Otherwise it's hard for us to know what you've tried and how it's broken.
