### ISSUE TITLE
In-class Solution

### ISSUE THREAD

**Issue by gabikeane** [obdurodon/dh_course#54]
Here's the solution for the problem we worked on in class. Post here if you want to challenge yourself to make it even better! As you saw at the end of class, we used an <xsl:choose> element to set different tests to determine what happens when.
[XSLT 6 solution](https://github.com/obdurodon/dh_course/blob/master/XSLT_6/rogers_xslt6.xsl)

**Comment by gabikeane** [comment]
Fixed it!

**Comment by djbpitt** [comment]
One of the things that was nagging at me while we were exploring this task is that we repeat ourselves: we create a `<p>` wrapper for all speeches and we tag all speakers as `<strong>`, and the only difference is that in the middle of this we wrap the `<strong>` elements in `<a>` tags only when there’s a following speech. The `<xsl:choose>` strategy has almost the same code inside the `<xsl:when>` and the `<xsl:otherwise>`; the only difference is the presence or absence of the `<a>` element. Can we get rid of that duplication, in keeping with the principle of [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)?

I had never had occasion to use `<xsl:next-match>` in production before—or perhaps I did and I didn’t recognize the need at the time—but it turns out to be well-suited to removing the repetition in this case. You can read more about it in Michael Kay, but the short version is that you can have multiple templates that match the same element (in this case, a `<speech>`), and normally only the one with highest priority fires. But you can tell the ones with higher priority to call the ones with lower priority by using `<xsl:next-match>`, and if you do that, they’ll all fire, and in the right order. This lets us remove all of the repeated code.

In <https://github.com/obdurodon/dh_course/blob/master/XSLT_6/xsl_next-match.xsl> (you’ll want to have the code in front of you while you read the explanation below) we have three templates that match speeches (the first and third match all speeches, the one in the middle has a predicate that restricts it to speeches that are not the last by their speakers), which fire in the following order, according to their priorities:

* Create the `<p>` wrapper with `@class` and `@id` attributes for all speeches.
* Create an `<a>` element with an `@href` attribute around the speaker name only if there is a following speech by the same speaker. (Note that we’ve used a predicate on the `@match` value to implement the conditional test. This is a common XSLT pattern.)
* Wrap the speaker name in `<strong>` tags.

The first of these templates fires for all speakers, and if there is a following speech by the same speaker, the next match is the second template, and the next match after that is the third. If there isn’t a following speech by the same speaker, the second template doesn’t match, so the next template after the first is the third.
