### ISSUE TITLE
Why you should label your axes

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#60]
You should label your axes so that you won’t wind up like <https://xkcd.com/833/>.

**Comment by JosephDRogers23** [comment]
I once saw a graph (with no actual data, it was just symbolic) that had the X axis labeled "Peace" and the y axis labeled "Over Time", and it had a straight diagonal line with a slope of 1. I appreciated the sentiment but it didn't seem mathematically sound. 
What other graphs have anyone seen that may have missed the mark?

**Comment by mtm80** [comment]
The ones on the Zelda project were a bit tricky to read in a case or two.  Labeling the y-axis of a bar graph only with 0%, 50%, and 100% leaves some of the smaller bars a bit ambiguous.  Otherwise, does anyone have an idea of which type of graph/visual representation is optimal for our projects?  I realize that this can vary by project but I'm speaking in the most general terms.  I'm leaning towards just a traditional bar graph since the Russian project is tracking occurrences of particular rhetorical patterns.
