### ISSUE TITLE
Homework Question

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#62]
So, right now, my graphs are all stacked on top of each other by means of a hacked-together subtraction of each of their previous values (i.e. the height of $RepVotes is `$Height - $DemVotes - $RepVotes`, the height of $LibVotes is `$Height - $DemVotes - $RepVotes - $LibVotes`, etc.), and while that works I was wondering if there was some way similar to `preceding-sibling::` that I could make each subsequent height dependent on its predecessor?
If not, this still works; I just feel it's inefficient. Thanks!

**Comment by djbpitt** [comment]
@Idi0teque +1 for noticing that there’s a pattern at work! The approach you’ve adopted is fine, especially because there are only four parties, so the repetition is limited. But here are a few thoughts about how to make it more elegant:

1. _Masking._ A human looks at a stacked bar chart and thinks that each segment of the bar starts where the last one left off. But because SVG objects are rendered in the order in which they appear in the code, later ones mask earlier ones. That means, for example, that if you put the Republicans at the top of your bar, you can just draw their Y value from 0 to 100. They’ll peek through at the top, and the other parties will mask them elsewhere. Whether that’s a useful strategy in the context of this particular task is a separate question, but because drawing something that’s too large and letting other stuff mask it isn’t always intuitive, it’s worthwhile reminding yourself that it’s an option.
1. _Recursion._ There are good reasons that XSLT follows a declarative programming model, but one consequence of that design that sometimes frustrates new coders (including those who are comfortable with other programming paradigms, but not with the declarative model) is that XSLT doesn’t let you increment the value of a variable in place. For example, you can’t keep a running, accumulating total of the percentage of votes already accounted for, and start where you left off. There are two ways to work within that constraint (I’m not calling it “working around” because it isn’t; it’s a programming paradigm, and not an accommodation to a limitation). They are:
    1. _Recursive function and template calls._ Process the first bar in a named template or user-defined function, and, at the end of the processing, call the same template or function, passing in the accumulated value. In pseudo-code: a) pass 0 to a function that plots the Democrats, then b) pass the top of the Democrat bar to the same function to plot the next party, c) and keep going until you run out of parties. This is called _sibling recursion_, because the parties are sibling nodes. 
    1. _`<xsl:iterate>`_ XSLT 3.0 introduced a new `<xsl:iterate>` function, which provides iterative structures that can be used where earlier version of XSLT required recursion. We illustrate this in a contrastive example at the bottom of <http://dh.obdurodon.org/xslt3.xhtml>.

With all of that said, especially because we haven’t worked with the more idiomatic alternatives described above, the strategy you describe is fine for this assignment. But you get points (well, virtual points) for recognizing that there must be an XSLT-idiomatic alternative to brute-forcing a patterned walk through four political parties. Great question!
