### ISSUE TITLE
Meta-XSLT seems like a code smell

### ISSUE THREAD

**Issue by richiebful** [obdurodon/dh_course#65]
Overall the XSLT for [making reading views](https://github.com/mtm80/russ-project/blob/master/util/gen-reading-view.xslt) has been getting pretty complex, and now I need to tag the topics I generated with MALLET. 

To generate class names from topics, I decided to use a helper [XSLT](https://github.com/mtm80/russ-project/blob/master/util/reading-view-helper/gen-topic-matcher.xslt) that would take my topics and their associated words as [input](https://github.com/mtm80/russ-project/blob/master/analysis/topic-report-30.xml). All of the topics with a name attribute are then transformed to create a "reverse-lookup" XSLT function that takes lemmas as input and outputs the topic name. The output is [here](https://github.com/mtm80/russ-project/blob/master/util/reading-view-helper/topic-matcher.xslt), and I'll ```<xsl:include>``` this function in my reading view generator.

Is this a reasonable way to go about this?

**Comment by djbpitt** [comment]
@richiebful It isn’t uncommon to pipeline XSLT transformations, but it isn’t really needed here, and I think it’s both simpler and more idiomatic to use the MALLET topics file directly to retrieve topics by keyword (using a key). See an example in the new `util/djb` subdirectory on the new `djb` branch (with documentation in [reading-view-with-topics.md](https://github.com/mtm80/russ-project/blob/djb/util/djb/reading-view-with-topics.md)).

The whitespace wrangling, which isn’t directly related to the topic-management strategy, is ... er ... sort of obsessive, and it isn’t strictly necessary, since the browser normalizes whitespace.

**Comment by richiebful** [comment]
Yeah, this approach has me feeling a lot better. Thanks for the help!
