### ISSUE TITLE
Counting Question

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#67]
So, for tomorrow's homework, I've successfully been able to return all plays that contain speaking messengers, servants, or 'all.' However, I run into a problem quantifying this: trying to return a number of these results (by, for example, `count($messenger)`) gives me not the expected single number (22) but instead something like:

`1`

`1`

`1`

`1`

`1`
etc. Any hints on how to get these `1`s to form up into one big easy number that can be actually used?
[edited for formatting]

**Comment by djbpitt** [comment]
It sounds as if you may be counting each play individually, instead of all of them. What’s inside your `count()` function? Is it one play at a time?

**Comment by Idi0teque** [comment]
Ah, that may be the rub; the count is measuring my $messenger, which I won't post because it will give away critical answers, but returns the title of each play that contains a messenger. I think I don't want the title, I want the number...

**Comment by Idi0teque** [comment]
Nope, that wasn't it. Still getting lists of 1s. Right now I'm using a $play[count($messenger) gt 0] to get these numbers; is there something obviously wrong there that I'm missing?

**Comment by djbpitt** [comment]
Look at the value of your `$messenger` variable.

**Comment by rmb165** [comment]
I'll try to be vague in my question because this is about the SVG test, but for the Y value of each rectangle of the bar chart, even though I put in the same calculations as for the presidential elections Y value just replaced with the appropriate element names for the movies, the text output shows the y value of every rectangle to be the same, and it's just y="-"

**Comment by djbpitt** [comment]
@rmb165 If all you’re seeing is a minus sign, it means that the numerical value that you think you’re calculating isn't being calculated. Return just that value, and fine-tune the code until it gives you the value you want. Then poke it into the SVG context, after the minus sign.

**Comment by enb34** [comment]
I'm also having a similar problem with searching for speakers within the entire corpus instead of within singular plays. I either end up with a series of 1s like in @Idi0teque's original post or a series of 966 "true"s. I think I understand what I'm doing wrong here, but I'm completely stuck on how to begin fixing it.

**Comment by danakaufhold** [comment]
I know it's much too late to receive any sort of help on this, but I had trouble as well trying to figure out how to filter speakers by number of appearances in the list of overall speakers. I always forget about this board in my quest to find the right thing, which I hope I will stop doing soon! I think my problem is that I can't figure out in what order I need to use the count function and the contains function. I'm pretty sure, at least, that they both need to be within the where statement, but beyond that I'm completely stumped.

**Comment by mtm80** [comment]
I'm working on this way too late also since I came back late from drill weekend but I'm stumped on the "where" function.  I can see that this means "where there is an instance of a speaker that appears in 10 or more plays" but I'm stuck on how to translate that into computer speak.
