### ISSUE TITLE
XSLT for many files

### ISSUE THREAD

**Issue by brucknerp** [obdurodon/dh_course#73]
I'm working on an XSLT template for all our song files to display on the website. I might be missing something simple, but how do/can you run multiple .xml files through one XSLT?

I'm sure there is an automated process besides manually linking each of our .xml files, manually creating an output file, and running the transformation for all of our 50 songs, but I can't find what I need from Google...

**Comment by djbpitt** [comment]
@brucknerp There are two basic strategies. Both are different enough from what we’ve been doing in class with a single file, though, that you might want to work through the development with your project mentor or another instructor.

1. You can address all of your files at once by using the `collection()` function in XSLT, just as you do in XPath, except that finding them in XSLT may be confusing at first because they’re in your file system, and not in the eXist database. And you can create multiple outputs from a single XSLT stylesheet by using the `<xsl:result-document>` element. The strategy, then, is that within the XSLT stylesheet you define a variable that points to the collection of all of your input documents, you loop over them with `<xsl:for-each>`, and for each one you construct a filename for the output document and create it with `<xsl:result-document>`.
1. Alternatively, you can run `saxon` (the XSLT transformation engine inside &lt;oXygen/&gt;) from the command line. When you specify directories (not single documents) as the input and output, `saxon` runs the transformation over each file in the input directory and writes the result into the output directory. You have may have to clean up the output filenames afterwards.

Neither of these is particularly difficult, but both can be confusing at first, so feel free to come to office hours or make an appointment and we’ll do it with you.
