### ISSUE TITLE
Schematron in projects

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#74]
This is an open ended question for anyone.  Have any of you found a use for schematron in your projects?  Unlike the tutorial that mentioned constraints on page numbers, our texts are all single page files so this doesn't really work for us and we're not working with numerical values either.  Have any of you encountered these situations and how did you resolve them?

**Comment by jachinn** [comment]
The My Immortal project used Schematron to help verify that our document
was structured the way we wanted a bit more specifically than RelaxNG could
handle alone. We wrote about it on the old discussion boards at the time
(and I can dig up that posting if you're interested in what we wrote about
it then), but I'd encourage you to take a look at the Schematron file on
our site and explore the different rules we wrote. During the course of the
semester we ended up changing our minds several times regarding what to
mark up and how, and Schematron let us easily spot places in our text that
we had likely made an error. Our schema did report some false positives--
we were using it to highlight opportunities for error rather than actual
validity of our document, but it allowed us to systematically check the
document for these errors rather than forcing us to do it by hand.

**Comment by djbpitt** [comment]
@mtm80 Good question! Schematron is useful when you imagine ways you could make mistakes in your markup that Schematron could catch, but Relax NG couldn't. We’ve illustrated several cases (and we link to descriptions of a few more in the Schematron section of our main course page), but you’ll want to abstract from that to think about the errors or inconsistencies you could introduce into   your markup.

Don’t forget, though, that to test whether your Schematron is doing what you think it’s doing, you need to introduce the errors and verify that the Schematron flags them. There’s a joke (well, a geek joke) about edge testing, that is, bullet-proofing your code (in our case, markup) by anticipating types of errors and writing Schematron code to catch them. You can see some variations of the joke at <https://www.sempf.net/post/On-Testing1> (“QA” = quality assurance, that is, the development person responsible for anticipating and preventing errors).
